declare
  procedure location( p_place  in varchar2
                    , p_name   in varchar2
                    , p_type   in varchar2
                    , p_flag   in varchar2
                    , p_county in varchar2) is
    v_count       pls_integer;
  begin
  --  dbms_output.put(p_name||' ('||p_county||') ');
    
    select count(*)
    into v_count
    from rnt_cities
    where state='FL'
    and name=upper(p_name);

    if v_count > 0 then
      update rnt_cities
      set census_place = p_place
      where state='FL'
      and name=upper(p_name);
    end if;
  end location;

  procedure seed_locations is
  begin
    location('00075','Acacia Villas','Census Designated Place','S','Palm Beach County');
    location('00375','Alachua','Incorporated Place','A','Alachua County');
    location('00410','Alafaya','Census Designated Place','S','Orange County');
    location('00625','Alford','Incorporated Place','A','Jackson County');
    location('00800','Allentown','Census Designated Place','S','Santa Rosa County');
    location('00950','Altamonte Springs','Incorporated Place','A','Seminole County');
    location('01000','Altha','Incorporated Place','A','Calhoun County');
    location('01050','Altoona','Census Designated Place','S','Lake County');
    location('01100','Alturas','Census Designated Place','S','Polk County');
    location('01125','Alva','Census Designated Place','S','Lee County');
    location('01353','Andrews','Census Designated Place','S','Levy County');
    location('01475','Anna Maria','Incorporated Place','A','Manatee County');
    location('01625','Apalachicola','Incorporated Place','A','Franklin County');
    location('01675','Apollo Beach','Census Designated Place','S','Hillsborough County');
    location('01700','Apopka','Incorporated Place','A','Orange County');
    location('01750','Arcadia','Incorporated Place','A','DeSoto County');
    location('01775','Archer','Incorporated Place','A','Alachua County');
    location('01875','Aripeka','Census Designated Place','S','Hernando County, Pasco County');
    location('02187','Asbury Lake','Census Designated Place','S','Clay County');
    location('02250','Astatula','Incorporated Place','A','Lake County');
    location('02275','Astor','Census Designated Place','S','Lake County');
    location('02400','Atlantic Beach','Incorporated Place','A','Duval County');
    location('02500','Atlantis','Incorporated Place','A','Palm Beach County');
    location('02550','Auburndale','Incorporated Place','A','Polk County');
    location('02575','Aucilla','Census Designated Place','S','Jefferson County');
    location('02660','Avalon','Census Designated Place','S','Santa Rosa County');
    location('02681','Aventura','Incorporated Place','A','Miami-Dade County');
    location('02750','Avon Park','Incorporated Place','A','Highlands County');
    location('02850','Azalea Park','Census Designated Place','S','Orange County');
    location('02900','Babson Park','Census Designated Place','S','Polk County');
    location('02925','Bagdad','Census Designated Place','S','Santa Rosa County');
    location('03250','Baldwin','Incorporated Place','A','Duval County');
    location('03275','Bal Harbour village','Incorporated Place','A','Miami-Dade County');
    location('03375','Balm','Census Designated Place','S','Hillsborough County');
    location('03480','Bardmoor','Census Designated Place','S','Pinellas County');
    location('03675','Bartow','Incorporated Place','A','Polk County');
    location('03725','Bascom','Incorporated Place','A','Jackson County');
    location('03975','Bay Harbor Islands','Incorporated Place','A','Miami-Dade County');
    location('04070','Bay Hill','Census Designated Place','S','Orange County');
    location('04150','Bay Lake','Incorporated Place','A','Orange County');
    location('04162','Bayonet Point','Census Designated Place','S','Pasco County');
    location('04200','Bay Pines','Census Designated Place','S','Pinellas County');
    location('04250','Bayport','Census Designated Place','S','Hernando County');
    location('04350','Bayshore Gardens','Census Designated Place','S','Manatee County');
    location('04650','Beacon Square','Census Designated Place','S','Pasco County');
    location('04735','Bear Creek','Census Designated Place','S','Pinellas County');
    location('04925','Bee Ridge','Census Designated Place','S','Sarasota County');
    location('04975','Bell','Incorporated Place','A','Gilchrist County');
    location('05025','Bellair-Meadowbrook Terrace','Census Designated Place','S','Clay County');
    location('05075','Belleair','Incorporated Place','A','Pinellas County');
    location('05100','Belleair Beach','Incorporated Place','A','Pinellas County');
    location('05125','Belleair Bluffs','Incorporated Place','A','Pinellas County');
    location('05150','Belleair Shore','Incorporated Place','A','Pinellas County');
    location('05200','Belle Glade','Incorporated Place','A','Palm Beach County');
    location('05300','Belle Isle','Incorporated Place','A','Orange County');
    location('05375','Belleview','Incorporated Place','A','Marion County');
    location('05462','Bellview','Census Designated Place','S','Escambia County');
    location('05825','Berrydale','Census Designated Place','S','Santa Rosa County');
    location('06100','Beverly Beach','Incorporated Place','A','Flagler County');
    location('06125','Beverly Hills','Census Designated Place','S','Citrus County');
    location('06350','Big Coppitt Key','Census Designated Place','S','Monroe County');
    location('06425','Big Pine Key','Census Designated Place','S','Monroe County');
    location('06600','Biscayne Park village','Incorporated Place','A','Miami-Dade County');
    location('06625','Bithlo','Census Designated Place','S','Orange County');
    location('06667','Black Diamond','Census Designated Place','S','Citrus County');
    location('06670','Black Hammock','Census Designated Place','S','Seminole County');
    location('06875','Bloomingdale','Census Designated Place','S','Hillsborough County');
    location('06925','Blountstown','Incorporated Place','A','Calhoun County');
    location('07300','Boca Raton','Incorporated Place','A','Palm Beach County');
    location('07375','Bokeelia','Census Designated Place','S','Lee County');
    location('07450','Bonifay','Incorporated Place','A','Holmes County');
    location('07525','Bonita Springs','Incorporated Place','A','Lee County');
    location('07687','Boulevard Gardens','Census Designated Place','S','Broward County');
    location('07775','Bowling Green','Incorporated Place','A','Hardee County');
    location('07875','Boynton Beach','Incorporated Place','A','Palm Beach County');
    location('07950','Bradenton','Incorporated Place','A','Manatee County');
    location('07975','Bradenton Beach','Incorporated Place','A','Manatee County');
    location('08125','Bradley Junction','Census Designated Place','S','Polk County');
    location('08150','Brandon','Census Designated Place','S','Hillsborough County');
    location('08175','Branford','Incorporated Place','A','Suwannee County');
    location('08300','Brent','Census Designated Place','S','Escambia County');
    location('08450','Brewster','Census Designated Place','S','Polk County');
    location('08575','Briny Breezes','Incorporated Place','A','Palm Beach County');
    location('08600','Bristol','Incorporated Place','A','Liberty County');
    location('08650','Broadview Park','Census Designated Place','S','Broward County');
    location('08700','Bronson','Incorporated Place','A','Levy County');
    location('08725','Brooker','Incorporated Place','A','Bradford County');
    location('08762','Brookridge','Census Designated Place','S','Hernando County');
    location('08800','Brooksville','Incorporated Place','A','Hernando County');
    location('08925','Brownsdale','Census Designated Place','S','Santa Rosa County');
    location('09000','Brownsville','Census Designated Place','S','Miami-Dade County');
    location('09315','Buckhead Ridge','Census Designated Place','S','Glades County');
    location('09350','Buckingham','Census Designated Place','S','Lee County');
    location('09415','Buenaventura Lakes','Census Designated Place','S','Osceola County');
    location('09550','Bunnell','Incorporated Place','A','Flagler County');
    location('09612','Burnt Store Marina','Census Designated Place','S','Lee County');
    location('09625','Bushnell','Incorporated Place','A','Sumter County');
    location('09630','Butler Beach','Census Designated Place','S','St. Johns County');
    location('09655','Cabana Colony','Census Designated Place','S','Palm Beach County');
    location('09700','Callahan','Incorporated Place','A','Nassau County');
    location('09725','Callaway','Incorporated Place','A','Bay County');
    location('09875','Campbell','Census Designated Place','S','Osceola County');
    location('09900','Campbellton','Incorporated Place','A','Jackson County');
    location('10100','Canal Point','Census Designated Place','S','Palm Beach County');
    location('10250','Cape Canaveral','Incorporated Place','A','Brevard County');
    location('10275','Cape Coral','Incorporated Place','A','Lee County');
    location('10425','Captiva','Census Designated Place','S','Lee County');
    location('10725','Carrabelle','Incorporated Place','A','Franklin County');
    location('10825','Carrollwood','Census Designated Place','S','Hillsborough County');
    location('10975','Caryville','Incorporated Place','A','Washington County');
    location('11050','Casselberry','Incorporated Place','A','Seminole County');
    location('11150','Cedar Grove','Census Designated Place','S','Bay County');
    location('11225','Cedar Key','Incorporated Place','A','Levy County');
    location('11285','Celebration','Census Designated Place','S','Osceola County');
    location('11325','Center Hill','Incorporated Place','A','Sumter County');
    location('11362','Century','Incorporated Place','A','Escambia County');
    location('11597','Charleston Park','Census Designated Place','S','Lee County');
    location('11625','Charlotte Harbor','Census Designated Place','S','Charlotte County');
    location('11650','Charlotte Park','Census Designated Place','S','Charlotte County');
    location('11800','Chattahoochee','Incorporated Place','A','Gadsden County');
    location('11912','Cheval','Census Designated Place','S','Hillsborough County');
    location('11925','Chiefland','Incorporated Place','A','Levy County');
    location('11975','Chipley','Incorporated Place','A','Washington County');
    location('12150','Chokoloskee','Census Designated Place','S','Collier County');
    location('12250','Christmas','Census Designated Place','S','Orange County');
    location('12275','Chuluota','Census Designated Place','S','Seminole County');
    location('12300','Chumuckla','Census Designated Place','S','Santa Rosa County');
    location('12325','Cinco Bayou','Incorporated Place','A','Okaloosa County');
    location('12412','Citrus Hills','Census Designated Place','S','Citrus County');
    location('12425','Citrus Park','Census Designated Place','S','Hillsborough County');
    location('12450','Citrus Springs','Census Designated Place','S','Citrus County');
    location('12675','Clarcona','Census Designated Place','S','Orange County');
    location('12875','Clearwater Beach','Incorporated Place','A','Pinellas County');
    location('12925','Clermont','Incorporated Place','A','Lake County');
    location('12950','Cleveland','Census Designated Place','S','Charlotte County');
    location('13000','Clewiston','Incorporated Place','A','Hendry County');
    location('13050','Cloud Lake','Incorporated Place','A','Palm Beach County');
    location('13125','Cobbtown','Census Designated Place','S','Santa Rosa County');
    location('13150','Cocoa','Incorporated Place','A','Brevard County');
    location('13175','Cocoa Beach','Incorporated Place','A','Brevard County');
    location('13225','Cocoa West','Census Designated Place','S','Brevard County');
    location('13275','Coconut Creek','Incorporated Place','A','Broward County');
    location('13400','Coleman','Incorporated Place','A','Sumter County');
    location('13775','Combee Settlement','Census Designated Place','S','Polk County');
    location('13965','Connerton','Census Designated Place','S','Pasco County');
    location('14050','Conway','Census Designated Place','S','Orange County');
    location('14125','Cooper City','Incorporated Place','A','Broward County');
    location('14250','Coral Gables','Incorporated Place','A','Miami-Dade County');
    location('14400','Coral Springs','Incorporated Place','A','Broward County');
    location('14412','Coral Terrace','Census Designated Place','S','Miami-Dade County');
    location('14700','Cortez','Census Designated Place','S','Manatee County');
    location('14850','Cottondale','Incorporated Place','A','Jackson County');
    location('14895','Country Club','Census Designated Place','S','Miami-Dade County');
    location('15055','Country Walk','Census Designated Place','S','Miami-Dade County');
    location('15300','Crawfordville','Census Designated Place','S','Wakulla County');
    location('15325','Crescent Beach','Census Designated Place','S','St. Johns County');
    location('15375','Crescent City','Incorporated Place','A','Putnam County');
    location('15475','Crestview','Incorporated Place','A','Okaloosa County');
    location('15515','Crooked Lake Park','Census Designated Place','S','Polk County');
    location('15575','Cross City','Incorporated Place','A','Dixie County');
    location('15725','Crystal Lake','Census Designated Place','S','Polk County');
    location('15775','Crystal River','Incorporated Place','A','Citrus County');
    location('15800','Crystal Springs','Census Designated Place','S','Pasco County');
    location('15862','Cudjoe Key','Census Designated Place','S','Monroe County');
    location('15968','Cutler Bay','Incorporated Place','A','Miami-Dade County');
    location('16050','Cypress Gardens','Census Designated Place','S','Polk County');
    location('16062','Cypress Lake','Census Designated Place','S','Lee County');
    location('16100','Cypress Quarters','Census Designated Place','S','Okeechobee County');
    location('16125','Dade City','Incorporated Place','A','Pasco County');
    location('16175','Dade City North','Census Designated Place','S','Pasco County');
    location('16335','Dania Beach','Incorporated Place','A','Broward County');
    location('16450','Davenport','Incorporated Place','A','Polk County');
    location('16475','Davie','Incorporated Place','A','Broward County');
    location('16500','Day','Census Designated Place','S','Lafayette County');
    location('16525','Daytona Beach','Incorporated Place','A','Volusia County');
    location('16550','Daytona Beach Shores','Incorporated Place','A','Volusia County');
    location('16675','DeBary','Incorporated Place','A','Volusia County');
    location('16725','Deerfield Beach','Incorporated Place','A','Broward County');
    location('16800','DeFuniak Springs','Incorporated Place','A','Walton County');
    location('16875','DeLand','Incorporated Place','A','Volusia County');
    location('16937','DeLand Southwest','Census Designated Place','S','Volusia County');
    location('16975','De Leon Springs','Census Designated Place','S','Volusia County');
    location('17100','Delray Beach','Incorporated Place','A','Palm Beach County');
    location('17200','Deltona','Incorporated Place','A','Volusia County');
    location('17300','Desoto Lakes','Census Designated Place','S','Sarasota County');
    location('17325','Destin','Incorporated Place','A','Okaloosa County');
    location('17450','Dickerson City','Census Designated Place','S','Santa Rosa County');
    location('17710','Dixonville','Census Designated Place','S','Santa Rosa County');
    location('17725','Doctor Phillips','Census Designated Place','S','Orange County');
    location('17935','Doral','Incorporated Place','A','Miami-Dade County');
    location('18075','Dover','Census Designated Place','S','Hillsborough County');
    location('18425','Duck Key','Census Designated Place','S','Monroe County');
    location('18550','Dundee','Incorporated Place','A','Polk County');
    location('18575','Dunedin','Incorporated Place','A','Pinellas County');
    location('18675','Dunnellon','Incorporated Place','A','Marion County');
    location('18875','Eagle Lake','Incorporated Place','A','Polk County');
    location('19025','East Bronson','Census Designated Place','S','Levy County');
    location('19206','East Lake','Census Designated Place','S','Pinellas County');
    location('19212','East Lake-Orient Park','Census Designated Place','S','Hillsborough County');
    location('19275','East Milton','Census Designated Place','S','Santa Rosa County');
    location('19350','East Palatka','Census Designated Place','S','Putnam County');
    location('19400','Eastpoint','Census Designated Place','S','Franklin County');
    location('19575','East Williston','Census Designated Place','S','Levy County');
    location('19650','Eatonville','Incorporated Place','A','Orange County');
    location('19725','Ebro','Incorporated Place','A','Washington County');
    location('19825','Edgewater','Incorporated Place','A','Volusia County');
    location('19900','Edgewood','Incorporated Place','A','Orange County');
    location('20050','Eglin AFB','Census Designated Place','S','Okaloosa County');
    location('20108','Egypt Lake-Leto','Census Designated Place','S','Hillsborough County');
    location('20275','Elfers','Census Designated Place','S','Pasco County');
    location('20375','Ellenton','Census Designated Place','S','Manatee County');
    location('20650','El Portal village','Incorporated Place','A','Miami-Dade County');
    location('20825','Englewood','Census Designated Place','S','Charlotte County, Sarasota County');
    location('20925','Ensley','Census Designated Place','S','Escambia County');
    location('21150','Estero','Census Designated Place','S','Lee County');
    location('21250','Esto','Incorporated Place','A','Holmes County');
    location('21350','Eustis','Incorporated Place','A','Lake County');
    location('21425','Everglades City','Incorporated Place','A','Collier County');
    location('21750','Fairview Shores','Census Designated Place','S','Orange County');
    location('21850','Fanning Springs','Incorporated Place','A','Gilchrist County, Levy County');
    location('21945','Feather Sound','Census Designated Place','S','Pinellas County');
    location('22100','Fellsmere','Incorporated Place','A','Indian River County');
    location('22175','Fernandina Beach','Incorporated Place','A','Nassau County');
    location('22225','Ferndale','Census Designated Place','S','Lake County');
    location('22250','Fern Park','Census Designated Place','S','Seminole County');
    location('22275','Ferry Pass','Census Designated Place','S','Escambia County');
    location('22325','Fidelis','Census Designated Place','S','Santa Rosa County');
    location('22375','Fisher Island','Census Designated Place','S','Miami-Dade County');
    location('22387','Fish Hawk','Census Designated Place','S','Hillsborough County');
    location('22475','Five Points','Census Designated Place','S','Columbia County');
    location('22550','Flagler Beach','Incorporated Place','A','Flagler County, Volusia County');
    location('22560','Flagler Estates','Census Designated Place','S','St. Johns County');
    location('22660','Fleming Island','Census Designated Place','S','Clay County');
    location('22775','Floral City','Census Designated Place','S','Citrus County');
    location('22975','Florida City','Incorporated Place','A','Miami-Dade County');
    location('23050','Florida Ridge','Census Designated Place','S','Indian River County');
    location('23125','Floridatown','Census Designated Place','S','Santa Rosa County');
    location('23375','Forest City','Census Designated Place','S','Seminole County');
    location('23730','Fort Denaud','Census Designated Place','S','Hendry County');
    location('23850','Fort Green','Census Designated Place','S','Hardee County');
    location('23875','Fort Green Springs','Census Designated Place','S','Hardee County');
    location('24000','Fort Lauderdale','Incorporated Place','A','Broward County');
    location('24100','Fort Meade','Incorporated Place','A','Polk County');
    location('24125','Fort Myers','Incorporated Place','A','Lee County');
    location('24150','Fort Myers Beach','Incorporated Place','A','Lee County');
    location('24175','Fort Myers Shores','Census Designated Place','S','Lee County');
    location('24300','Fort Pierce','Incorporated Place','A','St. Lucie County');
    location('24337','Fort Pierce North','Census Designated Place','S','St. Lucie County');
    location('24387','Fort Pierce South','Census Designated Place','S','St. Lucie County');
    location('24475','Fort Walton Beach','Incorporated Place','A','Okaloosa County');
    location('24500','Fort White','Incorporated Place','A','Columbia County');
    location('24562','Fountainebleau','Census Designated Place','S','Miami-Dade County');
    location('24581','Four Corners','Census Designated Place','S','Lake County, Orange County, Osceola County, Polk County');
    location('24710','Franklin Park','Census Designated Place','S','Broward County');
    location('24825','Freeport','Incorporated Place','A','Walton County');
    location('24900','Frostproof','Incorporated Place','A','Polk County');
    location('24925','Fruit Cove','Census Designated Place','S','St. Johns County');
    location('24975','Fruitland Park','Incorporated Place','A','Lake County');
    location('25000','Fruitville','Census Designated Place','S','Sarasota County');
    location('25025','Fuller Heights','Census Designated Place','S','Polk County');
    location('25125','Fussels Corner','Census Designated Place','S','Polk County');
    location('25175','Gainesville','Incorporated Place','A','Alachua County');
    location('25392','Garcon Point','Census Designated Place','S','Santa Rosa County');
    location('25475','Garden Grove','Census Designated Place','S','Hernando County');
    location('25550','Gardner','Census Designated Place','S','Hardee County');
    location('25655','Gateway','Census Designated Place','S','Lee County');
    location('25750','Geneva','Census Designated Place','S','Seminole County');
    location('25900','Gibsonton','Census Designated Place','S','Hillsborough County');
    location('25925','Gifford','Census Designated Place','S','Indian River County');
    location('25987','Gladeview','Census Designated Place','S','Miami-Dade County');
    location('26000','Glencoe','Census Designated Place','S','Volusia County');
    location('26050','Glen Ridge','Incorporated Place','A','Palm Beach County');
    location('26075','Glen Saint Mary','Incorporated Place','A','Baker County');
    location('26100','Glenvar Heights','Census Designated Place','S','Miami-Dade County');
    location('26250','Golden Beach','Incorporated Place','A','Miami-Dade County');
    location('26300','Golden Gate','Census Designated Place','S','Collier County');
    location('26375','Golden Glades','Census Designated Place','S','Miami-Dade County');
    location('26475','Goldenrod','Census Designated Place','S','Orange County, Seminole County');
    location('26550','Golf village','Incorporated Place','A','Palm Beach County');
    location('26700','Gonzalez','Census Designated Place','S','Escambia County');
    location('26775','Goodland','Census Designated Place','S','Collier County');
    location('26900','Gotha','Census Designated Place','S','Orange County');
    location('26925','Goulding','Census Designated Place','S','Escambia County');
    location('26950','Goulds','Census Designated Place','S','Miami-Dade County');
    location('27000','Graceville','Incorporated Place','A','Jackson County');
    location('27175','Grand Ridge','Incorporated Place','A','Jackson County');
    location('27256','Grant-Valkaria','Incorporated Place','A','Brevard County');
    location('27322','Greenacres','Incorporated Place','A','Palm Beach County');
    location('27360','Greenbriar','Census Designated Place','S','Pinellas County');
    location('27400','Green Cove Springs','Incorporated Place','A','Clay County');
    location('27550','Greensboro','Incorporated Place','A','Gadsden County');
    location('27575','Greenville','Incorporated Place','A','Madison County');
    location('27600','Greenwood','Incorporated Place','A','Jackson County');
    location('27635','Grenelefe','Census Designated Place','S','Polk County');
    location('27650','Gretna','Incorporated Place','A','Gadsden County');
    location('27775','Grove City','Census Designated Place','S','Charlotte County');
    location('27800','Groveland','Incorporated Place','A','Lake County');
    location('28000','Gulf Breeze','Incorporated Place','A','Santa Rosa County');
    location('28050','Gulf Gate Estates','Census Designated Place','S','Sarasota County');
    location('28175','Gulfport','Incorporated Place','A','Pinellas County');
    location('28275','Gulf Stream','Incorporated Place','A','Palm Beach County');
    location('28305','Gun Club Estates','Census Designated Place','S','Palm Beach County');
    location('28400','Haines City','Incorporated Place','A','Polk County');
    location('28452','Hallandale Beach','Incorporated Place','A','Broward County');
    location('28575','Hampton','Incorporated Place','A','Bradford County');
    location('28650','Harbor Bluffs','Census Designated Place','S','Pinellas County');
    location('28800','Harbour Heights','Census Designated Place','S','Charlotte County');
    location('28925','Harlem','Census Designated Place','S','Hendry County');
    location('28937','Harlem Heights','Census Designated Place','S','Lee County');
    location('29000','Harold','Census Designated Place','S','Santa Rosa County');
    location('29100','Hastings','Incorporated Place','A','St. Johns County');
    location('29150','Havana','Incorporated Place','A','Gadsden County');
    location('29200','Haverhill','Incorporated Place','A','Palm Beach County');
    location('29275','Hawthorne','Incorporated Place','A','Alachua County');
    location('29320','Heathrow','Census Designated Place','S','Seminole County');
    location('29385','Heritage Pines','Census Designated Place','S','Pasco County');
    location('29425','Hernando','Census Designated Place','S','Citrus County');
    location('29437','Hernando Beach','Census Designated Place','S','Hernando County');
    location('30000','Hialeah','Incorporated Place','A','Miami-Dade County');
    location('30025','Hialeah Gardens','Incorporated Place','A','Miami-Dade County');
    location('30200','Highland Beach','Incorporated Place','A','Palm Beach County');
    location('30225','Highland City','Census Designated Place','S','Polk County');
    location('30325','Highland Park village','Incorporated Place','A','Polk County');
    location('30494','High Point','Census Designated Place','S','Hernando County');
    location('30525','High Springs','Incorporated Place','A','Alachua County');
    location('30700','Hillcrest Heights','Incorporated Place','A','Polk County');
    location('30750','Hilliard','Incorporated Place','A','Nassau County');
    location('30800','Hill ''n Dale','Census Designated Place','S','Hernando County');
    location('30850','Hillsboro Beach','Incorporated Place','A','Broward County');
    location('30858','Hillsboro Pines','Census Designated Place','S','Broward County');
    location('30975','Hobe Sound','Census Designated Place','S','Martin County');
    location('31025','Holden Heights','Census Designated Place','S','Orange County');
    location('31075','Holiday','Census Designated Place','S','Pasco County');
    location('31275','Holley','Census Designated Place','S','Santa Rosa County');
    location('31350','Holly Hill','Incorporated Place','A','Volusia County');
    location('32000','Hollywood','Incorporated Place','A','Broward County');
    location('32150','Holmes Beach','Incorporated Place','A','Manatee County');
    location('32250','Homeland','Census Designated Place','S','Polk County');
    location('32275','Homestead','Incorporated Place','A','Miami-Dade County');
    location('32325','Homestead Base','Census Designated Place','S','Miami-Dade County');
    location('32375','Homosassa','Census Designated Place','S','Citrus County');
    location('32400','Homosassa Springs','Census Designated Place','S','Citrus County');
    location('32610','Horizon West','Census Designated Place','S','Orange County');
    location('32650','Horseshoe Beach','Incorporated Place','A','Dixie County');
    location('32675','Hosford','Census Designated Place','S','Liberty County');
    location('32775','Howey in the Hills','Incorporated Place','A','Lake County');
    location('32825','Hudson','Census Designated Place','S','Pasco County');
    location('32967','Hunters Creek','Census Designated Place','S','Orange County');
    location('32993','Hutchinson Island South','Census Designated Place','S','St. Lucie County');
    location('33150','Hypoluxo','Incorporated Place','A','Palm Beach County');
    location('33250','Immokalee','Census Designated Place','S','Collier County');
    location('33375','Indialantic','Incorporated Place','A','Brevard County');
    location('33425','Indian Creek village','Incorporated Place','A','Miami-Dade County');
    location('33450','Indian Harbour Beach','Incorporated Place','A','Brevard County');
    location('33585','Indian River Estates','Census Designated Place','S','St. Lucie County');
    location('33600','Indian River Shores','Incorporated Place','A','Indian River County');
    location('33625','Indian Rocks Beach','Incorporated Place','A','Pinellas County');
    location('33675','Indian Shores','Incorporated Place','A','Pinellas County');
    location('33700','Indiantown','Census Designated Place','S','Martin County');
    location('33800','Inglis','Incorporated Place','A','Levy County');
    location('33900','Interlachen','Incorporated Place','A','Putnam County');
    location('33950','Inverness','Incorporated Place','A','Citrus County');
    location('33958','Inverness Highlands North','Census Designated Place','S','Citrus County');
    location('33966','Inverness Highlands South','Census Designated Place','S','Citrus County');
    location('34000','Inwood','Census Designated Place','S','Polk County');
    location('34012','Iona','Census Designated Place','S','Lee County');
    location('34132','Islamorada, Village of Islands village','Incorporated Place','A','Monroe County');
    location('34175','Islandia','Incorporated Place','I','Miami-Dade County');
    location('34185','Island Walk','Census Designated Place','S','Collier County');
    location('34275','Istachatta','Census Designated Place','S','Hernando County');
    location('34400','Ives Estates','Census Designated Place','S','Miami-Dade County');
    location('35000','Jacksonville','Incorporated Place','A','Duval County');
    location('35050','Jacksonville Beach','Incorporated Place','A','Duval County');
    location('35200','Jacob City','Incorporated Place','A','Jackson County');
    location('35300','Jan Phyl Village','Census Designated Place','S','Polk County');
    location('35350','Jasmine Estates','Census Designated Place','S','Pasco County');
    location('35375','Jasper','Incorporated Place','A','Hamilton County');
    location('35425','Jay','Incorporated Place','A','Santa Rosa County');
    location('35525','Jennings','Incorporated Place','A','Hamilton County');
    location('35550','Jensen Beach','Census Designated Place','S','Martin County');
    location('35800','June Park','Census Designated Place','S','Brevard County');
    location('35850','Juno Beach','Incorporated Place','A','Palm Beach County');
    location('35862','Juno Ridge','Census Designated Place','S','Palm Beach County');
    location('35875','Jupiter','Incorporated Place','A','Palm Beach County');
    location('35890','Jupiter Farms','Census Designated Place','S','Palm Beach County');
    location('35900','Jupiter Inlet Colony','Incorporated Place','A','Palm Beach County');
    location('35925','Jupiter Island','Incorporated Place','A','Martin County');
    location('35950','Kathleen','Census Designated Place','S','Polk County');
    location('36062','Kendale Lakes','Census Designated Place','S','Miami-Dade County');
    location('36100','Kendall','Census Designated Place','S','Miami-Dade County');
    location('36121','Kendall West','Census Designated Place','S','Miami-Dade County');
    location('36175','Kenneth City','Incorporated Place','A','Pinellas County');
    location('36200','Kensington Park','Census Designated Place','S','Sarasota County');
    location('36220','Kenwood Estates','Census Designated Place','S','Palm Beach County');
    location('36300','Key Biscayne','Incorporated Place','A','Miami-Dade County');
    location('36325','Key Colony Beach','Incorporated Place','A','Monroe County');
    location('36375','Key Largo','Census Designated Place','S','Monroe County');
    location('36462','Keystone','Census Designated Place','S','Hillsborough County');
    location('36475','Keystone Heights','Incorporated Place','A','Clay County');
    location('36535','Key Vista','Census Designated Place','S','Pasco County');
    location('36550','Key West','Incorporated Place','A','Monroe County');
    location('36950','Kissimmee','Incorporated Place','A','Osceola County');
    location('37225','LaBelle','Incorporated Place','A','Hendry County');
    location('37275','Lacoochee','Census Designated Place','S','Pasco County');
    location('37300','La Crosse','Incorporated Place','A','Alachua County');
    location('37375','Lady Lake','Incorporated Place','A','Lake County');
    location('37500','Laguna Beach','Census Designated Place','S','Bay County');
    location('37525','Lake Alfred','Incorporated Place','A','Polk County');
    location('37542','Lake Belvedere Estates','Census Designated Place','S','Palm Beach County');
    location('37625','Lake Buena Vista','Incorporated Place','A','Orange County');
    location('37648','Lake Butler','Census Designated Place','S','Orange County');
    location('37650','Lake Butler','Incorporated Place','A','Union County');
    location('37775','Lake City','Incorporated Place','A','Columbia County');
    location('37800','Lake Clarke Shores','Incorporated Place','A','Palm Beach County');
    location('37975','Lake Hamilton','Incorporated Place','A','Polk County');
    location('38000','Lake Harbor','Census Designated Place','S','Palm Beach County');
    location('38012','Lake Hart','Census Designated Place','S','Orange County');
    location('38025','Lake Helen','Incorporated Place','A','Volusia County');
    location('38162','Lake Kathryn','Census Designated Place','S','Lake County');
    location('38250','Lakeland','Incorporated Place','A','Polk County');
    location('38262','Lakeland Highlands','Census Designated Place','S','Polk County');
    location('38275','Lake Lindsey','Census Designated Place','S','Hernando County');
    location('38287','Lake Lorraine','Census Designated Place','S','Okaloosa County');
    location('38332','Lake Mack-Forest Hills','Census Designated Place','S','Lake County');
    location('38350','Lake Magdalene','Census Designated Place','S','Hillsborough County');
    location('38425','Lake Mary','Incorporated Place','A','Seminole County');
    location('38430','Lake Mary Jane','Census Designated Place','S','Orange County');
    location('38519','Lake Mystic','Census Designated Place','S','Liberty County');
    location('38575','Lake Panasoffkee','Census Designated Place','S','Sumter County');
    location('38600','Lake Park','Incorporated Place','A','Palm Beach County');
    location('38625','Lake Placid','Incorporated Place','A','Highlands County');
    location('38690','Lake Sarasota','Census Designated Place','S','Sarasota County');
    location('38813','Lakeside','Census Designated Place','S','Clay County');
    location('38950','Lake Wales','Incorporated Place','A','Polk County');
    location('39056','Lakewood Gardens','Census Designated Place','S','Palm Beach County');
    location('39062','Lakewood Park','Census Designated Place','S','St. Lucie County');
    location('39075','Lake Worth','Incorporated Place','A','Palm Beach County');
    location('39100','Lamont','Census Designated Place','S','Jefferson County');
    location('39200','Land O Lakes','Census Designated Place','S','Pasco County');
    location('39375','Lantana','Incorporated Place','A','Palm Beach County');
    location('39425','Largo','Incorporated Place','A','Pinellas County');
    location('39475','Lauderdale-by-the-Sea','Incorporated Place','A','Broward County');
    location('39525','Lauderdale Lakes','Incorporated Place','A','Broward County');
    location('39550','Lauderhill','Incorporated Place','A','Broward County');
    location('39600','Laurel','Census Designated Place','S','Sarasota County');
    location('39650','Laurel Hill','Incorporated Place','A','Okaloosa County');
    location('39700','Lawtey','Incorporated Place','A','Bradford County');
    location('39725','Layton','Incorporated Place','A','Monroe County');
    location('39750','Lazy Lake village','Incorporated Place','A','Broward County');
    location('39775','Lealman','Census Designated Place','S','Pinellas County');
    location('39825','Lecanto','Census Designated Place','S','Citrus County');
    location('39850','Lee','Incorporated Place','A','Madison County');
    location('39875','Leesburg','Incorporated Place','A','Lake County');
    location('39925','Lehigh Acres','Census Designated Place','S','Lee County');
    location('39950','Leisure City','Census Designated Place','S','Miami-Dade County');
    location('39987','Lely','Census Designated Place','S','Collier County');
    location('40037','Lely Resort','Census Designated Place','S','Collier County');
    location('40100','Lemon Grove','Census Designated Place','S','Hardee County');
    location('40450','Lighthouse Point','Incorporated Place','A','Broward County');
    location('40525','Limestone','Census Designated Place','S','Hardee County');
    location('40562','Limestone Creek','Census Designated Place','S','Palm Beach County');
    location('40750','Lisbon','Census Designated Place','S','Lake County');
    location('40875','Live Oak','Incorporated Place','A','Suwannee County');
    location('40950','Lloyd','Census Designated Place','S','Jefferson County');
    location('40985','Lochmoor Waterway Estates','Census Designated Place','S','Lee County');
    location('41025','Lockhart','Census Designated Place','S','Orange County');
    location('41150','Longboat Key','Incorporated Place','A','Manatee County, Sarasota County');
    location('41250','Longwood','Incorporated Place','A','Seminole County');
    location('41400','Loughman','Census Designated Place','S','Polk County');
    location('41562','Lower Grand Lagoon','Census Designated Place','S','Bay County');
    location('41577','Loxahatchee Groves','Incorporated Place','A','Palm Beach County');
    location('41775','Lutz','Census Designated Place','S','Hillsborough County');
    location('41825','Lynn Haven','Incorporated Place','A','Bay County');
    location('41950','Macclenny','Incorporated Place','A','Baker County');
    location('42090','McGregor','Census Designated Place','S','Lee County');
    location('42150','McIntosh','Incorporated Place','A','Marion County');
    location('42400','Madeira Beach','Incorporated Place','A','Pinellas County');
    location('42425','Madison','Incorporated Place','A','Madison County');
    location('42575','Maitland','Incorporated Place','A','Orange County');
    location('42625','Malabar','Incorporated Place','A','Brevard County');
    location('42650','Malone','Incorporated Place','A','Jackson County');
    location('42700','Manalapan','Incorporated Place','A','Palm Beach County');
    location('42750','Manasota Key','Census Designated Place','S','Charlotte County');
    location('42787','Manatee Road','Census Designated Place','S','Levy County');
    location('42850','Mango','Census Designated Place','S','Hillsborough County');
    location('42900','Mangonia Park','Incorporated Place','A','Palm Beach County');
    location('43000','Marathon','Incorporated Place','A','Monroe County');
    location('43083','Marco Island','Incorporated Place','A','Collier County');
    location('43125','Margate','Incorporated Place','A','Broward County');
    location('43175','Marianna','Incorporated Place','A','Jackson County');
    location('43250','Marineland','Incorporated Place','A','Flagler County, St. Johns County');
    location('43375','Mary Esther','Incorporated Place','A','Okaloosa County');
    location('43400','Masaryktown','Census Designated Place','S','Hernando County');
    location('43425','Mascotte','Incorporated Place','A','Lake County');
    location('43475','Matlacha','Census Designated Place','S','Lee County');
    location('43484','Matlacha Isles-Matlacha Shores','Census Designated Place','S','Lee County');
    location('43575','Mayo','Incorporated Place','A','Lafayette County');
    location('43785','Meadow Oaks','Census Designated Place','S','Pasco County');
    location('43800','Meadow Woods','Census Designated Place','S','Orange County');
    location('43900','Medley','Incorporated Place','A','Miami-Dade County');
    location('43925','Medulla','Census Designated Place','S','Polk County');
    location('43975','Melbourne','Incorporated Place','A','Brevard County');
    location('44000','Melbourne Beach','Incorporated Place','A','Brevard County');
    location('44075','Melbourne Village','Incorporated Place','A','Brevard County');
    location('44175','Memphis','Census Designated Place','S','Manatee County');
    location('44275','Merritt Island','Census Designated Place','S','Brevard County');
    location('44300','Mexico Beach','Incorporated Place','A','Bay County');
    location('45000','Miami','Incorporated Place','A','Miami-Dade County');
    location('45025','Miami Beach','Incorporated Place','A','Miami-Dade County');
    location('45060','Miami Gardens','Incorporated Place','A','Miami-Dade County');
    location('45100','Miami Lakes','Incorporated Place','A','Miami-Dade County');
    location('45175','Miami Shores village','Incorporated Place','A','Miami-Dade County');
    location('45200','Miami Springs','Incorporated Place','A','Miami-Dade County');
    location('45225','Micanopy','Incorporated Place','A','Alachua County');
    location('45275','Micco','Census Designated Place','S','Brevard County');
    location('45350','Middleburg','Census Designated Place','S','Clay County');
    location('45425','Midway','Incorporated Place','A','Gadsden County');
    location('45465','Midway','Census Designated Place','S','Santa Rosa County');
    location('45475','Midway','Census Designated Place','S','Seminole County');
    location('45750','Milton','Incorporated Place','A','Santa Rosa County');
    location('45775','Mims','Census Designated Place','S','Brevard County');
    location('45900','Minneola','Incorporated Place','A','Lake County');
    location('45975','Miramar','Incorporated Place','A','Broward County');
    location('46000','Miramar Beach','Census Designated Place','S','Walton County');
    location('46225','Molino','Census Designated Place','S','Escambia County');
    location('46500','Monticello','Incorporated Place','A','Jefferson County');
    location('46520','Montura','Census Designated Place','S','Hendry County');
    location('46525','Montverde','Incorporated Place','A','Lake County');
    location('46540','Moon Lake','Census Designated Place','S','Pasco County');
    location('46550','Moore Haven','Incorporated Place','A','Glades County');
    location('46725','Morriston','Census Designated Place','S','Levy County');
    location('47000','Mount Carmel','Census Designated Place','S','Santa Rosa County');
    location('47050','Mount Dora','Incorporated Place','A','Lake County');
    location('47125','Mount Plymouth','Census Designated Place','S','Lake County');
    location('47175','Mulat','Census Designated Place','S','Santa Rosa County');
    location('47200','Mulberry','Incorporated Place','A','Polk County');
    location('47300','Munson','Census Designated Place','S','Santa Rosa County');
    location('47550','Myrtle Grove','Census Designated Place','S','Escambia County');
    location('47625','Naples','Incorporated Place','A','Collier County');
    location('47650','Naples Manor','Census Designated Place','S','Collier County');
    location('47675','Naples Park','Census Designated Place','S','Collier County');
    location('47700','Naranja','Census Designated Place','S','Miami-Dade County');
    location('47787','Nassau Village-Ratliff','Census Designated Place','S','Nassau County');
    location('48050','Navarre','Census Designated Place','S','Santa Rosa County');
    location('48055','Navarre Beach','Census Designated Place','S','Santa Rosa County');
    location('48100','Neptune Beach','Incorporated Place','A','Duval County');
    location('48200','Newberry','Incorporated Place','A','Alachua County');
    location('48500','New Port Richey','Incorporated Place','A','Pasco County');
    location('48525','New Port Richey East','Census Designated Place','S','Pasco County');
    location('48625','New Smyrna Beach','Incorporated Place','A','Volusia County');
    location('48750','Niceville','Incorporated Place','A','Okaloosa County');
    location('48825','Nobleton','Census Designated Place','S','Hernando County');
    location('48850','Nocatee','Census Designated Place','S','St. Johns County');
    location('48875','Nokomis','Census Designated Place','S','Sarasota County');
    location('48900','Noma','Incorporated Place','A','Holmes County');
    location('49225','North Bay Village','Incorporated Place','A','Miami-Dade County');
    location('49237','North Brooksville','Census Designated Place','S','Hernando County');
    location('49260','Northdale','Census Designated Place','S','Hillsborough County');
    location('49275','North DeLand','Census Designated Place','S','Volusia County');
    location('49350','North Fort Myers','Census Designated Place','S','Lee County');
    location('49406','North Key Largo','Census Designated Place','S','Monroe County');
    location('49425','North Lauderdale','Incorporated Place','A','Broward County');
    location('49450','North Miami','Incorporated Place','A','Miami-Dade County');
    location('49475','North Miami Beach','Incorporated Place','A','Miami-Dade County');
    location('49600','North Palm Beach','Incorporated Place','A','Palm Beach County');
    location('49675','North Port','Incorporated Place','A','Sarasota County');
    location('49725','North Redington Beach','Incorporated Place','A','Pinellas County');
    location('49750','North River Shores','Census Designated Place','S','Martin County');
    location('49787','North Sarasota','Census Designated Place','S','Sarasota County');
    location('49905','North Weeki Wachee','Census Designated Place','S','Hernando County');
    location('50450','Oak Hill','Incorporated Place','A','Volusia County');
    location('50525','Oakland','Incorporated Place','A','Orange County');
    location('50575','Oakland Park','Incorporated Place','A','Broward County');
    location('50630','Oakleaf Plantation','Census Designated Place','S','Clay County');
    location('50638','Oak Ridge','Census Designated Place','S','Orange County');
    location('50750','Ocala','Incorporated Place','A','Marion County');
    location('50900','Ocean Breeze Park','Incorporated Place','A','Martin County');
    location('50925','Ocean City','Census Designated Place','S','Okaloosa County');
    location('50950','Ocean Ridge','Incorporated Place','A','Palm Beach County');
    location('51075','Ocoee','Incorporated Place','A','Orange County');
    location('51100','Odessa','Census Designated Place','S','Pasco County');
    location('51125','Ojus','Census Designated Place','S','Miami-Dade County');
    location('51150','Okahumpka','Census Designated Place','S','Lake County');
    location('51200','Okeechobee','Incorporated Place','A','Okeechobee County');
    location('51350','Oldsmar','Incorporated Place','A','Pinellas County');
    location('51400','Olga','Census Designated Place','S','Lee County');
    location('51475','Olympia Heights','Census Designated Place','S','Miami-Dade County');
    location('51505','Ona','Census Designated Place','S','Hardee County');
    location('51650','Opa-locka','Incorporated Place','A','Miami-Dade County');
    location('51825','Orange City','Incorporated Place','A','Volusia County');
    location('52125','Orange Park','Incorporated Place','A','Clay County');
    location('52162','Orangetree','Census Designated Place','S','Collier County');
    location('52175','Orchid','Incorporated Place','A','Indian River County');
    location('52250','Oriole Beach','Census Designated Place','S','Santa Rosa County');
    location('53000','Orlando','Incorporated Place','A','Orange County');
    location('53100','Orlovista','Census Designated Place','S','Orange County');
    location('53150','Ormond Beach','Incorporated Place','A','Volusia County');
    location('53200','Ormond-by-the-Sea','Census Designated Place','S','Volusia County');
    location('53425','Osprey','Census Designated Place','S','Sarasota County');
    location('53500','Otter Creek','Incorporated Place','A','Levy County');
    location('53575','Oviedo','Incorporated Place','A','Seminole County');
    location('53725','Pace','Census Designated Place','S','Santa Rosa County');
    location('53775','Page Park','Census Designated Place','S','Lee County');
    location('53800','Pahokee','Incorporated Place','A','Palm Beach County');
    location('53850','Paisley','Census Designated Place','S','Lake County');
    location('53875','Palatka','Incorporated Place','A','Putnam County');
    location('54000','Palm Bay','Incorporated Place','A','Brevard County');
    location('54025','Palm Beach','Incorporated Place','A','Palm Beach County');
    location('54075','Palm Beach Gardens','Incorporated Place','A','Palm Beach County');
    location('54150','Palm Beach Shores','Incorporated Place','A','Palm Beach County');
    location('54175','Palm City','Census Designated Place','S','Martin County');
    location('54200','Palm Coast','Incorporated Place','A','Flagler County');
    location('54250','Palmetto','Incorporated Place','A','Manatee County');
    location('54275','Palmetto Bay village','Incorporated Place','A','Miami-Dade County');
    location('54300','Palmetto Estates','Census Designated Place','S','Miami-Dade County');
    location('54350','Palm Harbor','Census Designated Place','S','Pinellas County');
    location('54357','Palmona Park','Census Designated Place','S','Lee County');
    location('54387','Palm River-Clair Mel','Census Designated Place','S','Hillsborough County');
    location('54425','Palm Shores','Incorporated Place','A','Brevard County');
    location('54450','Palm Springs village','Incorporated Place','A','Palm Beach County');
    location('54500','Palm Springs North','Census Designated Place','S','Miami-Dade County');
    location('54525','Palm Valley','Census Designated Place','S','St. Johns County');
    location('54625','Panacea','Census Designated Place','S','Wakulla County');
    location('54700','Panama City','Incorporated Place','A','Bay County');
    location('54725','Panama City Beach','Incorporated Place','A','Bay County');
    location('54912','Paradise Heights','Census Designated Place','S','Orange County');
    location('55075','Parker','Incorporated Place','A','Bay County');
    location('55125','Parkland','Incorporated Place','A','Broward County');
    location('55305','Pasadena Hills','Census Designated Place','S','Pasco County');
    location('55375','Patrick AFB','Census Designated Place','S','Brevard County');
    location('55475','Paxton','Incorporated Place','A','Walton County');
    location('55532','Pea Ridge','Census Designated Place','S','Santa Rosa County');
    location('55540','Pebble Creek','Census Designated Place','S','Hillsborough County');
    location('55650','Pelican Bay','Census Designated Place','S','Collier County');
    location('55750','Pembroke Park','Incorporated Place','A','Broward County');
    location('55775','Pembroke Pines','Incorporated Place','A','Broward County');
    location('55875','Penney Farms','Incorporated Place','A','Clay County');
    location('55925','Pensacola','Incorporated Place','A','Escambia County');
    location('56150','Perry','Incorporated Place','A','Taylor County');
    location('56425','Pierson','Incorporated Place','A','Volusia County');
    location('56475','Pine Air','Census Designated Place','S','Palm Beach County');
    location('56500','Pine Castle','Census Designated Place','S','Orange County');
    location('56625','Pinecrest village','Incorporated Place','A','Miami-Dade County');
    location('56825','Pine Hills','Census Designated Place','S','Orange County');
    location('56840','Pine Island','Census Designated Place','S','Hernando County');
    location('56850','Pine Island Center','Census Designated Place','S','Lee County');
    location('56865','Pine Lakes','Census Designated Place','S','Lake County');
    location('56875','Pineland','Census Designated Place','S','Lee County');
    location('56955','Pine Level','Census Designated Place','S','Santa Rosa County');
    location('56975','Pinellas Park','Incorporated Place','A','Pinellas County');
    location('57025','Pine Manor','Census Designated Place','S','Lee County');
    location('57058','Pine Ridge','Census Designated Place','S','Citrus County');
    location('57066','Pine Ridge','Census Designated Place','S','Collier County');
    location('57250','Pinewood','Census Designated Place','S','Miami-Dade County');
    location('57320','Pioneer','Census Designated Place','S','Hendry County');
    location('57380','Pittman','Census Designated Place','S','Lake County');
    location('57425','Plantation','Incorporated Place','A','Broward County');
    location('57450','Plantation','Census Designated Place','S','Sarasota County');
    location('57492','Plantation Island','Census Designated Place','S','Collier County');
    location('57518','Plantation Mobile Home Park','Census Designated Place','S','Palm Beach County');
    location('57550','Plant City','Incorporated Place','A','Hillsborough County');
    location('57900','Poinciana','Census Designated Place','S','Osceola County, Polk County');
    location('57908','Point Baker','Census Designated Place','S','Santa Rosa County');
    location('57950','Polk City','Incorporated Place','A','Polk County');
    location('58025','Pomona Park','Incorporated Place','A','Putnam County');
    location('58050','Pompano Beach','Incorporated Place','A','Broward County');
    location('58175','Ponce de Leon','Incorporated Place','A','Holmes County');
    location('58200','Ponce Inlet','Incorporated Place','A','Volusia County');
    location('58350','Port Charlotte','Census Designated Place','S','Charlotte County');
    location('58420','Port LaBelle','Census Designated Place','S','Hendry County');
    location('58575','Port Orange','Incorporated Place','A','Volusia County');
    location('58600','Port Richey','Incorporated Place','A','Pasco County');
    location('58675','Port Saint Joe','Incorporated Place','A','Gulf County');
    location('58700','Port St. John','Census Designated Place','S','Brevard County');
    location('58715','Port Saint Lucie','Incorporated Place','A','St. Lucie County');
    location('58727','Port Salerno','Census Designated Place','S','Martin County');
    location('58962','Pretty Bayou','Census Designated Place','S','Bay County');
    location('58975','Princeton','Census Designated Place','S','Miami-Dade County');
    location('59050','Progress Village','Census Designated Place','S','Hillsborough County');
    location('59200','Punta Gorda','Incorporated Place','A','Charlotte County');
    location('59250','Punta Rassa','Census Designated Place','S','Lee County');
    location('59311','Quail Ridge','Census Designated Place','S','Pasco County');
    location('59325','Quincy','Incorporated Place','A','Gadsden County');
    location('59400','Raiford','Incorporated Place','A','Union County');
    location('59475','Raleigh','Census Designated Place','S','Levy County');
    location('59675','Reddick','Incorporated Place','A','Marion County');
    location('59725','Redington Beach','Incorporated Place','A','Pinellas County');
    location('59750','Redington Shores','Incorporated Place','A','Pinellas County');
    location('60225','Richmond Heights','Census Designated Place','S','Miami-Dade County');
    location('60230','Richmond West','Census Designated Place','S','Miami-Dade County');
    location('60275','Ridgecrest','Census Designated Place','S','Pinellas County');
    location('60325','Ridge Manor','Census Designated Place','S','Hernando County');
    location('60475','Ridge Wood Heights','Census Designated Place','S','Sarasota County');
    location('60550','Rio','Census Designated Place','S','Martin County');
    location('60562','Rio Pinar','Census Designated Place','S','Orange County');
    location('60785','River Park','Census Designated Place','S','St. Lucie County');
    location('60835','River Ridge','Census Designated Place','S','Pasco County');
    location('60950','Riverview','Census Designated Place','S','Hillsborough County');
    location('60975','Riviera Beach','Incorporated Place','A','Palm Beach County');
    location('61500','Rockledge','Incorporated Place','A','Brevard County');
    location('61615','Roeville','Census Designated Place','S','Santa Rosa County');
    location('61807','Roosevelt Gardens','Census Designated Place','S','Broward County');
    location('61875','Roseland','Census Designated Place','S','Indian River County');
    location('61937','Rotonda','Census Designated Place','S','Charlotte County');
    location('62100','Royal Palm Beach village','Incorporated Place','A','Palm Beach County');
    location('62118','Royal Palm Estates','Census Designated Place','S','Palm Beach County');
    location('62275','Ruskin','Census Designated Place','S','Hillsborough County');
    location('62425','Safety Harbor','Incorporated Place','A','Pinellas County');
    location('62500','Saint Augustine','Incorporated Place','A','St. Johns County');
    location('62525','St. Augustine Beach','Incorporated Place','A','St. Johns County');
    location('62550','St. Augustine Shores','Census Designated Place','S','St. Johns County');
    location('62562','St. Augustine South','Census Designated Place','S','St. Johns County');
    location('62625','Saint Cloud','Incorporated Place','A','Osceola County');
    location('62675','Saint James City','Census Designated Place','S','Lee County');
    location('62775','Saint Leo','Incorporated Place','A','Pasco County');
    location('62800','St. Lucie Village','Incorporated Place','A','St. Lucie County');
    location('62825','Saint Marks','Incorporated Place','A','Wakulla County');
    location('62885','St. Pete Beach','Incorporated Place','A','Pinellas County');
    location('63000','Saint Petersburg','Incorporated Place','A','Pinellas County');
    location('63225','Samoset','Census Designated Place','S','Manatee County');
    location('63362','Samsula-Spruce Creek','Census Designated Place','S','Volusia County');
    location('63375','San Antonio','Incorporated Place','A','Pasco County');
    location('63425','San Carlos Park','Census Designated Place','S','Lee County');
    location('63435','San Castle','Census Designated Place','S','Palm Beach County');
    location('63650','Sanford','Incorporated Place','A','Seminole County');
    location('63700','Sanibel','Incorporated Place','A','Lee County');
    location('64175','Sarasota','Incorporated Place','A','Sarasota County');
    location('64325','Sarasota Springs','Census Designated Place','S','Sarasota County');
    location('64400','Satellite Beach','Incorporated Place','A','Brevard County');
    location('64525','Sawgrass','Census Designated Place','S','St. Johns County');
    location('64547','Schall Circle','Census Designated Place','S','Palm Beach County');
    location('64725','Sea Ranch Lakes village','Incorporated Place','A','Broward County');
    location('64825','Sebastian','Incorporated Place','A','Indian River County');
    location('64875','Sebring','Incorporated Place','A','Highlands County');
    location('64925','Seffner','Census Designated Place','S','Hillsborough County');
    location('64975','Seminole','Incorporated Place','A','Pinellas County');
    location('65100','Seminole Manor','Census Designated Place','S','Palm Beach County');
    location('65200','Seville','Census Designated Place','S','Volusia County');
    location('65225','Sewall''s Point','Incorporated Place','A','Martin County');
    location('65385','Shady Hills','Census Designated Place','S','Pasco County');
    location('65425','Shalimar','Incorporated Place','A','Okaloosa County');
    location('65525','Sharpes','Census Designated Place','S','Brevard County');
    location('66000','Siesta Key','Census Designated Place','S','Sarasota County');
    location('66062','Silver Lake','Census Designated Place','S','Lake County');
    location('66175','Silver Springs','Census Designated Place','S','Marion County');
    location('66425','Sky Lake','Census Designated Place','S','Orange County');
    location('66725','Sneads','Incorporated Place','A','Jackson County');
    location('66875','Solana','Census Designated Place','S','Charlotte County');
    location('66925','Sopchoppy','Incorporated Place','A','Wakulla County');
    location('66975','Sorrento','Census Designated Place','S','Lake County');
    location('67163','South Apopka','Census Designated Place','S','Orange County');
    location('67175','South Bay','Incorporated Place','A','Palm Beach County');
    location('67192','South Beach','Census Designated Place','S','Indian River County');
    location('67258','South Bradenton','Census Designated Place','S','Manatee County');
    location('67266','South Brooksville','Census Designated Place','S','Hernando County');
    location('67270','Southchase','Census Designated Place','S','Orange County');
    location('67325','South Daytona','Incorporated Place','A','Volusia County');
    location('67355','Southeast Arcadia','Census Designated Place','S','DeSoto County');
    location('67425','Southgate','Census Designated Place','S','Sarasota County');
    location('67450','South Gate Ridge','Census Designated Place','S','Sarasota County');
    location('67462','South Highpoint','Census Designated Place','S','Pinellas County');
    location('67550','South Miami','Incorporated Place','A','Miami-Dade County');
    location('67575','South Miami Heights','Census Designated Place','S','Miami-Dade County');
    location('67650','South Palm Beach','Incorporated Place','A','Palm Beach County');
    location('67675','South Pasadena','Incorporated Place','A','Pinellas County');
    location('67725','South Patrick Shores','Census Designated Place','S','Brevard County');
    location('67887','South Sarasota','Census Designated Place','S','Sarasota County');
    location('68100','South Venice','Census Designated Place','S','Sarasota County');
    location('68135','Southwest Ranches','Incorporated Place','A','Broward County');
    location('68275','Springfield','Incorporated Place','A','Bay County');
    location('68350','Spring Hill','Census Designated Place','S','Hernando County');
    location('68365','Springhill','Census Designated Place','S','Santa Rosa County');
    location('68375','Spring Lake','Census Designated Place','S','Hernando County');
    location('68435','Spring Ridge','Census Designated Place','S','Gilchrist County');
    location('68487','Stacey Street','Census Designated Place','S','Palm Beach County');
    location('68525','Starke','Incorporated Place','A','Bradford County');
    location('68625','Steinhatchee','Census Designated Place','S','Taylor County');
    location('68800','Stock Island','Census Designated Place','S','Monroe County');
    location('68875','Stuart','Incorporated Place','A','Martin County');
    location('68950','Sugarmill Woods','Census Designated Place','S','Citrus County');
    location('69025','Sumatra','Census Designated Place','S','Liberty County');
    location('69250','Sun City Center','Census Designated Place','S','Hillsborough County');
    location('69275','Suncoast Estates','Census Designated Place','S','Lee County');
    location('69555','Sunny Isles Beach','Incorporated Place','A','Miami-Dade County');
    location('69700','Sunrise','Incorporated Place','A','Broward County');
    location('69812','Sunset','Census Designated Place','S','Miami-Dade County');
    location('70075','Surfside','Incorporated Place','A','Miami-Dade County');
    location('70345','Sweetwater','Incorporated Place','A','Miami-Dade County');
    location('70525','Taft','Census Designated Place','S','Orange County');
    location('70600','Tallahassee','Incorporated Place','A','Leon County');
    location('70675','Tamarac','Incorporated Place','A','Broward County');
    location('70700','Tamiami','Census Designated Place','S','Miami-Dade County');
    location('71000','Tampa','Incorporated Place','A','Hillsborough County');
    location('71075','Tangelo Park','Census Designated Place','S','Orange County');
    location('71100','Tangerine','Census Designated Place','S','Orange County');
    location('71150','Tarpon Springs','Incorporated Place','A','Pinellas County');
    location('71225','Tavares','Incorporated Place','A','Lake County');
    location('71250','Tavernier','Census Designated Place','S','Monroe County');
    location('71300','Taylor Creek','Census Designated Place','S','Okeechobee County');
    location('71400','Temple Terrace','Incorporated Place','A','Hillsborough County');
    location('71525','Tequesta','Incorporated Place','A','Palm Beach County');
    location('71564','The Acreage','Census Designated Place','S','Palm Beach County');
    location('71567','The Crossings','Census Designated Place','S','Miami-Dade County');
    location('71569','The Hammocks','Census Designated Place','S','Miami-Dade County');
    location('71580','The Meadows','Census Designated Place','S','Sarasota County');
    location('71625','The Villages','Census Designated Place','S','Marion County, Sumter County');
    location('71725','Thonotosassa','Census Designated Place','S','Hillsborough County');
    location('71741','Three Lakes','Census Designated Place','S','Miami-Dade County');
    location('71758','Three Oaks','Census Designated Place','S','Lee County');
    location('71800','Tice','Census Designated Place','S','Lee County');
    location('71825','Tierra Verde','Census Designated Place','S','Pinellas County');
    location('71842','Tiger Point','Census Designated Place','S','Santa Rosa County');
    location('71850','Tildenville','Census Designated Place','S','Orange County');
    location('71867','Timber Pines','Census Designated Place','S','Hernando County');
    location('71900','Titusville','Incorporated Place','A','Brevard County');
    location('72145','Town n Country','Census Designated Place','S','Hillsborough County');
    location('72325','Treasure Island','Incorporated Place','A','Pinellas County');
    location('72350','Trenton','Incorporated Place','A','Gilchrist County');
    location('72425','Trilby','Census Designated Place','S','Pasco County');
    location('72442','Trinity','Census Designated Place','S','Pasco County');
    location('72875','Tyndall AFB','Census Designated Place','S','Bay County');
    location('73025','Umatilla','Incorporated Place','A','Lake County');
    location('73075','Union Park','Census Designated Place','S','Orange County');
    location('73163','University','Census Designated Place','S','Hillsborough County');
    location('73172','University','Census Designated Place','S','Orange County');
    location('73287','University Park','Census Designated Place','S','Miami-Dade County');
    location('73312','Upper Grand Lagoon','Census Designated Place','S','Bay County');
    location('73675','Valparaiso','Incorporated Place','A','Okaloosa County');
    location('73700','Valrico','Census Designated Place','S','Hillsborough County');
    location('73725','Vamo','Census Designated Place','S','Sarasota County');
    location('73900','Venice','Incorporated Place','A','Sarasota County');
    location('73950','Venice Gardens','Census Designated Place','S','Sarasota County');
    location('74125','Vernon','Incorporated Place','A','Washington County');
    location('74150','Vero Beach','Incorporated Place','A','Indian River County');
    location('74200','Vero Beach South','Census Designated Place','S','Indian River County');
    location('74235','Verona Walk','Census Designated Place','S','Collier County');
    location('74368','Viera East','Census Designated Place','S','Brevard County');
    location('74370','Viera West','Census Designated Place','S','Brevard County');
    location('74498','Villano Beach','Census Designated Place','S','St. Johns County');
    location('74512','Villas','Census Designated Place','S','Lee County');
    location('74562','Vineyards','Census Designated Place','S','Collier County');
    location('74575','Virginia Gardens village','Incorporated Place','A','Miami-Dade County');
    location('74625','Wabasso','Census Designated Place','S','Indian River County');
    location('74635','Wabasso Beach','Census Designated Place','S','Indian River County');
    location('74700','Wacissa','Census Designated Place','S','Jefferson County');
    location('74775','Wahneta','Census Designated Place','S','Polk County');
    location('74925','Waldo','Incorporated Place','A','Alachua County');
    location('74975','Wallace','Census Designated Place','S','Santa Rosa County');
    location('75175','Warm Mineral Springs','Census Designated Place','S','Sarasota County');
    location('75200','Warrington','Census Designated Place','S','Escambia County');
    location('75225','Washington Park','Census Designated Place','S','Broward County');
    location('75275','Watergate','Census Designated Place','S','Palm Beach County');
    location('75300','Watertown','Census Designated Place','S','Columbia County');
    location('75375','Wauchula','Incorporated Place','A','Hardee County');
    location('75425','Waukeenah','Census Designated Place','S','Jefferson County');
    location('75450','Wausau','Incorporated Place','A','Washington County');
    location('75475','Waverly','Census Designated Place','S','Polk County');
    location('75600','Webster','Incorporated Place','A','Sumter County');
    location('75612','Wedgefield','Census Designated Place','S','Orange County');
    location('75625','Weeki Wachee','Incorporated Place','A','Hernando County');
    location('75641','Weeki Wachee Gardens','Census Designated Place','S','Hernando County');
    location('75725','Wekiwa Springs','Census Designated Place','S','Seminole County');
    location('75750','Welaka','Incorporated Place','A','Putnam County');
    location('75812','Wellington village','Incorporated Place','A','Palm Beach County');
    location('75875','Wesley Chapel','Census Designated Place','S','Pasco County');
    location('76050','West Bradenton','Census Designated Place','S','Manatee County');
    location('76062','Westchase','Census Designated Place','S','Hillsborough County');
    location('76075','Westchester','Census Designated Place','S','Miami-Dade County');
    location('76087','West DeLand','Census Designated Place','S','Volusia County');
    location('76290','Westgate','Census Designated Place','S','Palm Beach County');
    location('76481','West Lealman','Census Designated Place','S','Pinellas County');
    location('76487','West Little River','Census Designated Place','S','Miami-Dade County');
    location('76500','West Melbourne','Incorporated Place','A','Brevard County');
    location('76525','West Miami','Incorporated Place','A','Miami-Dade County');
    location('76582','Weston','Incorporated Place','A','Broward County');
    location('76600','West Palm Beach','Incorporated Place','A','Palm Beach County');
    location('76658','West Park','Incorporated Place','A','Broward County');
    location('76675','West Pensacola','Census Designated Place','S','Escambia County');
    location('76700','West Perrine','Census Designated Place','S','Miami-Dade County');
    location('76740','West Samoset','Census Designated Place','S','Manatee County');
    location('76937','West Vero Corridor','Census Designated Place','S','Indian River County');
    location('76950','Westview','Census Designated Place','S','Miami-Dade County');
    location('76975','Westville','Incorporated Place','A','Holmes County');
    location('77075','Westwood Lakes','Census Designated Place','S','Miami-Dade County');
    location('77100','Wewahitchka','Incorporated Place','A','Gulf County');
    location('77137','Whiskey Creek','Census Designated Place','S','Lee County');
    location('77275','White City','Census Designated Place','S','St. Lucie County');
    location('77400','White Springs','Incorporated Place','A','Hamilton County');
    location('77467','Whitfield','Census Designated Place','S','Manatee County');
    location('77470','Whitfield','Census Designated Place','S','Santa Rosa County');
    location('77675','Wildwood','Incorporated Place','A','Sumter County');
    location('77735','Williamsburg','Census Designated Place','S','Orange County');
    location('77825','Williston','Incorporated Place','A','Levy County');
    location('77837','Williston Highlands','Census Designated Place','S','Levy County');
    location('77862','Willow Oak','Census Designated Place','S','Polk County');
    location('78000','Wilton Manors','Incorporated Place','A','Broward County');
    location('78025','Wimauma','Census Designated Place','S','Hillsborough County');
    location('78050','Windermere','Incorporated Place','A','Orange County');
    location('78110','Windsor','Census Designated Place','S','Indian River County');
    location('78225','Winter Beach','Census Designated Place','S','Indian River County');
    location('78250','Winter Garden','Incorporated Place','A','Orange County');
    location('78275','Winter Haven','Incorporated Place','A','Polk County');
    location('78300','Winter Park','Incorporated Place','A','Orange County');
    location('78325','Winter Springs','Incorporated Place','A','Seminole County');
    location('78340','Wiscon','Census Designated Place','S','Hernando County');
    location('78500','Woodlawn Beach','Census Designated Place','S','Santa Rosa County');
    location('78700','Woodville','Census Designated Place','S','Leon County');
    location('78740','World Golf Village','Census Designated Place','S','St. Johns County');
    location('78775','Worthington Springs','Incorporated Place','A','Union County');
    location('78800','Wright','Census Designated Place','S','Okaloosa County');
    location('78900','Yalaha','Census Designated Place','S','Lake County');
    location('78925','Yankeetown','Incorporated Place','A','Levy County');
    location('78975','Yeehaw Junction','Census Designated Place','S','Osceola County');
    location('79175','Yulee','Census Designated Place','S','Nassau County');
    location('79200','Zellwood','Census Designated Place','S','Orange County');
    location('79225','Zephyrhills','Incorporated Place','A','Pasco County');
    location('79231','Zephyrhills North','Census Designated Place','S','Pasco County');
    location('79237','Zephyrhills South','Census Designated Place','S','Pasco County');
    location('79243','Zephyrhills West','Census Designated Place','S','Pasco County');
    location('79250','Zolfo Springs','Incorporated Place','A','Hardee County');
  end seed_locations;

  procedure seed_population is
  begin
    update rnt_cities c
    set population = nvl(
      (select pop100
       from census2010profile cp
       where c.census_place = cp.place), population);

    update rnt_cities
    set pop_source = '2010 Census'
    where population is not null;
  end seed_population;
  
  
begin
  seed_locations;
  seed_population;
end;
/