CREATE OR REPLACE VIEW RNT_EXPENSE_ITEMS_V
(EXPENSE_ID, SUPPLIER_ID, ITEM_NAME, ITEM_COST, ESTIMATE, 
 ACTUAL, EXPENSE_ITEM_ID, ORDER_ROW, ITEM_UNIT, CHECKSUM, 
 SUPPLIER_NAME)
AS 
select ei.EXPENSE_ID
,      ei.SUPPLIER_ID
,      ei.ITEM_NAME
,      ei.ITEM_COST
,      ei.ESTIMATE
,      ei.ACTUAL
,      ei.EXPENSE_ITEM_ID
,      ei.ORDER_ROW
,      ei.ITEM_UNIT
,      rnt_sys_checksum_rec_pkg.get_checksum('EXPENSE_ID='||ei.EXPENSE_ID||'SUPPLIER_ID='||ei.SUPPLIER_ID||'ITEM_NAME='||ei.ITEM_NAME||'ITEM_COST='||ei.ITEM_COST||'ESTIMATE='||ei.ESTIMATE||'ACTUAL='||ei.ACTUAL||'EXPENSE_ITEM_ID='||ei.EXPENSE_ITEM_ID||'ORDER_ROW='||ei.ORDER_ROW||'ITEM_UNIT='||ei.ITEM_UNIT) as CHECKSUM
,      s.NAME as SUPPLIER_NAME
from RNT_EXPENSE_ITEMS ei,
     RNT_SUPPLIERS_ALL s
where ei.SUPPLIER_ID = s.SUPPLIER_ID
/

