ALTER TABLE RNTMGR.RNT_TENANCY_AGREEMENT MODIFY(TERM NUMBER);


ALTER TABLE RNTMGR.RNT_TENANCY_AGREEMENT DROP COLUMN NOTM;

ALTER TABLE RNTMGR.RNT_TENANCY DROP COLUMN NOTM;

ALTER TABLE RNTMGR.RNT_LOANS DROP COLUMN NOTM;