CREATE OR REPLACE VIEW RNT_PROPERTY_UNITS_V
(UNIT_ID, PROPERTY_ID, UNIT_NAME, UNIT_SIZE, BEDROOMS, 
 BATHROOMS, CHECKSUM)
AS 
select UNIT_ID, 
       PROPERTY_ID, 
       UNIT_NAME, UNIT_SIZE, BEDROOMS, 
       BATHROOMS,
       RNT_PROPERTY_UNITS_PKG.GET_CHECKSUM(UNIT_ID) as CHECKSUM
from RNT_PROPERTY_UNITS
order by UNIT_NAME
/


