VALUE="AK  ">Alaska<OPTION							
VALUE="AL  ">Alabama<OPTION						
VALUE="AR  ">Arkansas<OPTION							
VALUE="AZ  ">Arizona<OPTION							
VALUE="CA  ">California<OPTION							
VALUE="CO  ">Colorado<OPTION							
VALUE="CT  ">Connecticut<OPTION							
VALUE="DC  ">District Of Columbia<OPTION							
VALUE="DE  ">Delaware<OPTION							
VALUE="FL  ">Florida<OPTION							
VALUE="GA  ">Georgia<OPTION							
VALUE="HI  ">Hawaii<OPTION							
VALUE="IA  ">Iowa<OPTION							
VALUE="ID  ">Idaho<OPTION							
VALUE="IL  ">Illinois<OPTION							
VALUE="IN  ">Indiana<OPTION							
VALUE="KS  ">Kansas<OPTION							
VALUE="KY  ">Kentucky<OPTION							
VALUE="LA  ">Louisiana<OPTION							
VALUE="MA  ">Massachusetts<OPTION							
VALUE="MD  ">Maryland<OPTION							
VALUE="ME  ">Maine<OPTION
VALUE="MI  ">Michigan<OPTION							
VALUE="MN  ">Minnesota<OPTION
VALUE="MO  ">Missouri<OPTION							
VALUE="MS  ">Mississippi<OPTION							
VALUE="MT  ">Montana<OPTION							
VALUE="NC  ">North Carolina<OPTION							
VALUE="ND  ">North Dakota<OPTION							
VALUE="NE  ">Nebraska<OPTION							
VALUE="NH  ">New Hampshire<OPTION							
VALUE="NJ  ">New Jersey<OPTION							
VALUE="NM  ">New Mexico<OPTION							VALUE="NV  ">Nevada<OPTION							
VALUE="NY  ">New York<OPTION							
VALUE="OH  ">Ohio<OPTION							
VALUE="OK  ">Oklahoma<OPTION							

VALUE="OR  ">Oregon<OPTION							
VALUE="PA  ">Pennsylvania<OPTION							
VALUE="RI  ">Rhode Island<OPTION							
VALUE="SC  ">South Carolina<OPTION
VALUE="SD  ">South Dakota<OPTION							
VALUE="TN  ">Tennessee<OPTION							
VALUE="TX  ">Texas<OPTION							
VALUE="UT  ">Utah<OPTION							
VALUE="VA  ">Virginia<OPTION							
VALUE="VT  ">Vermont<OPTION							
VALUE="WA  ">Washington<OPTION							
VALUE="WI  ">Wisconsin<OPTION							
VALUE="WV  ">West Virginia<OPTION							
VALUE="WY  ">Wyoming<OPTION