ALTER TABLE RNT_PAYMENT_TYPES ADD NOI_YN VARCHAR2(1) NULL;

COMMENT ON COLUMN RNT_PAYMENT_TYPES.NOI_YN IS 'Y if included in NOI';

update RNT_PAYMENT_TYPES
set NOI_YN = 'Y';

update RNT_PAYMENT_TYPES
set NOI_YN = 'N'
where PAYMENT_TYPE_ID in (12, 27);

commit;

ALTER TABLE RNT_PAYMENT_TYPES MODIFY NOI_YN VARCHAR2(1) NOT NULL;
