CREATE OR REPLACE VIEW RNT_SUPPLIERS_V
(SUPPLIER_ID, NAME, PHONE1, PHONE2, ADDRESS1, 
 ADDRESS2, CITY, STATE, ZIPCODE, EMAIL_ADDRESS, 
 COMMENTS, SUPPLIER_TYPE_ID, BU_SUPPLIER_ID, BUSINESS_ID, TAX_IDENTIFIER, 
 NOTES, SUPPLIER_TYPE_NAME, STATE_NAME)
AS 
select 
   s.SUPPLIER_ID, s.NAME, s.PHONE1, 
   s.PHONE2, s.ADDRESS1, s.ADDRESS2, 
   s.CITY, s.STATE, s.ZIPCODE, 
   s.EMAIL_ADDRESS, s.COMMENTS, s.SUPPLIER_TYPE_ID,
   bs.BU_SUPPLIER_ID, 
   bs.BUSINESS_ID, 
   bs.TAX_IDENTIFIER, 
   bs.NOTES,
   st.SUPPLIER_TYPE_NAME,
   lv.LOOKUP_VALUE as STATE_NAME
from RNT_SUPPLIERS_ALL s,
     RNT_BU_SUPPLIERS bs,
     RNT_SUPPLIER_TYPES st,
     RNT_LOOKUP_VALUES_V lv
where st.SUPPLIER_TYPE_ID = s.SUPPLIER_TYPE_ID
  and bs.SUPPLIER_ID = s.SUPPLIER_ID
  and lv.LOOKUP_TYPE_CODE = 'STATES'
  and lv.LOOKUP_CODE = s.STATE
/

