CREATE SEQUENCE RNT_PEOPLE_BU_SEQ
  START WITH 81
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

CREATE SEQUENCE RNT_SECTION8_OFFICES_BU_SEQ
  START WITH 33
  MAXVALUE 999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;

CREATE TABLE RNT_SECTION8_OFFICES_BU
(
  SECTION8_BUSINESS_ID  NUMBER                  NOT NULL,
  SECTION8_ID           NUMBER                  NOT NULL,
  BUSINESS_ID           NUMBER                  NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX RNT_SECTION8_OFFICES_BU_U1 ON RNT_SECTION8_OFFICES_BU
(SECTION8_ID, BUSINESS_ID)
LOGGING
NOPARALLEL;

CREATE UNIQUE INDEX RNT_SECTION8_OFFICES_BU_PK ON RNT_SECTION8_OFFICES_BU
(SECTION8_BUSINESS_ID)
LOGGING
NOPARALLEL;

ALTER TABLE RNT_SECTION8_OFFICES_BU
 ADD CONSTRAINT RNT_SECTION8_OFFICES_BU_PK
 PRIMARY KEY
 (SECTION8_BUSINESS_ID);

CREATE TABLE RNT_PEOPLE_BU
(
  PEOPLE_BUSINESS_ID  NUMBER                    NOT NULL,
  PEOPLE_ID           NUMBER                    NOT NULL,
  BUSINESS_ID         NUMBER                    NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE RNT_PEOPLE_BU IS 'People with business units.';

CREATE UNIQUE INDEX RNT_PEOPLE_BU_U1 ON RNT_PEOPLE_BU
(PEOPLE_ID, BUSINESS_ID)
LOGGING
NOPARALLEL;

CREATE UNIQUE INDEX RNT_PEOPLE_BU_PK ON RNT_PEOPLE_BU
(PEOPLE_BUSINESS_ID)
LOGGING
NOPARALLEL;

ALTER TABLE RNT_PEOPLE_BU
 ADD CONSTRAINT RNT_PEOPLE_BU_PK
 PRIMARY KEY
 (PEOPLE_BUSINESS_ID);

CREATE UNIQUE INDEX RNT_SECTION8_OFFICES_U1 ON RNT_SECTION8_OFFICES
(SECTION_NAME)
LOGGING
NOPARALLEL;
