insert into RNT_PEOPLE_BU (PEOPLE_BUSINESS_ID, PEOPLE_ID, BUSINESS_ID)
select RNT_PEOPLE_BU_SEQ.NEXTVAL, p.PEOPLE_ID, bu.BUSINESS_ID
from RNT_PEOPLE p,
     RNT_BUSINESS_UNITS bu
where bu.PARENT_BUSINESS_ID = p.BUSINESS_ID     
/

commit
/
