insert into RNT_SECTION8_OFFICES_BU (
   SECTION8_BUSINESS_ID, SECTION8_ID, BUSINESS_ID) 
select RNT_SECTION8_OFFICES_BU_SEQ.NEXTVAL, so.SECTION8_ID, bu.BUSINESS_ID
from RNT_SECTION8_OFFICES so,
     RNT_BUSINESS_UNITS bu
where bu.PARENT_BUSINESS_ID = so.BUSINESS_ID     

/

commit
/

