CREATE OR REPLACE FORCE VIEW RNT_PEOPLE_LIST_V
(PEOPLE_ID, FIRST_NAME, LAST_NAME, PHONE1, PHONE2, 
 DATE_OF_BIRTH, EMAIL_ADDRESS, SSN, DRIVERS_LICENSE, BUSINESS_ID, 
 PEOPLE_BUSINESS_ID, CHECKSUM)
AS 
select p.PEOPLE_ID, p.FIRST_NAME, p.LAST_NAME, 
       p.PHONE1, p.PHONE2, p.DATE_OF_BIRTH, p.EMAIL_ADDRESS, 
       p.SSN, p.DRIVERS_LICENSE, bu.BUSINESS_ID, 
       pbu.PEOPLE_BUSINESS_ID,
       rnt_sys_checksum_rec_pkg.get_checksum( 
       'PEOPLE_ID='||p.PEOPLE_ID||',FIRST_NAME='||p.FIRST_NAME||',LAST_NAME='||p.LAST_NAME||
       ',PHONE1='||p.PHONE1||',PHONE2='||p.PHONE2||'EMAIL_ADDRESS='||p.EMAIL_ADDRESS||',SSN='||p.SSN||
       ',DRIVERS_LICENSE='||p.DRIVERS_LICENSE||',DATE_OF_BIRTH='||p.DATE_OF_BIRTH||
       ',BUSINESS_ID='||bu.BUSINESS_ID||',PEOPLE_BUSINESS_ID='||pbu.PEOPLE_BUSINESS_ID
       ) as CHECKSUM
from RNT_PEOPLE p,
     RNT_BUSINESS_UNITS_V bu,
     RNT_PEOPLE_BU pbu
where bu.PARENT_BUSINESS_ID != 0
  and pbu.PEOPLE_ID = p.PEOPLE_ID
  and pbu.BUSINESS_ID = bu.BUSINESS_ID;

CREATE OR REPLACE FORCE VIEW RNT_SECTION8_OFFICES_V
(SECTION8_ID, SECTION_NAME, BUSINESS_ID, SECTION8_BUSINESS_ID, CHECKSUM)
AS 
select s8.SECTION8_ID, s8.SECTION_NAME, s8bu.BUSINESS_ID, s8bu.SECTION8_BUSINESS_ID,
       rnt_sys_checksum_rec_pkg.get_checksum('SECTION8_ID='||s8.SECTION8_ID||',SECTION_NAME='||s8.SECTION_NAME||',BUSINESS_ID='||s8bu.BUSINESS_ID||',SECTION8_BUSINESS_ID='||s8bu.SECTION8_BUSINESS_ID) as CHECKSUM 
from RNT_SECTION8_OFFICES s8,
     RNT_BUSINESS_UNITS_V bu,
     RNT_SECTION8_OFFICES_BU s8bu
where bu.PARENT_BUSINESS_ID != 0
  and s8bu.BUSINESS_ID = bu.BUSINESS_ID
  and s8.SECTION8_ID = s8bu.SECTION8_ID;

CREATE OR REPLACE FORCE VIEW RNT_TENANT_V1
(TENANT_ID, AGREEMENT_ID, STATUS, DEPOSIT_BALANCE, LAST_MONTH_BALANCE, 
 PEOPLE_ID, SECTION8_VOUCHER_AMOUNT, SECTION8_TENANT_PAYS, SECTION8_ID, TENANT_NOTE, 
 CHECKSUM, TENANT_STATUS_NAME, LAST_NAME, FIRST_NAME, PHONE1, 
 PHONE2, EMAIL_ADDRESS, SSN, DRIVERS_LICENSE, DATE_OF_BIRTH, 
 SECTION8_NAME, UNIT_NAME, AMOUNT, AMOUNTH_PERIOD_NAME, AGREEMENT_DATE, 
 BUSINESS_ID)
AS 
select 
   t.TENANT_ID, t.AGREEMENT_ID, t.STATUS, 
   t.DEPOSIT_BALANCE, t.LAST_MONTH_BALANCE, t.PEOPLE_ID, 
   t.SECTION8_VOUCHER_AMOUNT, t.SECTION8_TENANT_PAYS, t.SECTION8_ID,
   t.TENANT_NOTE,
   RNT_TENANT_PKG.GET_CHECKSUM(t.TENANT_ID) as CHECKSUM,
   lv.LOOKUP_VALUE as TENANT_STATUS_NAME,
   p.LAST_NAME, p.FIRST_NAME,
   p.PHONE1, p.PHONE2, p.EMAIL_ADDRESS, 
   p.SSN, p.DRIVERS_LICENSE, p.DATE_OF_BIRTH,
   so.SECTION_NAME as SECTION8_NAME,
   pu.UNIT_NAME, ta.AMOUNT, ta.AMOUNTH_PERIOD_NAME, ta.AGREEMENT_DATE,
   pu.BUSINESS_ID  
from RNT_TENANT t,
     RNT_LOOKUP_VALUES_V lv,
     RNT_PEOPLE p,
     RNT_SECTION8_OFFICES so,
     RNT_TENANCY_AGREEMENT_V ta,
     RNT_PROPERTY_UNITS_V pu
where lv.LOOKUP_TYPE_CODE = 'TENANT_STATUS'
  and lv.LOOKUP_CODE = t.STATUS
  and p.PEOPLE_ID = t.PEOPLE_ID
  and so.SECTION8_ID(+) = t.SECTION8_ID
  and ta.AGREEMENT_ID = t.AGREEMENT_ID
  and pu.UNIT_ID = ta.UNIT_ID;
