ALTER TABLE RNT_PEOPLE DROP COLUMN BUSINESS_ID;

ALTER TABLE RNT_PEOPLE DROP COLUMN IS_ENABLED_YN;

ALTER TABLE RNT_SECTION8_OFFICES DROP COLUMN BUSINESS_ID;

SHOW ERRORS;

ALTER TABLE RNT_SECTION8_OFFICES_BU
 ADD CONSTRAINT RNT_SECTION8_OFFICES_BU_FK1 
 FOREIGN KEY (BUSINESS_ID) 
 REFERENCES RNT_BUSINESS_UNITS (BUSINESS_ID);

ALTER TABLE RNT_SECTION8_OFFICES_BU
 ADD CONSTRAINT RNT_SECTION8_OFFICES_BU_FK2 
 FOREIGN KEY (SECTION8_ID) 
 REFERENCES RNT_SECTION8_OFFICES (SECTION8_ID);

ALTER TABLE RNT_PEOPLE_BU
 ADD CONSTRAINT RNT_PEOPLE_BU_FK1 
 FOREIGN KEY (BUSINESS_ID) 
 REFERENCES RNT_BUSINESS_UNITS (BUSINESS_ID);

ALTER TABLE RNT_PEOPLE_BU
 ADD CONSTRAINT RNT_PEOPLE_BU_FK2 
 FOREIGN KEY (PEOPLE_ID) 
 REFERENCES RNT_PEOPLE (PEOPLE_ID);