ALTER VIEW RNT_USER_ASSIGNMENTS_V COMPILE;

ALTER PACKAGE RNT_USERS_PKG COMPILE;

ALTER PACKAGE RNT_USERS_PKG COMPILE BODY;

ALTER VIEW RNT_USERS_V COMPILE;


ALTER PACKAGE RNT_SECTION8_OFFICES_PKG COMPILE;

ALTER PACKAGE RNT_SUPPLIERS_PKG COMPILE;

ALTER PACKAGE RNT_SECTION8_OFFICES_PKG COMPILE BODY;

ALTER PACKAGE RNT_SUPPLIERS_PKG COMPILE BODY;

ALTER PACKAGE RNT_PAYMENTS_PKG COMPILE BODY;

ALTER PACKAGE RNT_PROPERTY_UNITS_PKG COMPILE BODY;

ALTER PACKAGE RNT_BUSINESS_UNITS_PKG COMPILE BODY;

ALTER VIEW RNT_BUSINESS_UNITS_V COMPILE;

ALTER VIEW RNT_PROPERTIES_V COMPILE;

ALTER VIEW RNT_PEOPLE_LIST_V COMPILE;

ALTER VIEW RNT_SUPPLIERS_V COMPILE;

ALTER VIEW RNT_SECTION8_OFFICES_V COMPILE;

ALTER VIEW RNT_PROPERTY_UNITS_V COMPILE;

ALTER VIEW RNT_TENANCY_AGREEMENT_V COMPILE;

ALTER VIEW RNT_TENANT_V1 COMPILE;