ALTER TABLE RNT_ERROR_DESCRIPTION
 ADD (DISPLAY_SHORT_DESCRIPTION_YN  VARCHAR2(1 BYTE) NULL);


update RNT_ERROR_DESCRIPTION
set DISPLAY_SHORT_DESCRIPTION_YN = 'Y';

commit;

ALTER TABLE RNT_ERROR_DESCRIPTION
 MODIFY (DISPLAY_SHORT_DESCRIPTION_YN  VARCHAR2(1 BYTE) NOT NULL);

COMMENT ON COLUMN RNT_ERROR_DESCRIPTION.DISPLAY_SHORT_DESCRIPTION_YN IS 'if Y then short description must be displayed, overwise display error message from database.';

CREATE OR REPLACE FORCE VIEW RNT_ERROR_DESCRIPTION_V
(ERROR_ID, ERROR_CODE, SHORT_DESCRIPTION, LONG_DESCRIPTION, SHOW_LONG_DESCRIPTION_YN, 
 CLASSIFIED_DESCRIPTION, DISPLAY_SHORT_DESCRIPTION_YN, CHECKSUM)
AS 
select ERROR_ID
,      ERROR_CODE
,      SHORT_DESCRIPTION
,      LONG_DESCRIPTION
,      SHOW_LONG_DESCRIPTION_YN
,      CLASSIFIED_DESCRIPTION
,      DISPLAY_SHORT_DESCRIPTION_YN  
,      rnt_sys_checksum_rec_pkg.get_checksum('ERROR_ID='||ERROR_ID||'ERROR_CODE='||ERROR_CODE||'SHORT_DESCRIPTION='||SHORT_DESCRIPTION||'LONG_DESCRIPTION='||LONG_DESCRIPTION||'SHOW_LONG_DESCRIPTION_YN='||SHOW_LONG_DESCRIPTION_YN||'CLASSIFIED_DESCRIPTION='||CLASSIFIED_DESCRIPTION||'DISPLAY_SHORT_DESCRIPTION_YN='||DISPLAY_SHORT_DESCRIPTION_YN) as CHECKSUM
from RNT_ERROR_DESCRIPTION;



