CREATE SEQUENCE RNT_USER_REGISTRY_SEQ
  START WITH 23
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

CREATE TABLE RNT_USER_REGISTRY
(
  USER_REGISTRY_ID  NUMBER                      NOT NULL,
  USER_LOGIN_EMAIL  VARCHAR2(50 BYTE)           NOT NULL,
  USER_PASSWORD     VARCHAR2(64 BYTE)           NOT NULL,
  USER_HASH_VALUE   VARCHAR2(64 BYTE)           NOT NULL,
  USER_NAME         VARCHAR2(50 BYTE)           NOT NULL,
  USER_LAST_NAME    VARCHAR2(50 BYTE)           NOT NULL,
  INVITE_USER_ID    NUMBER,
  LAST_UPDATE_DATE  DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE RNT_USER_REGISTRY IS 'User who must registry information.';

COMMENT ON COLUMN RNT_USER_REGISTRY.USER_REGISTRY_ID IS 'Resitry user ID';

COMMENT ON COLUMN RNT_USER_REGISTRY.USER_LOGIN_EMAIL IS 'User Login as E-mail';

COMMENT ON COLUMN RNT_USER_REGISTRY.USER_PASSWORD IS 'User password';

COMMENT ON COLUMN RNT_USER_REGISTRY.USER_HASH_VALUE IS 'User hash value for enter';

COMMENT ON COLUMN RNT_USER_REGISTRY.USER_NAME IS 'User name';

COMMENT ON COLUMN RNT_USER_REGISTRY.USER_LAST_NAME IS 'User last name';

COMMENT ON COLUMN RNT_USER_REGISTRY.INVITE_USER_ID IS 'ID of user who invited this user. If null user not has been invited.';

COMMENT ON COLUMN RNT_USER_REGISTRY.LAST_UPDATE_DATE IS 'Update or creation date';

CREATE UNIQUE INDEX RNT_USER_REGISTRY_U1 ON RNT_USER_REGISTRY
(USER_HASH_VALUE)
LOGGING
NOPARALLEL;

CREATE UNIQUE INDEX RNT_USER_REGISTRY_PK ON RNT_USER_REGISTRY
(USER_REGISTRY_ID)
LOGGING
NOPARALLEL;

ALTER TABLE RNT_USER_REGISTRY
 ADD CONSTRAINT RNT_USER_REGISTRY_PK
 PRIMARY KEY
 (USER_REGISTRY_ID);
