INSERT INTO RNT_LOOKUP_VALUES (
   LOOKUP_VALUE_ID, LOOKUP_CODE, LOOKUP_VALUE, 
   LOOKUP_TYPE_ID) 
VALUES ((select max(LOOKUP_VALUE_ID)+1 from RNT_LOOKUP_VALUES), 'PH', 'Phone Call', 5);

INSERT INTO RNT_LOOKUP_VALUES (
   LOOKUP_VALUE_ID, LOOKUP_CODE, LOOKUP_VALUE, 
   LOOKUP_TYPE_ID) 
VALUES ((select max(LOOKUP_VALUE_ID)+1 from RNT_LOOKUP_VALUES), 'SL', 'Sent Letter', 5);

INSERT INTO RNT_LOOKUP_VALUES (
   LOOKUP_VALUE_ID, LOOKUP_CODE, LOOKUP_VALUE, 
   LOOKUP_TYPE_ID) 
VALUES ((select max(LOOKUP_VALUE_ID)+1 from RNT_LOOKUP_VALUES), 'SI', 'Sent Invoice', 5);

INSERT INTO RNT_LOOKUP_VALUES (
   LOOKUP_VALUE_ID, LOOKUP_CODE, LOOKUP_VALUE, 
   LOOKUP_TYPE_ID) 
VALUES ((select max(LOOKUP_VALUE_ID)+1 from RNT_LOOKUP_VALUES), 'RD', 'Return of Deposit', 5);

INSERT INTO RNT_LOOKUP_VALUES (
   LOOKUP_VALUE_ID, LOOKUP_CODE, LOOKUP_VALUE, 
   LOOKUP_TYPE_ID) 
VALUES ((select max(LOOKUP_VALUE_ID)+1 from RNT_LOOKUP_VALUES), 'O', 'Other', 5);

commit;


