ALTER TABLE RNT_SECTION8_OFFICES
ADD (BUSINESS_ID NUMBER)
/

update RNT_SECTION8_OFFICES
set BUSINESS_ID = (select BUSINESS_ID from RNT_BUSINESS_UNITS where PARENT_BUSINESS_ID = 0 and rownum < 2)
/

commit
/

ALTER TABLE RNT_SECTION8_OFFICES
MODIFY(BUSINESS_ID  NOT NULL)
/

COMMENT ON COLUMN 
RNT_SECTION8_OFFICES.BUSINESS_ID IS 
'Business ID'
/


CREATE OR REPLACE FORCE VIEW RNT_SECTION8_OFFICES_V
(SECTION8_ID, SECTION_NAME, BUSINESS_ID, CHECKSUM)
AS 
select s8.SECTION8_ID, s8.SECTION_NAME, s8.BUSINESS_ID,
       rnt_sys_checksum_rec_pkg.get_checksum('SECTION8_ID='||s8.SECTION8_ID||',SECTION_NAME='||s8.SECTION_NAME||',BUSINESS_ID='||s8.BUSINESS_ID) as CHECKSUM 
from RNT_SECTION8_OFFICES s8,
     RNT_BUSINESS_UNITS_V bu
where bu.PARENT_BUSINESS_ID = 0
  and s8.BUSINESS_ID = bu.BUSINESS_ID
/

