CREATE TABLE RNT_PROPERTY_ESTIMATES
(
  PROPERTY_ID            NUMBER                 NOT NULL,
  BUSINESS_ID            NUMBER                 NOT NULL,
  ESTIMATE_YEAR          DATE                   NOT NULL,
  ESTIMATE_TITLE         VARCHAR2(30 BYTE)      DEFAULT 'Pro-Forma Statement',
  MONTHLY_RENT           NUMBER                 NOT NULL,
  OTHER_INCOME           NUMBER                 DEFAULT 0,
  VACANCY_PCT            NUMBER(2)              DEFAULT 5,
  REPLACE_3YEARS         NUMBER                 DEFAULT 0,
  REPLACE_5YEARS         NUMBER                 DEFAULT 0,
  REPLACE_12YEARS        NUMBER                 DEFAULT 0,
  MAINTENANCE            NUMBER                 DEFAULT 0,
  UTILITIES              NUMBER                 DEFAULT 0,
  PROPERTY_TAXES         NUMBER                 DEFAULT 0,
  INSURANCE              NUMBER                 DEFAULT 0,
  MGT_FEES               NUMBER                 DEFAULT 0,
  DOWN_PAYMENT           NUMBER                 DEFAULT 0,
  CLOSING_COSTS          NUMBER                 DEFAULT 0,
  PURCHASE_PRICE         NUMBER,
  CAP_RATE               NUMBER,
  LOAN1_AMOUNT           NUMBER                 DEFAULT 0,
  LOAN1_TYPE             VARCHAR2(16 BYTE)      DEFAULT 'Amortizing',
  LOAN1_TERM             NUMBER,
  LOAN1_RATE             NUMBER                 DEFAULT 8.0,
  LOAN2_AMOUNT           NUMBER                 DEFAULT 0,
  LOAN2_TYPE             VARCHAR2(16 BYTE)      DEFAULT 'Interest Only',
  LOAN2_TERM             NUMBER,
  LOAN2_RATE             NUMBER                 DEFAULT 8.0,
  NOTES                  VARCHAR2(4000 BYTE),
  PROPERTY_ESTIMATES_ID  NUMBER                 NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN RNT_PROPERTY_ESTIMATES.PROPERTY_ESTIMATES_ID IS 'Primary Key';

CREATE UNIQUE INDEX RNT_PROPERTY_ESTIMATES_PK ON RNT_PROPERTY_ESTIMATES
(PROPERTY_ESTIMATES_ID)
LOGGING
NOPARALLEL;

CREATE UNIQUE INDEX RNT_PROPERTY_ESTIMATES_U1 ON RNT_PROPERTY_ESTIMATES
(PROPERTY_ID, BUSINESS_ID, ESTIMATE_YEAR, ESTIMATE_TITLE)
LOGGING
NOPARALLEL;

ALTER TABLE RNT_PROPERTY_ESTIMATES
 ADD CONSTRAINT RNT_PROPERTY_ESTIMATES_CHK2
 CHECK (loan2_type  in ('Amortizing', 'Interest Only'));

ALTER TABLE RNT_PROPERTY_ESTIMATES
 ADD CONSTRAINT RNT_PROPERTY_ESTIMATES_CHK1
 CHECK (loan1_type  in ('Amortizing', 'Interest Only'));

ALTER TABLE RNT_PROPERTY_ESTIMATES
 ADD CONSTRAINT RNT_PROPERTY_ESTIMATES_U1
 UNIQUE (PROPERTY_ID, BUSINESS_ID, ESTIMATE_YEAR, ESTIMATE_TITLE);

ALTER TABLE RNT_PROPERTY_ESTIMATES
 ADD CONSTRAINT RNT_PROPERTY_ESTIMATES_PK
 UNIQUE (PROPERTY_ESTIMATES_ID);

CREATE TABLE RNT_PROPERTY_LINKS
(
  PROPERTY_LINK_ID  NUMBER                      NOT NULL,
  PROPERTY_ID       NUMBER                      NOT NULL,
  LINK_TITLE        VARCHAR2(200 BYTE)          NOT NULL,
  LINK_URL          VARCHAR2(1000 BYTE)         NOT NULL,
  CREATION_DATE     DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX RNT_PROPERTY_LINKS_PK ON RNT_PROPERTY_LINKS
(PROPERTY_LINK_ID)
LOGGING
NOPARALLEL;

ALTER TABLE RNT_PROPERTY_LINKS
 ADD CONSTRAINT RNT_PROPERTY_LINKS_PK
 PRIMARY KEY
 (PROPERTY_LINK_ID);

ALTER TABLE RNT_PROPERTY_ESTIMATES
 ADD CONSTRAINT RNT_PROPERTY_ESTIMATES_FK1 
 FOREIGN KEY (PROPERTY_ID) 
 REFERENCES RNT_PROPERTIES (PROPERTY_ID);

ALTER TABLE RNT_PROPERTY_ESTIMATES
 ADD CONSTRAINT RNT_PROPERTY_ESTIMATES_FK2 
 FOREIGN KEY (BUSINESS_ID) 
 REFERENCES RNT_BUSINESS_UNITS (BUSINESS_ID);
