CREATE OR REPLACE FORCE VIEW RNT_PROPERTY_ESTIMATES_V
(PROPERTY_ESTIMATES_ID, PROPERTY_ID, BUSINESS_ID, ESTIMATE_YEAR, ESTIMATE_TITLE, 
 MONTHLY_RENT, OTHER_INCOME, VACANCY_PCT, REPLACE_3YEARS, REPLACE_5YEARS, 
 REPLACE_12YEARS, MAINTENANCE, UTILITIES, PROPERTY_TAXES, INSURANCE, 
 MGT_FEES, DOWN_PAYMENT, CLOSING_COSTS, PURCHASE_PRICE, CAP_RATE, 
 LOAN1_AMOUNT, LOAN1_TYPE, LOAN1_TERM, LOAN1_RATE, LOAN2_AMOUNT, 
 LOAN2_TYPE, LOAN2_TERM, LOAN2_RATE, NOTES, CHECKSUM)
AS 
select PROPERTY_ESTIMATES_ID
,      PROPERTY_ID
,      BUSINESS_ID
,      ESTIMATE_YEAR
,      ESTIMATE_TITLE
,      MONTHLY_RENT
,      OTHER_INCOME
,      VACANCY_PCT
,      REPLACE_3YEARS
,      REPLACE_5YEARS
,      REPLACE_12YEARS
,      MAINTENANCE
,      UTILITIES
,      PROPERTY_TAXES
,      INSURANCE
,      MGT_FEES
,      DOWN_PAYMENT
,      CLOSING_COSTS
,      PURCHASE_PRICE
,      CAP_RATE
,      LOAN1_AMOUNT
,      LOAN1_TYPE
,      LOAN1_TERM
,      LOAN1_RATE
,      LOAN2_AMOUNT
,      LOAN2_TYPE
,      LOAN2_TERM
,      LOAN2_RATE
,      NOTES
,      rnt_sys_checksum_rec_pkg.get_checksum('PROPERTY_ESTIMATES_ID='||PROPERTY_ESTIMATES_ID||'PROPERTY_ID='||PROPERTY_ID||'BUSINESS_ID='||BUSINESS_ID||'ESTIMATE_YEAR='||ESTIMATE_YEAR||'ESTIMATE_TITLE='||ESTIMATE_TITLE||'MONTHLY_RENT='||MONTHLY_RENT||'OTHER_INCOME='||OTHER_INCOME||'VACANCY_PCT='||VACANCY_PCT||'REPLACE_3YEARS='||REPLACE_3YEARS||'REPLACE_5YEARS='||REPLACE_5YEARS||'REPLACE_12YEARS='||REPLACE_12YEARS||'MAINTENANCE='||MAINTENANCE||'UTILITIES='||UTILITIES||'PROPERTY_TAXES='||PROPERTY_TAXES||'INSURANCE='||INSURANCE||'MGT_FEES='||MGT_FEES||'DOWN_PAYMENT='||DOWN_PAYMENT||'CLOSING_COSTS='||CLOSING_COSTS||'PURCHASE_PRICE='||PURCHASE_PRICE||'CAP_RATE='||CAP_RATE||'LOAN1_AMOUNT='||LOAN1_AMOUNT||'LOAN1_TYPE='||LOAN1_TYPE||'LOAN1_TERM='||LOAN1_TERM||'LOAN1_RATE='||LOAN1_RATE||'LOAN2_AMOUNT='||LOAN2_AMOUNT||'LOAN2_TYPE='||LOAN2_TYPE||'LOAN2_TERM='||LOAN2_TERM||'LOAN2_RATE='||LOAN2_RATE||'NOTES='||NOTES) as CHECKSUM
from RNT_PROPERTY_ESTIMATES;
