ALTER TABLE RNT_ACCOUNTS_RECEIVABLE
ADD (RECORD_TYPE VARCHAR2(1 BYTE));

COMMENT ON COLUMN 
RNT_ACCOUNTS_RECEIVABLE.RECORD_TYPE IS 
'Record type: G-generate, O - other payments. ';

update RNT_ACCOUNTS_RECEIVABLE
set RECORD_TYPE = decode(PAYMENT_TYPE, 11, 'O', 12, 'O', 'G');

commit;

ALTER TABLE RNT_ACCOUNTS_RECEIVABLE
MODIFY (RECORD_TYPE VARCHAR2(1 BYTE) NOT NULL);
