--------------------------------------------------------------------------
-- Play this script in TESTRNTMGR@XE to make it look like RNTMGR@XE
--                                                                      --
-- Please review the script before using it to make sure it won't       --
-- cause any unacceptable data loss.                                    --
--                                                                      --
-- TESTRNTMGR@XE Schema Extracted by User TESTRNTMGR 
-- RNTMGR@XE Schema Extracted by User RNTMGR 

ALTER TABLE RNT_ERROR_DESCRIPTION
 ADD (CLASSIFIED_DESCRIPTION  VARCHAR2(50 BYTE));

COMMENT ON COLUMN RNT_ERROR_DESCRIPTION.CLASSIFIED_DESCRIPTION IS 'Additional comment for message.';

SHOW ERRORS;

ALTER PACKAGE RNT_PROPERTY_EXPENSES_PKG COMPILE BODY;

ALTER PACKAGE RNT_LOANS_PKG COMPILE BODY;

ALTER VIEW RNT_TENANT_V COMPILE;

-- Difference: Status (no action taken since target is valid).
CREATE OR REPLACE FORCE VIEW RNT_ACCOUNTS_RECEIVABLE_ALL_V
(AR_ID, PAYMENT_DUE_DATE, AMOUNT, PAYMENT_TYPE, TENANT_ID, 
 AGREEMENT_ID, LOAN_ID, BUSINESS_ID, IS_GENERATED_YN, AGREEMENT_ACTION_ID, 
 PAYMENT_PROPERTY_ID, SOURCE_PAYMENT_ID, RECORD_TYPE, CHECKSUM)
AS 
select ar.AR_ID
,      ar.PAYMENT_DUE_DATE
,      ar.AMOUNT
,      ar.PAYMENT_TYPE
,      ar.TENANT_ID
,      ar.AGREEMENT_ID
,      ar.LOAN_ID
,      ar.BUSINESS_ID
,      ar.IS_GENERATED_YN
,      ar.AGREEMENT_ACTION_ID
,      ar.PAYMENT_PROPERTY_ID
,      ar.SOURCE_PAYMENT_ID
,      ar.RECORD_TYPE
,      rnt_sys_checksum_rec_pkg.get_checksum('AR_ID='||ar.AR_ID||'PAYMENT_DUE_DATE='||ar.PAYMENT_DUE_DATE||'AMOUNT='||ar.AMOUNT||'PAYMENT_TYPE='||ar.PAYMENT_TYPE||'TENANT_ID='||ar.TENANT_ID||'AGREEMENT_ID='||ar.AGREEMENT_ID||'LOAN_ID='||ar.LOAN_ID||'BUSINESS_ID='||ar.BUSINESS_ID||'IS_GENERATED_YN='||ar.IS_GENERATED_YN||
        'AGREEMENT_ACTION_ID='||ar.AGREEMENT_ACTION_ID||'PAYMENT_PROPERTY_ID='||ar.PAYMENT_PROPERTY_ID||
        'SOURCE_PAYMENT_ID='||ar.SOURCE_PAYMENT_ID||'RECORD_TYPE='||RECORD_TYPE) as CHECKSUM
from RNT_ACCOUNTS_RECEIVABLE ar;

CREATE OR REPLACE FORCE VIEW RNT_ACCOUNTS_RECEIVABLE_V
(AR_ID, PAYMENT_DUE_DATE, AMOUNT, PAYMENT_TYPE, TENANT_ID, 
 AGREEMENT_ID, LOAN_ID, BUSINESS_ID, IS_GENERATED_YN, AGREEMENT_ACTION_ID, 
 PAYMENT_PROPERTY_ID, CHECKSUM, PROPERTY_ID, RECEIVABLE_TYPE_NAME, UNIT_NAME, 
 ADDRESS1, ZIPCODE, UNITS, SOURCE_PAYMENT_ID, TENANT_NAME)
AS 
select ar.AR_ID
,      ar.PAYMENT_DUE_DATE
,      ar.AMOUNT
,      ar.PAYMENT_TYPE
,      ar.TENANT_ID
,      ar.AGREEMENT_ID
,      ar.LOAN_ID
,      ar.BUSINESS_ID
,      ar.IS_GENERATED_YN
,      ar.AGREEMENT_ACTION_ID
,      ar.PAYMENT_PROPERTY_ID
,      ar.CHECKSUM
,      u.PROPERTY_ID
,      pt.PAYMENT_TYPE_NAME as RECEIVABLE_TYPE_NAME
,      u.UNIT_NAME
,      prop.ADDRESS1
,      prop.ZIPCODE
,      prop.UNITS
,      ar.SOURCE_PAYMENT_ID
,      p.LAST_NAME||' '||p.FIRST_NAME as TENANT_NAME
from RNT_ACCOUNTS_RECEIVABLE_ALL_V ar,
     RNT_TENANT t,
     RNT_PEOPLE p,
     RNT_TENANCY_AGREEMENT a,
     RNT_PROPERTY_UNITS u,
     RNT_PAYMENT_TYPES pt,
     RNT_PROPERTIES prop
where a.AGREEMENT_ID = ar.AGREEMENT_ID
  and u.UNIT_ID = a.UNIT_ID
  and pt.PAYMENT_TYPE_ID = ar.PAYMENT_TYPE
  and prop.PROPERTY_ID = u.PROPERTY_ID
  and t.TENANT_ID = ar.TENANT_ID
  and p.PEOPLE_ID = t.PEOPLE_ID  
  and ar.RECORD_TYPE = RNT_ACC_RECEIVABLE_CONST_PKG.CONST_GENERATE_TYPE_VAL;

CREATE OR REPLACE FORCE VIEW RNT_ACCOUNTS_RECEIVABLE_PROP_V
(AR_ID, PAYMENT_DUE_DATE, AMOUNT, PAYMENT_TYPE, TENANT_ID, 
 AGREEMENT_ID, LOAN_ID, BUSINESS_ID, IS_GENERATED_YN, AGREEMENT_ACTION_ID, 
 PAYMENT_PROPERTY_ID, PROPERTY_NAME, CHECKSUM, PAYMENT_DATE)
AS 
select ar.AR_ID
,      ar.PAYMENT_DUE_DATE
,      ar.AMOUNT
,      ar.PAYMENT_TYPE
,      ar.TENANT_ID
,      ar.AGREEMENT_ID
,      ar.LOAN_ID
,      ar.BUSINESS_ID
,      ar.IS_GENERATED_YN
,      ar.AGREEMENT_ACTION_ID
,      ar.PAYMENT_PROPERTY_ID
,      p.ADDRESS1 as PROPERTY_NAME
,      ar.CHECKSUM
,      pa.PAYMENT_DATE
 from RNT_ACCOUNTS_RECEIVABLE_ALL_V ar,
      RNT_PROPERTIES p,
      RNT_PAYMENT_ALLOCATIONS pa 
where ar.PAYMENT_PROPERTY_ID = p.PROPERTY_ID
  and pa.AR_ID(+) = ar.AR_ID  
  and ar.RECORD_TYPE = RNT_ACC_RECEIVABLE_CONST_PKG.CONST_OTHER_TYPE_VAL;

ALTER VIEW RNT_ACCNTS_PAYABLE_EXPENSES_V COMPILE;

ALTER PACKAGE RNT_PAYMENT_ALLOCATIONS_PKG COMPILE BODY;

CREATE OR REPLACE FORCE VIEW RNT_ACCOUNTS_PAYABLE_PROP_V
(AP_ID, PAYMENT_DUE_DATE, AMOUNT, PAYMENT_TYPE_ID, EXPENSE_ID, 
 LOAN_ID, SUPPLIER_ID, PAYMENT_PROPERTY_ID, CHECKSUM, PAYMENT_DATE, 
 BUSINESS_ID, INVOICE_NUMBER)
AS 
select 
   ap.AP_ID, 
   ap.PAYMENT_DUE_DATE, 
   ap.AMOUNT, 
   ap.PAYMENT_TYPE_ID, 
   ap.EXPENSE_ID, 
   ap.LOAN_ID, 
   ap.SUPPLIER_ID, 
   ap.PAYMENT_PROPERTY_ID, 
   ap.CHECKSUM,
   pa.PAYMENT_DATE,
   ap.BUSINESS_ID,
   ap.INVOICE_NUMBER
from RNT_ACCOUNTS_PAYABLE_ALL_V ap,
     RNT_PROPERTIES p,
     RNT_PAYMENT_ALLOCATIONS pa 
where ap.PAYMENT_PROPERTY_ID = p.PROPERTY_ID(+)
  and pa.AP_ID(+) = ap.AP_ID
  and ap.RECORD_TYPE = RNT_ACCOUNTS_PAYABLE_PKG.CONST_OTHER_TYPE_VAL;

ALTER VIEW RNT_TENANT_V1 COMPILE;

