DROP INDEX RNT_EXPENSE_ITEMS_I1;

CREATE SEQUENCE RNT_PROPERTY_PHOTOS_SEQ
  START WITH 28
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

CREATE TABLE RNT_PROPERTY_PHOTOS
(
  PHOTO_ID        NUMBER                        NOT NULL,
  PHOTO_TITLE     VARCHAR2(300 BYTE)            NOT NULL,
  PHOTO_FILENAME  VARCHAR2(1024 BYTE)           NOT NULL,
  PROPERTY_ID     NUMBER                        NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE RNT_PROPERTY_PHOTOS IS 'Photos of property.';

COMMENT ON COLUMN RNT_PROPERTY_PHOTOS.PHOTO_ID IS 'Photo ID';

COMMENT ON COLUMN RNT_PROPERTY_PHOTOS.PHOTO_TITLE IS 'Photo title';

COMMENT ON COLUMN RNT_PROPERTY_PHOTOS.PHOTO_FILENAME IS 'Filename with photo';

COMMENT ON COLUMN RNT_PROPERTY_PHOTOS.PROPERTY_ID IS 'FK to Property ID';

CREATE UNIQUE INDEX RNT_PROPERTY_PHOTOS_PK ON RNT_PROPERTY_PHOTOS
(PHOTO_ID)
LOGGING
NOPARALLEL;

ALTER TABLE RNT_PROPERTY_PHOTOS
 ADD CONSTRAINT RNT_PROPERTY_PHOTOS_PK
 PRIMARY KEY
 (PHOTO_ID);


ALTER TABLE RNT_PROPERTY_PHOTOS
 ADD CONSTRAINT RNT_PROPERTY_PHOTOS_FK1 
 FOREIGN KEY (PROPERTY_ID) 
 REFERENCES RNT_PROPERTIES (PROPERTY_ID);

CREATE OR REPLACE FORCE VIEW RNT_PROPERTY_PHOTOS_V
(PHOTO_ID, PHOTO_TITLE, PHOTO_FILENAME, PROPERTY_ID, CHECKSUM)
AS 
select PHOTO_ID
,      PHOTO_TITLE
,      PHOTO_FILENAME
,      PROPERTY_ID
,      rnt_sys_checksum_rec_pkg.get_checksum('PHOTO_ID='||PHOTO_ID||'PHOTO_TITLE='||PHOTO_TITLE||'PHOTO_FILENAME='||PHOTO_FILENAME||'PROPERTY_ID='||PROPERTY_ID) as CHECKSUM
from RNT_PROPERTY_PHOTOS;

COMMENT ON COLUMN RNT_EXPENSE_ITEMS.ORDER_ROW IS 'Row number for sort';

COMMENT ON COLUMN RNT_EXPENSE_ITEMS.ITEM_UNIT IS 'Allowed values HR and FT';
