begin
/*
  CREATE UNIQUE INDEX "RNTMGR"."PR_PROPERTIES_U2" ON "RNTMGR"."PR_PROPERTIES" ("ADDRESS1", "ADDRESS2", "ZIPCODE")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 75497472 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE INDEX "RNTMGR"."PR_PROPERTIES_N1" ON "RNTMGR"."PR_PROPERTIES" ("SOURCE_PK")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 36700160 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE INDEX "RNTMGR"."PR_PROPERTIES_N2" ON "RNTMGR"."PR_PROPERTIES" ("ZIPCODE")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 25165824 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE INDEX "RNTMGR"."PR_PROPERTIES_FB1" ON "RNTMGR"."PR_PROPERTIES" ("RNTMGR"."PR_RECORDS_PKG"."STANDARD_SUFFIX"("ADDRESS1"))
  PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS
  STORAGE(INITIAL 40894464 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE INDEX "RNTMGR"."PR_PROPERTIES_FB2" ON "RNTMGR"."PR_PROPERTIES" ("RNTMGR"."PR_RECORDS_PKG"."SQFT_CLASS"("SQ_FT"))
  PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS
  STORAGE(INITIAL 32505856 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

 CREATE INDEX "RNTMGR"."PR_PROPERTIES_X1" ON "RNTMGR"."PR_PROPERTIES" ("ADDRESS1")
   INDEXTYPE IS "CTXSYS"."CTXCAT"  PARAMETERS ('index set pr_city_iset');
*/
  drop index PR_PROPERTIES_X1;
  drop index PR_PROPERTIES_FB1;
  drop index PR_PROPERTIES_FB2;
  drop index PR_PROPERTIES_N1;
  drop index PR_PROPERTIES_N2;
  drop index PR_OWNER_X1;
end;
/

exec ctx_ddl.create_index_set('pr_city_iset');

  CREATE INDEX "RNTMGR"."PR_OWNER_X1" ON "RNTMGR"."PR_OWNERS" ("OWNER_NAME")
   INDEXTYPE IS "CTXSYS"."CTXCAT" ;


    CREATE INDEX "RNTMGR"."PR_PROPERTIES_X1" ON "RNTMGR"."PR_PROPERTIES" ("ADDRESS1")
       INDEXTYPE IS "CTXSYS"."CTXCAT"  PARAMETERS ('index set pr_city_iset');
       
 CREATE INDEX "RNTMGR"."PR_PROPERTIES_X1" ON "RNTMGR"."PR_PROPERTIES" ("ADDRESS1")
*
ERROR at line 1:
ORA-29855: error occurred in the execution of ODCIINDEXCREATE routine
ORA-20000: Oracle Text error:
DRG-50857: oracle error in drvxtabc.create_indexes:TC
ORA-04020: deadlock detected while trying to lock object RNTMGR.PR_PROPERTIES
ORA-06512: at "CTXSYS.DRUE", line 160
ORA-06512: at "CTXSYS.CATINDEXMETHODS", line 99

