-- Duplicate entry for Pay Alloc ID = 2473
-- Payment Type = 7
-- Debit Account = 3022
-- Credit Account = 3026
delete from rnt_ledger_entries where ledger_id = 29023;
-- Duplicate entry for Pay Alloc ID = 2559
-- Payment Type = 7
-- Debit Account = 3022
-- Credit Account = 3026
delete from rnt_ledger_entries where ledger_id = 29022;
-- Duplicate entry for Pay Alloc ID = 3193
-- Payment Type = 7
-- Debit Account = 3022
-- Credit Account = 3026
delete from rnt_ledger_entries where ledger_id = 29024;
-- Duplicate entry for Pay Alloc ID = 8257
-- Payment Type = 7
-- Debit Account = 107
-- Credit Account = 111
delete from rnt_ledger_entries where ledger_id = 29002;
-- Duplicate entry for Pay Alloc ID = 9390
-- Payment Type = 7
-- Debit Account = 107
-- Credit Account = 111
delete from rnt_ledger_entries where ledger_id = 29003;
-- Duplicate entry for Pay Alloc ID = 9806
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 32205;
-- Duplicate entry for Pay Alloc ID = 9821
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 32199;
-- Duplicate entry for Pay Alloc ID = 9822
-- Payment Type = 14
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 32225;
-- Duplicate entry for Pay Alloc ID = 9823
-- Payment Type = 14
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 32212;
-- Duplicate entry for Pay Alloc ID = 9824
-- Payment Type = 14
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 32213;
-- Duplicate entry for Pay Alloc ID = 9825
-- Payment Type = 14
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 32215;
-- Duplicate entry for Pay Alloc ID = 9826
-- Payment Type = 14
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 32226;
-- Duplicate entry for Pay Alloc ID = 9885
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 32188;
-- Duplicate entry for Pay Alloc ID = 9886
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 32195;
-- Duplicate entry for Pay Alloc ID = 9887
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 32198;
-- Duplicate entry for Pay Alloc ID = 9888
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 32200;
-- Duplicate entry for Pay Alloc ID = 9896
-- Payment Type = 14
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 32186;
-- Duplicate entry for Pay Alloc ID = 9902
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 32192;
-- Duplicate entry for Pay Alloc ID = 10103
-- Payment Type = 10
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 32194;
-- Duplicate entry for Pay Alloc ID = 10104
-- Payment Type = 10
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 32203;
-- Duplicate entry for Pay Alloc ID = 10105
-- Payment Type = 10
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 32208;
-- Duplicate entry for Pay Alloc ID = 10106
-- Payment Type = 10
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 32210;
-- Duplicate entry for Pay Alloc ID = 10107
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 32211;
-- Duplicate entry for Pay Alloc ID = 10108
-- Payment Type = 10
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 32214;
-- Duplicate entry for Pay Alloc ID = 10152
-- Payment Type = 7
-- Debit Account = 107
-- Credit Account = 111
delete from rnt_ledger_entries where ledger_id = 29004;
-- Duplicate entry for Pay Alloc ID = 10196
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 32204;
-- Duplicate entry for Pay Alloc ID = 10236
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 32206;
-- Duplicate entry for Pay Alloc ID = 10237
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 32209;
-- Duplicate entry for Pay Alloc ID = 10357
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 32218;
-- Duplicate entry for Pay Alloc ID = 10476
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 32207;
-- Duplicate entry for Pay Alloc ID = 10477
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 32222;
-- Duplicate entry for Pay Alloc ID = 10478
-- Payment Type = 10
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 32223;
-- Duplicate entry for Pay Alloc ID = 10479
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 32219;
-- Duplicate entry for Pay Alloc ID = 10767
-- Payment Type = 7
-- Debit Account = 3022
-- Credit Account = 3026
delete from rnt_ledger_entries where ledger_id = 29025;
-- Duplicate entry for Pay Alloc ID = 10796
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 32196;
-- Duplicate entry for Pay Alloc ID = 10798
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 32193;
-- Duplicate entry for Pay Alloc ID = 10802
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 32220;
-- Duplicate entry for Pay Alloc ID = 10803
-- Payment Type = 10
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 32221;
-- Duplicate entry for Pay Alloc ID = 11117
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 32185;
-- Duplicate entry for Pay Alloc ID = 11187
-- Payment Type = 10
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 32187;
-- Duplicate entry for Pay Alloc ID = 11237
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 32189;
-- Duplicate entry for Pay Alloc ID = 11317
-- Payment Type = 10
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 32224;
-- Duplicate entry for Pay Alloc ID = 11937
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 32190;
-- Duplicate entry for Pay Alloc ID = 11938
-- Payment Type = 10
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 32191;
-- Duplicate entry for Pay Alloc ID = 12116
-- Payment Type = 7
-- Debit Account = 3075
-- Credit Account = 3079
delete from rnt_ledger_entries where ledger_id = 28741;
-- Duplicate entry for Pay Alloc ID = 12241
-- Payment Type = 7
-- Debit Account = 3022
-- Credit Account = 3026
delete from rnt_ledger_entries where ledger_id = 29026;
-- Duplicate entry for Pay Alloc ID = 12624
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 32201;
-- Duplicate entry for Pay Alloc ID = 12753
-- Payment Type = 7
-- Debit Account = 3075
-- Credit Account = 3079
delete from rnt_ledger_entries where ledger_id = 28742;
-- Duplicate entry for Pay Alloc ID = 12756
-- Payment Type = 10
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 32197;
-- Duplicate entry for Pay Alloc ID = 12802
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 32202;
-- Duplicate entry for Pay Alloc ID = 13802
-- Payment Type = 7
-- Debit Account = 3075
-- Credit Account = 3079
delete from rnt_ledger_entries where ledger_id = 28743;
-- Duplicate entry for Pay Alloc ID = 16089
-- Payment Type = 14
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 32216;
-- Duplicate entry for Pay Alloc ID = 16717
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 28937;
-- Duplicate entry for Pay Alloc ID = 17365
-- Payment Type = 14
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 32217;
-- Duplicate entry for Pay Alloc ID = 18702
-- Payment Type = 7
-- Debit Account = 213
-- Credit Account = 217
delete from rnt_ledger_entries where ledger_id = 28759;
-- Duplicate entry for Pay Alloc ID = 19376
-- Payment Type = 7
-- Debit Account = 3181
-- Credit Account = 3185
delete from rnt_ledger_entries where ledger_id = 28701;
-- Duplicate entry for Pay Alloc ID = 19558
-- Payment Type = 7
-- Debit Account = 3181
-- Credit Account = 3185
delete from rnt_ledger_entries where ledger_id = 28702;
-- Duplicate entry for Pay Alloc ID = 19657
-- Payment Type = 10
-- Debit Account = 3022
-- Credit Account = 3026
delete from rnt_ledger_entries where ledger_id = 29027;
-- Duplicate entry for Pay Alloc ID = 19821
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 28938;
-- Duplicate entry for Pay Alloc ID = 20678
-- Payment Type = 7
-- Debit Account = 3181
-- Credit Account = 3185
delete from rnt_ledger_entries where ledger_id = 28703;
-- Duplicate entry for Pay Alloc ID = 21156
-- Payment Type = 7
-- Debit Account = 3022
-- Credit Account = 3026
delete from rnt_ledger_entries where ledger_id = 29028;
-- Duplicate entry for Pay Alloc ID = 22918
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 28939;
-- Duplicate entry for Pay Alloc ID = 23196
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 30379;
-- Duplicate entry for Pay Alloc ID = 23197
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 30402;
-- Duplicate entry for Pay Alloc ID = 23380
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 30386;
-- Duplicate entry for Pay Alloc ID = 23381
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 30388;
-- Duplicate entry for Pay Alloc ID = 23382
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 30412;
-- Duplicate entry for Pay Alloc ID = 23596
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 28940;
-- Duplicate entry for Pay Alloc ID = 23597
-- Payment Type = 14
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 30378;
-- Duplicate entry for Pay Alloc ID = 23598
-- Payment Type = 14
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 30391;
-- Duplicate entry for Pay Alloc ID = 23676
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 30400;
-- Duplicate entry for Pay Alloc ID = 23776
-- Payment Type = 14
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 30408;
-- Duplicate entry for Pay Alloc ID = 23777
-- Payment Type = 14
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 30410;
-- Duplicate entry for Pay Alloc ID = 23778
-- Payment Type = 14
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 30413;
-- Duplicate entry for Pay Alloc ID = 24256
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 30411;
-- Duplicate entry for Pay Alloc ID = 24356
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 30397;
-- Duplicate entry for Pay Alloc ID = 24418
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 30380;
-- Duplicate entry for Pay Alloc ID = 24476
-- Payment Type = 14
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 30414;
-- Duplicate entry for Pay Alloc ID = 24497
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 30382;
-- Duplicate entry for Pay Alloc ID = 24498
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 30406;
-- Duplicate entry for Pay Alloc ID = 24499
-- Payment Type = 9
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 30407;
-- Duplicate entry for Pay Alloc ID = 24503
-- Payment Type = 9
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 30392;
-- Duplicate entry for Pay Alloc ID = 24504
-- Payment Type = 14
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 30409;
-- Duplicate entry for Pay Alloc ID = 24519
-- Payment Type = 7
-- Debit Account = 3181
-- Credit Account = 3185
delete from rnt_ledger_entries where ledger_id = 28704;
-- Duplicate entry for Pay Alloc ID = 24637
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 30404;
-- Duplicate entry for Pay Alloc ID = 24656
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 30398;
-- Duplicate entry for Pay Alloc ID = 24696
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 30401;
-- Duplicate entry for Pay Alloc ID = 24697
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 30403;
-- Duplicate entry for Pay Alloc ID = 24757
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 30395;
-- Duplicate entry for Pay Alloc ID = 24761
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 28941;
-- Duplicate entry for Pay Alloc ID = 24842
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 30390;
-- Duplicate entry for Pay Alloc ID = 24898
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 30405;
-- Duplicate entry for Pay Alloc ID = 24899
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 30399;
-- Duplicate entry for Pay Alloc ID = 24936
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 30387;
-- Duplicate entry for Pay Alloc ID = 24976
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 30383;
-- Duplicate entry for Pay Alloc ID = 24977
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 30389;
-- Duplicate entry for Pay Alloc ID = 25139
-- Payment Type = 7
-- Debit Account = 1909
-- Credit Account = 1913
delete from rnt_ledger_entries where ledger_id = 29663;
-- Duplicate entry for Pay Alloc ID = 25140
-- Payment Type = 7
-- Debit Account = 1909
-- Credit Account = 1913
delete from rnt_ledger_entries where ledger_id = 29667;
-- Duplicate entry for Pay Alloc ID = 25141
-- Payment Type = 7
-- Debit Account = 1909
-- Credit Account = 1913
delete from rnt_ledger_entries where ledger_id = 29668;
-- Duplicate entry for Pay Alloc ID = 25142
-- Payment Type = 7
-- Debit Account = 1909
-- Credit Account = 1913
delete from rnt_ledger_entries where ledger_id = 29669;
-- Duplicate entry for Pay Alloc ID = 25143
-- Payment Type = 7
-- Debit Account = 1909
-- Credit Account = 1913
delete from rnt_ledger_entries where ledger_id = 29670;
-- Duplicate entry for Pay Alloc ID = 25144
-- Payment Type = 7
-- Debit Account = 1909
-- Credit Account = 1913
delete from rnt_ledger_entries where ledger_id = 29671;
-- Duplicate entry for Pay Alloc ID = 25145
-- Payment Type = 7
-- Debit Account = 1909
-- Credit Account = 1913
delete from rnt_ledger_entries where ledger_id = 29674;
-- Duplicate entry for Pay Alloc ID = 25146
-- Payment Type = 7
-- Debit Account = 1909
-- Credit Account = 1913
delete from rnt_ledger_entries where ledger_id = 29675;
-- Duplicate entry for Pay Alloc ID = 25147
-- Payment Type = 7
-- Debit Account = 1909
-- Credit Account = 1913
delete from rnt_ledger_entries where ledger_id = 29676;
-- Duplicate entry for Pay Alloc ID = 25148
-- Payment Type = 7
-- Debit Account = 1909
-- Credit Account = 1913
delete from rnt_ledger_entries where ledger_id = 29664;
-- Duplicate entry for Pay Alloc ID = 25149
-- Payment Type = 7
-- Debit Account = 1909
-- Credit Account = 1913
delete from rnt_ledger_entries where ledger_id = 29677;
-- Duplicate entry for Pay Alloc ID = 25150
-- Payment Type = 7
-- Debit Account = 1909
-- Credit Account = 1913
delete from rnt_ledger_entries where ledger_id = 29680;
-- Duplicate entry for Pay Alloc ID = 25151
-- Payment Type = 7
-- Debit Account = 1909
-- Credit Account = 1913
delete from rnt_ledger_entries where ledger_id = 29678;
-- Duplicate entry for Pay Alloc ID = 25152
-- Payment Type = 7
-- Debit Account = 1909
-- Credit Account = 1913
delete from rnt_ledger_entries where ledger_id = 29665;
-- Duplicate entry for Pay Alloc ID = 25153
-- Payment Type = 7
-- Debit Account = 1909
-- Credit Account = 1913
delete from rnt_ledger_entries where ledger_id = 29673;
-- Duplicate entry for Pay Alloc ID = 25154
-- Payment Type = 7
-- Debit Account = 1909
-- Credit Account = 1913
delete from rnt_ledger_entries where ledger_id = 29679;
-- Duplicate entry for Pay Alloc ID = 25155
-- Payment Type = 7
-- Debit Account = 1909
-- Credit Account = 1913
delete from rnt_ledger_entries where ledger_id = 29662;
-- Duplicate entry for Pay Alloc ID = 25158
-- Payment Type = 7
-- Debit Account = 1909
-- Credit Account = 1913
delete from rnt_ledger_entries where ledger_id = 29666;
-- Duplicate entry for Pay Alloc ID = 25176
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 30384;
-- Duplicate entry for Pay Alloc ID = 25185
-- Payment Type = 7
-- Debit Account = 3022
-- Credit Account = 3026
delete from rnt_ledger_entries where ledger_id = 29034;
-- Duplicate entry for Pay Alloc ID = 25478
-- Payment Type = 7
-- Debit Account = 3075
-- Credit Account = 3079
delete from rnt_ledger_entries where ledger_id = 28744;
-- Duplicate entry for Pay Alloc ID = 25617
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 30381;
-- Duplicate entry for Pay Alloc ID = 25619
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 30385;
-- Duplicate entry for Pay Alloc ID = 25776
-- Payment Type = 9
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 30393;
-- Duplicate entry for Pay Alloc ID = 25857
-- Payment Type = 7
-- Debit Account = 3181
-- Credit Account = 3185
delete from rnt_ledger_entries where ledger_id = 28705;
-- Duplicate entry for Pay Alloc ID = 25937
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 30396;
-- Duplicate entry for Pay Alloc ID = 25939
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 31538;
-- Duplicate entry for Pay Alloc ID = 25958
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 31527;
-- Duplicate entry for Pay Alloc ID = 25959
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 31540;
-- Duplicate entry for Pay Alloc ID = 25962
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 31533;
-- Duplicate entry for Pay Alloc ID = 25976
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 28942;
-- Duplicate entry for Pay Alloc ID = 25977
-- Payment Type = 14
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 31526;
-- Duplicate entry for Pay Alloc ID = 25978
-- Payment Type = 14
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 31534;
-- Duplicate entry for Pay Alloc ID = 25979
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 31545;
-- Duplicate entry for Pay Alloc ID = 25980
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 31537;
-- Duplicate entry for Pay Alloc ID = 25981
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 31529;
-- Duplicate entry for Pay Alloc ID = 25983
-- Payment Type = 7
-- Debit Account = 3075
-- Credit Account = 3079
delete from rnt_ledger_entries where ledger_id = 28748;
-- Duplicate entry for Pay Alloc ID = 25999
-- Payment Type = 9
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 31539;
-- Duplicate entry for Pay Alloc ID = 26097
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 31532;
-- Duplicate entry for Pay Alloc ID = 26137
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 31531;
-- Duplicate entry for Pay Alloc ID = 26216
-- Payment Type = 7
-- Debit Account = 1909
-- Credit Account = 1913
delete from rnt_ledger_entries where ledger_id = 29672;
-- Duplicate entry for Pay Alloc ID = 26218
-- Payment Type = 7
-- Debit Account = 3022
-- Credit Account = 3026
delete from rnt_ledger_entries where ledger_id = 29030;
-- Duplicate entry for Pay Alloc ID = 26316
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 31535;
-- Duplicate entry for Pay Alloc ID = 26336
-- Payment Type = 14
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 31541;
-- Duplicate entry for Pay Alloc ID = 26337
-- Payment Type = 14
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 31543;
-- Duplicate entry for Pay Alloc ID = 26338
-- Payment Type = 14
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 31546;
-- Duplicate entry for Pay Alloc ID = 26396
-- Payment Type = 7
-- Debit Account = 3181
-- Credit Account = 3185
delete from rnt_ledger_entries where ledger_id = 28707;
-- Duplicate entry for Pay Alloc ID = 26496
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 31544;
-- Duplicate entry for Pay Alloc ID = 26537
-- Payment Type = 14
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 31542;
-- Duplicate entry for Pay Alloc ID = 26562
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 31536;
-- Duplicate entry for Pay Alloc ID = 26564
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 30394;
-- Duplicate entry for Pay Alloc ID = 26618
-- Payment Type = 7
-- Debit Account = 213
-- Credit Account = 217
delete from rnt_ledger_entries where ledger_id = 28760;
-- Duplicate entry for Pay Alloc ID = 26677
-- Payment Type = 7
-- Debit Account = 1
-- Credit Account = 5
delete from rnt_ledger_entries where ledger_id = 31528;