declare
  procedure set_zipcode_name( p_name    in varchar2
                            , p_zipcode in number ) is
  begin
    update rnt_zipcodes
    set place_name = p_name
    where zipcode = p_zipcode;
  end set_zipcode_name;

begin
  set_zipcode_name('Altamonte Springs East', 32701);
  set_zipcode_name('Altamonte Springs West/Forest City', 32714);
  set_zipcode_name('Altoona', 32702);
  set_zipcode_name('Alturas', 33820);
  set_zipcode_name('Alva', 33920);
  set_zipcode_name('Anna Maria', 34216);
  set_zipcode_name('Anthony', 32617);
  set_zipcode_name('Apollo Beach', 33572);
  set_zipcode_name('Apopka - South', 32703);
  set_zipcode_name('Apopka - North', 32712);
  set_zipcode_name('Arcadia - North', 34266);
  set_zipcode_name('Arcadia - South', 34269);
  set_zipcode_name('Astatula', 34705);
  set_zipcode_name('Astor', 32102);
  set_zipcode_name('Auburndale', 33823);
  set_zipcode_name('Avon Park', 33825);
  set_zipcode_name('Babson Park', 33827);
  set_zipcode_name('Bartow - Northeast', 33830);
  set_zipcode_name('Bartow - Southwest', 33831);
  set_zipcode_name('Belle Glade', 33430);
  set_zipcode_name('Belleair Beach', 33786);
  set_zipcode_name('Belleview', 34420);
  set_zipcode_name('Boca Grande', 33921);
  set_zipcode_name('Boca Raton - Southwest', 33428);
  set_zipcode_name('Boca Raton - East Central', 33431);
  set_zipcode_name('Boca Raton - Southeast', 33432);
  set_zipcode_name('Boca Raton - Boca Del Mar', 33433);
  set_zipcode_name('Boca Raton - Hamptons at Boca Raton', 33434);
  set_zipcode_name('Boca Raton - East of Boca Del Mar, South of FAU', 33486);
  set_zipcode_name('Boca Raton - Northeast', 33487);
  set_zipcode_name('Boca Raton - North Central', 33496);
  set_zipcode_name('Boca Raton West', 33498);
  set_zipcode_name('Bokeelia', 33922);
  set_zipcode_name('Bonita Springs - West', 34134);
  set_zipcode_name('Bonita Springs - East', 34135);
  set_zipcode_name('Boynton Beach - South of Hypoluxo Rd., West of I95', 33426);
  set_zipcode_name('Boynton Beach - East', 33435);
  set_zipcode_name('Boynton Beach - South of Hypoluxo Rd., West of Congress Ave.', 33436);
  set_zipcode_name('Boynton Beach - South of Stanley Weaver Canal, East of Florida Turnpike', 33437);
  set_zipcode_name('Boynton Beach - Cobblestone Creek', 33472);
  set_zipcode_name('Boynton Beach - South of Boynton Beach Blvd., West of Florida Turnpike', 33473);
  set_zipcode_name('Bradenton Beach', 34217);
  set_zipcode_name('Bradenton', 34201);
  set_zipcode_name('Bradenton - East of I75, South', 34202);
  set_zipcode_name('Bradenton - Southeast', 34203);
  set_zipcode_name('Bradenton - North Central', 34205);
  set_zipcode_name('Bradenton - South Central', 34207);
  set_zipcode_name('Bradenton - Northeast', 34208);
  set_zipcode_name('Bradenton - Northwest', 34209);
  set_zipcode_name('Bradenton - Southwest', 34210);
  set_zipcode_name('Bradenton - East of I75, Central', 34211);
  set_zipcode_name('Bradenton - East of I75, North', 34212);
  set_zipcode_name('Bradley', 33835);
  set_zipcode_name('Brandon - North', 33510);
  set_zipcode_name('Brandon - South', 33511);
  set_zipcode_name('Brooksville - Central', 34601);
  set_zipcode_name('Brooksville - Hill ''N Dale', 34602);
  set_zipcode_name('Brooksville - East of Spring Hills', 34604);
  set_zipcode_name('Brooksville - Spring Hill', 34609);
  set_zipcode_name('Brooksville - Shady Hills', 34610);
  set_zipcode_name('Brooksville - High Point and Brookridge', 34613);
  set_zipcode_name('Brooksville - Annutteliga Hammock and Chassahowitzka NWR', 34614);
  set_zipcode_name('Bushnell', 33513);
  set_zipcode_name('Canal Point', 33438);
  set_zipcode_name('Cape Canaveral', 32920);
  set_zipcode_name('Cape Coral - Southeast', 33904);
  set_zipcode_name('Cape Coral - Northeast', 33909);
  set_zipcode_name('Cape Coral - Southwest', 33914);
  set_zipcode_name('Cape Coral - East Central', 33990);
  set_zipcode_name('Cape Coral - West Central', 33991);
  set_zipcode_name('Cape Coral - Northwest', 33993);
  set_zipcode_name('Captiva', 33924);
  set_zipcode_name('Casselberry - East', 32707);
  set_zipcode_name('Casselberry - West', 32730);
  set_zipcode_name('Center Hill', 33514);
  set_zipcode_name('Christmas', 32709);
  set_zipcode_name('Citra', 32113);
  set_zipcode_name('Clarcona', 32710);
  set_zipcode_name('Clearwater Beach', 33767);
  set_zipcode_name('Clearwater - Old Clearwater Bay and Sunset Lake Estates', 33755);
  set_zipcode_name('Clearwater - Belleair', 33756);
  set_zipcode_name('Clearwater - Northwood', 33759);
  set_zipcode_name('Clearwater - Highpoint', 33760);
  set_zipcode_name('Clearwater - Countryside', 33761);
  set_zipcode_name('Clearwater - Feather Sound and Chateau Bayonne', 33762);
  set_zipcode_name('Clearwater - Spring Lake South and Hillcrest Villas', 33763);
  set_zipcode_name('Clearwater - Seville and Imperial Cove', 33764);
  set_zipcode_name('Clearwater - Woodlake', 33765);
  set_zipcode_name('Clermont - Central', 34711);
  set_zipcode_name('Clermont - South', 34714);
  set_zipcode_name('Clermont - North', 34715);
  set_zipcode_name('Cocoa Beach', 32931);
  set_zipcode_name('Cocoa - Cocoa Village', 32922);
  set_zipcode_name('Cocoa - Canaveral Groves', 32926);
  set_zipcode_name('Cocoa - North', 32927);
  set_zipcode_name('Coleman', 33521);
  set_zipcode_name('Cortez', 34215);
  set_zipcode_name('Crystal Beach', 34681);
  set_zipcode_name('Dade City - North', 33523);
  set_zipcode_name('Dade City - South', 33525);
  set_zipcode_name('Dade City - Central', 33526);
  set_zipcode_name('Dania', 33004);
  set_zipcode_name('Davenport - South', 33836);
  set_zipcode_name('Davenport - South', 33837);
  set_zipcode_name('Davenport - Central', 33896);
  set_zipcode_name('Davenport - North', 33897);
  set_zipcode_name('Daytona Beach - Central', 32114);
  set_zipcode_name('Daytona Beach - Holly Hill', 32117);
  set_zipcode_name('Daytona Beach - Daytona Beach Shores', 32118);
  set_zipcode_name('Daytona Beach - South Daytona', 32119);
  set_zipcode_name('Daytona Beach - Central', 32120);
  set_zipcode_name('Daytona Beach - West', 32124);
  set_zipcode_name('Daytona Beach - Port Orange', 32127);
  set_zipcode_name('Daytona Beach - Southwest', 32128);
  set_zipcode_name('De Leon Springs', 32130);
  set_zipcode_name('Debary', 32713);
  set_zipcode_name('Deerfield Beach - East', 33441);
  set_zipcode_name('Deerfield Beach - West', 33442);
  set_zipcode_name('Deland - West', 32720);
  set_zipcode_name('Deland - East', 32724);
  set_zipcode_name('Delray Beach - East of I95', 33444);
  set_zipcode_name('Delray Beach - West of I95', 33445);
  set_zipcode_name('Delray Beach - West', 33446);
  set_zipcode_name('Delray Beach - Gulf Stream', 33483);
  set_zipcode_name('Delray Beach - High Point', 33484);
  set_zipcode_name('Deltona - West', 32725);
  set_zipcode_name('Deltona - East/Deltona Lakes', 32738);
  set_zipcode_name('Dover', 33527);
  set_zipcode_name('Dundee', 33838);
  set_zipcode_name('Dunedin', 34698);
  set_zipcode_name('Dunnellon - West', 34431);
  set_zipcode_name('Dunnellon - East', 34432);
  set_zipcode_name('Eagle Lake', 33839);
  set_zipcode_name('Eastlake Weir', 32133);
  set_zipcode_name('Eaton Park', 33840);
  set_zipcode_name('Edgewater - North', 32132);
  set_zipcode_name('Edgewater - South', 32141);
  set_zipcode_name('Ellenton', 34222);
  set_zipcode_name('Englewood - North', 34223);
  set_zipcode_name('Englewood - South', 34224);
  set_zipcode_name('Estero', 33928);
  set_zipcode_name('Eustis - Central', 32726);
  set_zipcode_name('Eustis - West', 32727);
  set_zipcode_name('Eustis - East', 32736);
  set_zipcode_name('Fedhaven', 33854);
  set_zipcode_name('Ferndale', 34729);
  set_zipcode_name('Fort Lauderdale - East Fort Lauderdale', 33301);
  set_zipcode_name('Fort Lauderdale - Lake Ridge', 33304);
  set_zipcode_name('Fort Lauderdale - Dolphin Isles', 33305);
  set_zipcode_name('Fort Lauderdale - Coral Shores', 33306);
  set_zipcode_name('Fort Lauderdale - Imperial Point and Lauderdale by the Sea', 33308);
  set_zipcode_name('Fort Lauderdale - North Fort Lauderdale', 33309);
  set_zipcode_name('Fort Lauderdale - Central Fort Lauderdale and Roosevelt Gardens', 33311);
  set_zipcode_name('Fort Lauderdale - South Fort Lauderdale', 33312);
  set_zipcode_name('Fort Lauderdale Lauderhill', 33313);
  set_zipcode_name('Fort Lauderdale - South of Port Everglades Expy., East of Davie', 33314);
  set_zipcode_name('Fort Lauderdale - East of South Fort Lauderdale', 33315);
  set_zipcode_name('Fort Lauderdale', 33316);
  set_zipcode_name('Fort Lauderdale - Plantation', 33317);
  set_zipcode_name('Fort Lauderdale - Inverrary and Lauderdale Lakes', 33319);
  set_zipcode_name('Fort Lauderdale - Everglades Wildlife Management Area', 33321);
  set_zipcode_name('Fort Lauderdale - South of Sunrise', 33322);
  set_zipcode_name('Fort Lauderdale - Southeast of Water Conservation Area 2B', 33323);
  set_zipcode_name('Fort Lauderdale - Pine Island Ridge', 33324);
  set_zipcode_name('Fort Lauderdale - West of Pine Island Ridge', 33325);
  set_zipcode_name('Fort Lauderdale - Weston East', 33326);
  set_zipcode_name('Fort Lauderdale - Weston West', 33327);
  set_zipcode_name('Fort Lauderdale - Cooper City', 33328);
  set_zipcode_name('Fort Lauderdale - Southwest Ranches', 33330);
  set_zipcode_name('Fort Lauderdale - West of Southwest Ranches', 33331);
  set_zipcode_name('Fort Lauderdale - Everglades', 33332);
  set_zipcode_name('Fort Lauderdale - North Andrews Gardens and Oakland Park', 33334);
  set_zipcode_name('Fort Lauderdale - Sunrise', 33351);
  set_zipcode_name('Fort Mc Coy', 32134);
  set_zipcode_name('Fort Meade', 33841);
  set_zipcode_name('Fort Myers Beach', 33931);
  set_zipcode_name('Fort Myers - Central', 33901);
  set_zipcode_name('Fort Myers - Fort Myers Shores', 33905);
  set_zipcode_name('Fort Myers - Pine Manor and Page Park', 33907);
  set_zipcode_name('Fort Myers - North of Rocky Bay and San Carlos Bay', 33908);
  set_zipcode_name('Fort Myers - Villas', 33912);
  set_zipcode_name('Fort Myers - North of Corkscrew Rd., East of I75', 33913);
  set_zipcode_name('Fort Myers - South of Caloosahatchee River, East of Evans Ave.', 33916);
  set_zipcode_name('Fort Myers - Whiskey Creek and Cypress Lake', 33919);
  set_zipcode_name('Fort Myers - East of Page Park', 33966);
  set_zipcode_name('Fort Myers - San Carlos Park', 33967);
  set_zipcode_name('Frostproof', 33843);
  set_zipcode_name('Fruitland Park', 34731);
  set_zipcode_name('Gainesville', 32612);
  set_zipcode_name('Geneva', 32732);
  set_zipcode_name('Gibsonton', 33534);
  set_zipcode_name('Gotha', 34734);
  set_zipcode_name('Grand Island', 32735);
  set_zipcode_name('Grant', 32949);
  set_zipcode_name('Groveland', 34736);
  set_zipcode_name('Haines City', 33844);
  set_zipcode_name('Haines City - Lake Hamilton', 33845);
  set_zipcode_name('Hallandale - South', 33008);
  set_zipcode_name('Hallandale - North', 33009);
  set_zipcode_name('Hialeah - South', 33010);
  set_zipcode_name('Hialeah - Central', 33012);
  set_zipcode_name('Hialeah - East', 33013);
  set_zipcode_name('Hialeah - Miami Lakes', 33014);
  set_zipcode_name('Hialeah - Country Club', 33015);
  set_zipcode_name('Hialeah - Hialeah Gardens', 33016);
  set_zipcode_name('Hialeah - West', 33018);
  set_zipcode_name('Highland City', 33846);
  set_zipcode_name('Holiday - East', 34690);
  set_zipcode_name('Holiday - West', 34691);
  set_zipcode_name('Hollywood - Hollywood Lakes', 33019);
  set_zipcode_name('Hollywood - Parkside', 33020);
  set_zipcode_name('Hollywood - Hillcrest', 33021);
  set_zipcode_name('Hollywood - West Park', 33023);
  set_zipcode_name('Hollywood - Driftwood', 33024);
  set_zipcode_name('Hollywood - Miramar East', 33025);
  set_zipcode_name('Hollywood - Pembroke Pines', 33026);
  set_zipcode_name('Hollywood - Miramar West', 33027);
  set_zipcode_name('Hollywood - South of Sheridan St., East of 172nd Ave.', 33028);
  set_zipcode_name('Hollywood - Silverlakes', 33029);
  set_zipcode_name('Homeland', 33847);
  set_zipcode_name('Homestead - Southwest', 33030);
  set_zipcode_name('Homestead - Northwest', 33031);
  set_zipcode_name('Homestead - Northeast', 33032);
  set_zipcode_name('Homestead - Leisure City', 33033);
  set_zipcode_name('Homestead - Everglades', 33034);
  set_zipcode_name('Homestead - South', 33035);
  set_zipcode_name('Howey In The Hills', 34737);
  set_zipcode_name('Hudson - West', 34667);
  set_zipcode_name('Hudson - East', 34669);
  set_zipcode_name('Indialantic', 32903);
  set_zipcode_name('Indian Lake Estates', 33855);
  set_zipcode_name('Indian Rocks Beach', 33785);
  set_zipcode_name('Intercession City', 33848);
  set_zipcode_name('Jupiter - Central', 33458);
  set_zipcode_name('Jupiter - Northeast', 33469);
  set_zipcode_name('Jupiter - Southeast', 33477);
  set_zipcode_name('Jupiter - West', 33478);
  set_zipcode_name('Kathleen', 33849);
  set_zipcode_name('Kenansville', 34739);
  set_zipcode_name('Key Biscayne', 33149);
  set_zipcode_name('Kissimmee - North', 34741);
  set_zipcode_name('Kissimmee - Buena Ventura Lakes', 34743);
  set_zipcode_name('Kissimmee - Northeast', 34744);
  set_zipcode_name('Kissimmee - Central', 34746);
  set_zipcode_name('Kissimmee - Northwest', 34747);
  set_zipcode_name('Kissimmee - West Central', 34758);
  set_zipcode_name('Kissimmee - South', 34759);
  set_zipcode_name('Lady Lake - East', 32159);
  set_zipcode_name('Lady Lake - West', 32162);
  set_zipcode_name('Lake Alfred', 33850);
  set_zipcode_name('Lake Hamilton', 33851);
  set_zipcode_name('Lake Helen', 32744);
  set_zipcode_name('Lake Mary', 32746);
  set_zipcode_name('Lake Monroe', 32747);
  set_zipcode_name('Lake Panasoffkee', 33538);
  set_zipcode_name('Lake Placid', 33852);
  set_zipcode_name('Lake Wales - Central', 33853);
  set_zipcode_name('Lake Wales - West', 33859);
  set_zipcode_name('Lake Wales - East', 33898);
  set_zipcode_name('Lake Worth - West', 33449);
  set_zipcode_name('Lake Worth - East', 33460);
  set_zipcode_name('Lake Worth - Lake Worth Corridor and Palm Springs', 33461);
  set_zipcode_name('Lake Worth - Atlantis and Lantana', 33462);
  set_zipcode_name('Lake Worth - Greenacres', 33463);
  set_zipcode_name('Lake Worth - East of 441, South of Arrowhead Dr.', 33467);
  set_zipcode_name('Lakeland - Combee Settlement and Crystal Lake', 33801);
  set_zipcode_name('Lakeland - South of Lake Morton', 33802);
  set_zipcode_name('Lakeland - Lake Somerset', 33803);
  set_zipcode_name('Lakeland - Lake Somerset', 33804);
  set_zipcode_name('Lakeland - South of 400, West of 570', 33805);
  set_zipcode_name('Lakeland - North of Lakeland Highlands', 33807);
  set_zipcode_name('Lakeland - Lake Gibson', 33809);
  set_zipcode_name('Lakeland - North of 400, West of 700', 33810);
  set_zipcode_name('Lakeland - North of Shepherd Rd., East of County Line Rd.', 33811);
  set_zipcode_name('Lakeland - Banana Lake', 33812);
  set_zipcode_name('Lakeland - Lakeland Highlands', 33813);
  set_zipcode_name('Lakeland - Winston', 33815);
  set_zipcode_name('Land O Lakes - North', 34637);
  set_zipcode_name('Land O Lakes - West', 34638);
  set_zipcode_name('Land O Lakes - East', 34639);
  set_zipcode_name('Largo - Northwest', 33770);
  set_zipcode_name('Largo - Northeast', 33771);
  set_zipcode_name('Largo - Southeast', 33773);
  set_zipcode_name('Largo - Southwest', 33774);
  set_zipcode_name('Largo - South Central', 33778);
  set_zipcode_name('Leesburg - South', 34748);
  set_zipcode_name('Leesburg - North', 34788);
  set_zipcode_name('Lehigh Acres - Central', 33936);
  set_zipcode_name('Lehigh Acres - Northwest', 33971);
  set_zipcode_name('Lehigh Acres - Northeast', 33972);
  set_zipcode_name('Lehigh Acres - Westminister', 33973);
  set_zipcode_name('Lehigh Acres - Southeast', 33974);
  set_zipcode_name('Lehigh Acres - Southwest', 33976);
  set_zipcode_name('Lithia', 33547);
  set_zipcode_name('Longboat Key', 34228);
  set_zipcode_name('Longwood - East', 32750);
  set_zipcode_name('Longwood - West', 32779);
  set_zipcode_name('Loughman', 33858);
  set_zipcode_name('Loxahatchee', 33470);
  set_zipcode_name('Lutz - West Central', 33548);
  set_zipcode_name('Lutz - East Central', 33549);
  set_zipcode_name('Lutz - West', 33558);
  set_zipcode_name('Lutz - East', 33559);
  set_zipcode_name('Maitland', 32751);
  set_zipcode_name('Malabar', 32950);
  set_zipcode_name('Mascotte', 34753);
  set_zipcode_name('Melbourne Beach', 32951);
  set_zipcode_name('Melbourne - Southeast', 32901);
  set_zipcode_name('Melbourne - West', 32904);
  set_zipcode_name('Melbourne - Central', 32934);
  set_zipcode_name('Melbourne - East', 32935);
  set_zipcode_name('Melbourne - North', 32940);
  set_zipcode_name('Merritt Island - South', 32952);
  set_zipcode_name('Merritt Island - North', 32953);
  set_zipcode_name('Miami Beach - Fisher Island', 33109);
  set_zipcode_name('Miami Beach - South Beach', 33139);
  set_zipcode_name('Miami Beach - Mid-Beach', 33140);
  set_zipcode_name('Miami Beach - North Beach', 33141);
  set_zipcode_name('Miami - Doral', 33122);
  set_zipcode_name('Miami - NW North of Flagler, West of 12th', 33125);
  set_zipcode_name('Miami - NW North of Flagler, West of 37th', 33126);
  set_zipcode_name('Miami - NW North of 20 St., West of Miami Ave.', 33127);
  set_zipcode_name('Miami - Downtown Miami North' , 33128);
  set_zipcode_name('Miami - Brickell', 33129);
  set_zipcode_name('Miami - Downtown Miami West', 33130);
  set_zipcode_name('Miami - Downtown Miami East', 33131);
  set_zipcode_name('Miami - Ne North of Flagler St., East of Miami Ave.', 33132);
  set_zipcode_name('Miami - Coconut Grove', 33133);
  set_zipcode_name('Miami - Coral Gables/SW South of Flagler, West of Douglas.', 33134);
  set_zipcode_name('Miami - SW South of Flagler, West of 12th', 33135);
  set_zipcode_name('Miami - NW North of 5th St., West of Miami Ave.', 33136);
  set_zipcode_name('Miami - NE North of 20th St., East of Miami Ave.', 33137);
  set_zipcode_name('Miami - NE North of 62nd St., East of Miami Ave.', 33138);
  set_zipcode_name('Miami - NW North of 62nd St., West of Miami Ave.', 33142);
  set_zipcode_name('Miami - SW South of Coral Gables, West of 57th', 33143);
  set_zipcode_name('Miami - SW South of Flagler West of 57', 33144);
  set_zipcode_name('Miami - SW South of 13th, West of 12th', 33145);
  set_zipcode_name('Miami - Coral Gables', 33146);
  set_zipcode_name('Miami - NW North of 62nd, West of 12th', 33147);
  set_zipcode_name('Miami - NW North of 62nd St., West of Miami Ave.', 33150);
  set_zipcode_name('Miami - Surfside', 33154);
  set_zipcode_name('Miami - SW South of 16th, West of 57th', 33155);
  set_zipcode_name('Miami - Pinecrest', 33156);
  set_zipcode_name('Miami - SW South of 152nd, West of Biscayne Bay', 33157);
  set_zipcode_name('Miami - SW South of 136th, West of Biscayne Bay', 33158);
  set_zipcode_name('Miami - NE North of 107th St., East of Miami Ave.', 33161);
  set_zipcode_name('Miami - NE North of 151st St., East of Miami Ave.', 33162);
  set_zipcode_name('Miami - SW South of 16th, West of 87th', 33165);
  set_zipcode_name('Miami - NW North of 36th St., Southwest of Okeechobee Rd', 33166);
  set_zipcode_name('Miami - Westview', 33167);
  set_zipcode_name('Miami - NW North of 107th St., West of Miami Ave.', 33168);
  set_zipcode_name('Miami - NW North of 151st St. West of Miami Ave.', 33169);
  set_zipcode_name('Miami - SW South of 216th, West of 107th', 33170);
  set_zipcode_name('Miami - NW North of Flagler, West of 87th', 33172);
  set_zipcode_name('Miami - SW South of 56th, West of 87th', 33173);
  set_zipcode_name('Miami - SW South of Flagler, West of 87th', 33174);
  set_zipcode_name('Miami - SW South of 16th, West of 117th', 33175);
  set_zipcode_name('Miami - SW South of 88th, West of 87th', 33176);
  set_zipcode_name('Miami - SW South of 152nd, West of 117th', 33177);
  set_zipcode_name('Miami - NW North of 36th, West of 87th', 33178);
  set_zipcode_name('Miami - NE North of 183rd St., East of Miami Ave.', 33179);
  set_zipcode_name('Miami - Aventura', 33180);
  set_zipcode_name('Miami - North Miami', 33181);
  set_zipcode_name('Miami - NW North of Flagler, West of 117th', 33182);
  set_zipcode_name('Miami - Kendale Lakes', 33183);
  set_zipcode_name('Miami - SW South of Flagler, West of 117th', 33184);
  set_zipcode_name('Miami - SW South of 16th, West of 147th', 33185);
  set_zipcode_name('Miami - SW South of 88th, West of 117th', 33186);
  set_zipcode_name('Miami - SW South of 152nd, West of 147th', 33187);
  set_zipcode_name('Miami - Cutler Bay ', 33189);
  set_zipcode_name('Miami - SW South of 216th, West of Biscayne Bay', 33190);
  set_zipcode_name('Miami - SW South of 56th, West of 147th', 33193);
  set_zipcode_name('Miami - SW South of Flagler, West of 147th', 33194);
  set_zipcode_name('Miami - SW South of 88th, West of 147th', 33196);
  set_zipcode_name('Micanopy', 32667);
  set_zipcode_name('Mims', 32754);
  set_zipcode_name('Montverde', 34756);
  set_zipcode_name('Mount Dora - North', 32756);
  set_zipcode_name('Mount Dora - South', 32757);
  set_zipcode_name('Mulberry', 33860);
  set_zipcode_name('Myakka City', 34251);
  set_zipcode_name('New Port Richey - West', 34652);
  set_zipcode_name('New Port Richey - East', 34653);
  set_zipcode_name('New Port Richey - North', 34654);
  set_zipcode_name('New Port Richey - South', 34655);
  set_zipcode_name('New Smyrna Beach - West', 32168);
  set_zipcode_name('New Smyrna Beach - East', 32169);
  set_zipcode_name('Nichols', 33863);
  set_zipcode_name('Nobleton', 34661);
  set_zipcode_name('Nokomis', 34275);
  set_zipcode_name('North Fort Myers - West', 33903);
  set_zipcode_name('North Fort Myers - East', 33917);
  set_zipcode_name('North Miami Beach', 33160);
  set_zipcode_name('North Palm Beach', 33408);
  set_zipcode_name('North Port - Central', 34286);
  set_zipcode_name('North Port - Southwest', 34287);
  set_zipcode_name('North Port - Southeast', 34288);
  set_zipcode_name('North Port - Northeast', 34289);
  set_zipcode_name('North Port - Northwest', 34291);
  set_zipcode_name('Oak Hill', 32759);
  set_zipcode_name('Oakland', 34760);
  set_zipcode_name('Ocala - South of Silver Springs State Park', 34470);
  set_zipcode_name('Ocala - East Central', 34471);
  set_zipcode_name('Ocala - East', 34472);
  set_zipcode_name('Ocala - South', 34473);
  set_zipcode_name('Ocala - North Central', 34474);
  set_zipcode_name('Ocala - North', 34475);
  set_zipcode_name('Ocala - South Central', 34476);
  set_zipcode_name('Ocala - Northeast', 34479);
  set_zipcode_name('Ocala - Southeast', 34480);
  set_zipcode_name('Ocala - Southwest', 34481);
  set_zipcode_name('Ocala - Northwest', 34482);
  set_zipcode_name('Ocklawaha', 32179);
  set_zipcode_name('Ocoee', 34761);
  set_zipcode_name('Odessa', 33556);
  set_zipcode_name('Okahumpka', 34762);
  set_zipcode_name('Oldsmar', 34677);
  set_zipcode_name('Opa Locka - South', 33054);
  set_zipcode_name('Opa Locka - West', 33055);
  set_zipcode_name('Opa Locka - Miami Gardens', 33056);
  set_zipcode_name('Orange City', 32763);
  set_zipcode_name('Orlando (Baldwin Park)', 32814);
  set_zipcode_name('Orlando (Downtown and Thornton Park)', 32801);
  set_zipcode_name('Orlando Alafaya', 32826);
  set_zipcode_name('Orlando', 32816);
  set_zipcode_name('Orlando', 32830);
  set_zipcode_name('Orlando', 32853);
  set_zipcode_name('Orlando', 32897);
  set_zipcode_name('Orlando/Airport/Alafaya/Lake Nona', 32827);
  set_zipcode_name('Orlando/Alafaya/Waterford Lakes', 32828);
  set_zipcode_name('Orlando/Azalea Park/Park Manor', 32807);
  set_zipcode_name('Orlando/Bay Hill/Sand Lake', 32819);
  set_zipcode_name('Orlando/Bithlo', 32820);
  set_zipcode_name('Orlando/Chickasaw', 32829);
  set_zipcode_name('Orlando/College Park', 32804);
  set_zipcode_name('Orlando/Colonial Town', 32803);
  set_zipcode_name('Orlando/Conway/Belle Isle', 32812);
  set_zipcode_name('Orlando/Delaney Park/Crystal Lake', 32806);
  set_zipcode_name('Orlando/Dr. Phillips/Bay Vista', 32836);
  set_zipcode_name('Orlando/Edgewood/Pinecastle', 32839);
  set_zipcode_name('Orlando/Hiawassee/Pine Hills', 32818);
  set_zipcode_name('Orlando/Hunters Creek/Southchase', 32837);
  set_zipcode_name('Orlando/International Drive', 32821);
  set_zipcode_name('Orlando/Lockhard', 32810);
  set_zipcode_name('Orlando/MetroWest/Orlo Vista', 32835);
  set_zipcode_name('Orlando/Moss Park/Lake Mary Jane', 32832);
  set_zipcode_name('Orlando/Orlo Vista/Richmond Heights', 32811);
  set_zipcode_name('Orlando/Pine Hills', 32808);
  set_zipcode_name('Orlando/Pinecastle/Oakridge/Edgewood', 32809);
  set_zipcode_name('Orlando/Rio Pinar/Union Park', 32825);
  set_zipcode_name('Orlando/Taft/ Meadow Woods', 32824);
  set_zipcode_name('Orlando/Union Park/University Area', 32817);
  set_zipcode_name('Orlando/Ventura', 32822);
  set_zipcode_name('Orlando/Washintong Shores', 32805);
  set_zipcode_name('Orlando/Wedgefield/Rocket City/Cape Orlando', 32833);
  set_zipcode_name('Ormond Beach - West', 32174);
  set_zipcode_name('Ormond Beach - East', 32176);
  set_zipcode_name('Osprey', 34229);
  set_zipcode_name('Osteen', 32764);
  set_zipcode_name('Oviedo - West', 32765);
  set_zipcode_name('Oviedo - East', 32766);
  set_zipcode_name('Oxford', 34484);
  set_zipcode_name('Pahokee', 33476);
  set_zipcode_name('Paisley', 32767);
  set_zipcode_name('Palm Bay - Northeast', 32905);
  set_zipcode_name('Palm Bay - North', 32907);
  set_zipcode_name('Palm Bay - Central', 32908);
  set_zipcode_name('Palm Bay - South', 32909);
  set_zipcode_name('Palm Beach', 33480);
  set_zipcode_name('Palm Harbor - West', 34683);
  set_zipcode_name('Palm Harbor - Central', 34684);
  set_zipcode_name('Palm Harbor - East', 34685);
  set_zipcode_name('Palmetto', 34221);
  set_zipcode_name('Parrish', 34219);
  set_zipcode_name('Pierson', 32180);
  set_zipcode_name('Pinellas Park - South', 33781);
  set_zipcode_name('Pinellas Park - North', 33782);
  set_zipcode_name('Placida', 33946);
  set_zipcode_name('Plant City - Central', 33563);
  set_zipcode_name('Plant City - North', 33565);
  set_zipcode_name('Plant City - South Central', 33566);
  set_zipcode_name('Plant City - South', 33567);
  set_zipcode_name('Polk City', 33868);
  set_zipcode_name('Pompano Beach - West of Federal Hwy.', 33060);
  set_zipcode_name('Pompano Beach - East of Federal Hwy.', 33062);
  set_zipcode_name('Pompano Beach - Margate', 33063);
  set_zipcode_name('Pompano Beach - Pompano Beach Highlands', 33064);
  set_zipcode_name('Pompano Beach - Coral Springs', 33065);
  set_zipcode_name('Pompano Beach - Coconut Creek', 33066);
  set_zipcode_name('Pompano Beach - Pompano Beach West of 441', 33067);
  set_zipcode_name('Pompano Beach - North Lauderdale', 33068);
  set_zipcode_name('Pompano Beach - West of I95', 33069);
  set_zipcode_name('Pompano Beach - West of Margate, South of Coral Springs', 33071);
  set_zipcode_name('Pompano Beach - Hillsboro Pines', 33073);
  set_zipcode_name('Pompano Beach - North of Coral Springs', 33076);
  set_zipcode_name('Port Charlotte - Between Tippecanoe Bay and Alligator Bay', 33948);
  set_zipcode_name('Port Charlotte - North of Alligator Bay', 33952);
  set_zipcode_name('Port Charlotte - Northwest of Myakka River', 33953);
  set_zipcode_name('Port Charlotte - South of Hillsborough Blvd., East of I75', 33954);
  set_zipcode_name('Port Charlotte - Charlotte Harbor', 33980);
  set_zipcode_name('Port Charlotte - West of Myakka River/Charlotte Harbor', 33981);
  set_zipcode_name('Port Orange', 32129);
  set_zipcode_name('Port Richey - North', 34668);
  set_zipcode_name('Port Richey - South', 34673);
  set_zipcode_name('Punta Gorda - South of Peace River', 33950);
  set_zipcode_name('Punta Gorda - Between Charlotte Harbor and I75', 33955);
  set_zipcode_name('Punta Gorda - Cecil M Webb State Wildlife Management Area', 33982);
  set_zipcode_name('Punta Gorda - North of Peace River, East of I75', 33983);
  set_zipcode_name('Riverview - Boyette', 33569);
  set_zipcode_name('Riverview - Northwest', 33578);
  set_zipcode_name('Riverview - Southeast', 33579);
  set_zipcode_name('Rockledge', 32955);
  set_zipcode_name('Rotonda West', 33947);
  set_zipcode_name('Ruskin', 33570);
  set_zipcode_name('Safety Harbor', 34695);
  set_zipcode_name('Saint Cloud - South of East Lake Tohopekalia', 34769);
  set_zipcode_name('Saint Cloud - East of East Lake Tohopekalia', 34771);
  set_zipcode_name('Saint Cloud - South', 34772);
  set_zipcode_name('Saint Cloud - East', 34773);
  set_zipcode_name('Saint James City', 33956);
  set_zipcode_name('Saint Petersburg - East Central', 33701);
  set_zipcode_name('Saint Petersburg - Riviera Bay/Gandy', 33702);
  set_zipcode_name('Saint Petersburg - North of Snell Isle', 33703);
  set_zipcode_name('Saint Petersburg - Crescent Heights and Snell Isle', 33704);
  set_zipcode_name('Saint Petersburg - Greater Pinellas Point East', 33705);
  set_zipcode_name('Saint Petersburg - Barrier Islands West of Boca Ciega Bay', 33706);
  set_zipcode_name('Saint Petersburg - Pasadena', 33707);
  set_zipcode_name('Saint Petersburg - Bay Pines', 33708);
  set_zipcode_name('Saint Petersburg - Kenneth City', 33709);
  set_zipcode_name('Saint Petersburg - Jungle Terrace', 33710);
  set_zipcode_name('Saint Petersburg - Childs Park', 33711);
  set_zipcode_name('Saint Petersburg - Greater Pinellas Point West', 33712);
  set_zipcode_name('Saint Petersburg - Disston Heights', 33713);
  set_zipcode_name('Saint Petersburg - Lealman', 33714);
  set_zipcode_name('Saint Petersburg - Islands in Tampa Bay', 33715);
  set_zipcode_name('Saint Petersburg - North of Gandy Blvd.', 33716);
  set_zipcode_name('San Antonio', 33576);
  set_zipcode_name('Sanford - West', 32771);
  set_zipcode_name('Sanford - South of Lake Monroe', 32772);
  set_zipcode_name('Sanford - North of Lake Jesup', 32773);
  set_zipcode_name('Sanibel', 33957);
  set_zipcode_name('Sarasota - South Sarasota', 34231);
  set_zipcode_name('Sarasota - Fruitville and Sarasota Springs', 34232);
  set_zipcode_name('Sarasota - Bee Ridge', 34233);
  set_zipcode_name('Sarasota - North Sarasota', 34234);
  set_zipcode_name('Sarasota - Desoto Lakes and The Meadows', 34235);
  set_zipcode_name('Sarasota - West', 34236);
  set_zipcode_name('Sarasota - East of 301, South of 17th', 34237);
  set_zipcode_name('Sarasota - West of I75, South of Clark Rd.', 34238);
  set_zipcode_name('Sarasota - Bayview and Southgate', 34239);
  set_zipcode_name('Sarasota - East of I75, South of University Pkwy', 34240);
  set_zipcode_name('Sarasota - Lake Sarasota', 34241);
  set_zipcode_name('Sarasota - Siesta Key', 34242);
  set_zipcode_name('Sarasota - Whitfield', 34243);
  set_zipcode_name('Satellite Beach', 32937);
  set_zipcode_name('Sebastian', 32976);
  set_zipcode_name('Sebring - West', 33870);
  set_zipcode_name('Sebring - East', 33872);
  set_zipcode_name('Seffner', 33584);
  set_zipcode_name('Seminole - Central', 33772);
  set_zipcode_name('Seminole - West', 33776);
  set_zipcode_name('Seminole - East', 33777);
  set_zipcode_name('Seville', 32190);
  set_zipcode_name('Silver Springs', 34488);
  set_zipcode_name('Sorrento', 32776);
  set_zipcode_name('South Bay', 33493);
  set_zipcode_name('Spring Hill - Timber Pines', 34606);
  set_zipcode_name('Spring Hill - Hernando Beach', 34607);
  set_zipcode_name('Spring Hill - East', 34608);
  set_zipcode_name('Summerfield', 34491);
  set_zipcode_name('Sumterville', 33585);
  set_zipcode_name('Sun City Center', 33573);
  set_zipcode_name('Tampa - Tampa Heights', 33602);
  set_zipcode_name('Tampa - Wellswood', 33603);
  set_zipcode_name('Tampa - Old Seminole Heights and Lowry Park North', 33604);
  set_zipcode_name('Tampa - East Ybor', 33605);
  set_zipcode_name('Tampa - Hyde Park', 33606);
  set_zipcode_name('Tampa - Northwest Tampa', 33607);
  set_zipcode_name('Tampa - Bon Air and Beach Park', 33609);
  set_zipcode_name('Tampa - Northview Hills and Live Oaks Square', 33610);
  set_zipcode_name('Tampa - Ballast Point and Bayshore Beautiful', 33611);
  set_zipcode_name('Tampa - North Tampa', 33612);
  set_zipcode_name('Tampa - Lake Magdalene', 33613);
  set_zipcode_name('Tampa - Egypt Lake-Leto and Drew Park', 33614);
  set_zipcode_name('Tampa - Town ''n'' Country', 33615);
  set_zipcode_name('Tampa - South Tampa', 33616);
  set_zipcode_name('Tampa - Temple Terrace', 33617);
  set_zipcode_name('Tampa - Carrollwood', 33618);
  set_zipcode_name('Tampa - Palm River', 33619);
  set_zipcode_name('Tampa - West of Carrollwood', 33624);
  set_zipcode_name('Tampa - Citrus Park', 33625);
  set_zipcode_name('Tampa - Westchase', 33626);
  set_zipcode_name('Tampa - Virginia Park and Palma Ceia', 33629);
  set_zipcode_name('Tampa - East Town ''n'' Country', 33634);
  set_zipcode_name('Tampa - East of Temple Terrace', 33637);
  set_zipcode_name('Tampa - New Tampa', 33647);
  set_zipcode_name('Tarpon Springs - East', 34688);
  set_zipcode_name('Tarpon Springs - West', 34689);
  set_zipcode_name('Tavares', 32778);
  set_zipcode_name('Terra Ceia', 34250);
  set_zipcode_name('The Villages', 32163);
  set_zipcode_name('Thonotosassa', 33592);
  set_zipcode_name('Titusville - South', 32780);
  set_zipcode_name('Titusville - North', 32796);
  set_zipcode_name('Umatilla', 32784);
  set_zipcode_name('Valrico - North', 33594);
  set_zipcode_name('Valrico - South', 33596);
  set_zipcode_name('Venice - West', 34285);
  set_zipcode_name('Venice - East', 34292);
  set_zipcode_name('Venice - Venice Gardens', 34293);
  set_zipcode_name('Waverly', 33877);
  set_zipcode_name('Webster', 33597);
  set_zipcode_name('Weirsdale', 32195);
  set_zipcode_name('Wesley Chapel', 33545);
  set_zipcode_name('West Palm Beach - Central', 33401);
  set_zipcode_name('West Palm Beach - Lake Park', 33403);
  set_zipcode_name('West Palm Beach - Riviera Beach', 33404);
  set_zipcode_name('West Palm Beach - West of Lake Worth Lagoon, South of Belvedere Rd.', 33405);
  set_zipcode_name('West Palm Beach - Gun Club Estates and Lake Clarke Shores', 33406);
  set_zipcode_name('West Palm Beach - Magnolia Park', 33407);
  set_zipcode_name('West Palm Beach - Villages of Palm Beach Lakes and Westgate', 33409);
  set_zipcode_name('West Palm Beach - West of Lake Worth Creek, South of Donald Ross Rd.', 33410);
  set_zipcode_name('West Palm Beach - Royal Palm Beach', 33411);
  set_zipcode_name('West Palm Beach - Southwest of Palm Beach Gardens', 33412);
  set_zipcode_name('West Palm Beach - Lake Belvedere Estates', 33413);
  set_zipcode_name('West Palm Beach - Wellington', 33414);
  set_zipcode_name('West Palm Beach - Royal Palm Estates', 33415);
  set_zipcode_name('West Palm Beach - Cypress Lakes and Century Village', 33417);
  set_zipcode_name('West Palm Beach - Palm Beach Gardens', 33418);
  set_zipcode_name('Wildwood', 34785);
  set_zipcode_name('Wimauma', 33598);
  set_zipcode_name('Windermere', 34786);
  set_zipcode_name('Winter Garden', 34787);
  set_zipcode_name('Winter Haven - West', 33880);
  set_zipcode_name('Winter Haven - North', 33881);
  set_zipcode_name('Winter Haven - Central', 33882);
  set_zipcode_name('Winter Haven - Central', 33883);
  set_zipcode_name('Winter Haven - Southeast', 33884);
  set_zipcode_name('Winter Haven - Cypress Gardens', 33885);
  set_zipcode_name('Winter Haven - Central', 33888);
  set_zipcode_name('Winter Park - West', 32789);
  set_zipcode_name('Winter Park - East', 32792);
  set_zipcode_name('Winter Springs - East', 32708);
  set_zipcode_name('Winter Springs - West', 32719);
  set_zipcode_name('Yalaha', 34797);
  set_zipcode_name('Zellwood', 32798);
  set_zipcode_name('Zephyrhills - Central', 33539);
  set_zipcode_name('Zephyrhills - East', 33540);
  set_zipcode_name('Zephyrhills - West', 33541);
  set_zipcode_name('Zephyrhills - Central', 33542);
  set_zipcode_name('Zephyrhills - Wesley Chapel East', 33543);
  set_zipcode_name('Zephyrhills - Wesley Chapel West', 33544);


end;
/
