ALTER TABLE RNT_EXPENSE_ITEMS
 ADD (ORDER_ROW  NUMBER);

CREATE OR REPLACE VIEW RNT_EXPENSE_ITEMS_V
(EXPENSE_ID, SUPPLIER_ID, ITEM_NAME, ITEM_COST, ESTIMATE, 
 ACTUAL, EXPENSE_ITEM_ID, ORDER_ROW, CHECKSUM)
AS 
select EXPENSE_ID
,      SUPPLIER_ID
,      ITEM_NAME
,      ITEM_COST
,      ESTIMATE
,      ACTUAL
,      EXPENSE_ITEM_ID
,      ORDER_ROW
,      rnt_sys_checksum_rec_pkg.get_checksum('EXPENSE_ID='||EXPENSE_ID||'SUPPLIER_ID='||SUPPLIER_ID||'ITEM_NAME='||ITEM_NAME||'ITEM_COST='||ITEM_COST||'ESTIMATE='||ESTIMATE||'ACTUAL='||ACTUAL||'EXPENSE_ITEM_ID='||EXPENSE_ITEM_ID||'ORDER_ROW='||ORDER_ROW) as CHECKSUM
from RNT_EXPENSE_ITEMS
/
