SET DEFINE OFF;
Insert into RNT_LOOKUP_TYPES
   (LOOKUP_TYPE_ID, LOOKUP_TYPE_CODE, LOOKUP_TYPE_DESCRIPTION)
 Values
   (4, 'TENANT_STATUS', 'Tenant status');
Insert into RNT_LOOKUP_TYPES
   (LOOKUP_TYPE_ID, LOOKUP_TYPE_CODE, LOOKUP_TYPE_DESCRIPTION)
 Values
   (1, 'STATES', 'States of USA');
Insert into RNT_LOOKUP_TYPES
   (LOOKUP_TYPE_ID, LOOKUP_TYPE_CODE, LOOKUP_TYPE_DESCRIPTION)
 Values
   (2, 'RENT_PERIOD', 'Rent period for agreements.');
Insert into RNT_LOOKUP_TYPES
   (LOOKUP_TYPE_ID, LOOKUP_TYPE_CODE, LOOKUP_TYPE_DESCRIPTION)
 Values
   (3, 'FEE_TYPE', 'Fee type for agreements');
COMMIT;


SET DEFINE OFF;
Insert into RNT_LOOKUP_VALUES
   (LOOKUP_VALUE_ID, LOOKUP_CODE, LOOKUP_VALUE, LOOKUP_TYPE_ID)
 Values
   (9, 'ACTIVE', 'Active', 4);
Insert into RNT_LOOKUP_VALUES
   (LOOKUP_VALUE_ID, LOOKUP_CODE, LOOKUP_VALUE, LOOKUP_TYPE_ID)
 Values
   (10, 'FORMER', 'Former', 4);
Insert into RNT_LOOKUP_VALUES
   (LOOKUP_VALUE_ID, LOOKUP_CODE, LOOKUP_VALUE, LOOKUP_TYPE_ID)
 Values
   (1, 'NC', 'North Carolina', 1);
Insert into RNT_LOOKUP_VALUES
   (LOOKUP_VALUE_ID, LOOKUP_CODE, LOOKUP_VALUE, LOOKUP_TYPE_ID)
 Values
   (2, 'FL', 'Florida', 1);
Insert into RNT_LOOKUP_VALUES
   (LOOKUP_VALUE_ID, LOOKUP_CODE, LOOKUP_VALUE, LOOKUP_TYPE_ID)
 Values
   (3, 'MONTH', 'Month', 2);
Insert into RNT_LOOKUP_VALUES
   (LOOKUP_VALUE_ID, LOOKUP_CODE, LOOKUP_VALUE, LOOKUP_TYPE_ID)
 Values
   (4, 'BI-MONTH', 'Bi-Month', 2);
Insert into RNT_LOOKUP_VALUES
   (LOOKUP_VALUE_ID, LOOKUP_CODE, LOOKUP_VALUE, LOOKUP_TYPE_ID)
 Values
   (5, '2WEEKS', '2-Weeks', 2);
Insert into RNT_LOOKUP_VALUES
   (LOOKUP_VALUE_ID, LOOKUP_CODE, LOOKUP_VALUE, LOOKUP_TYPE_ID)
 Values
   (6, 'WEEK', 'Week', 2);
Insert into RNT_LOOKUP_VALUES
   (LOOKUP_VALUE_ID, LOOKUP_CODE, LOOKUP_VALUE, LOOKUP_TYPE_ID)
 Values
   (7, 'DISCOUNT', 'Discount', 3);
Insert into RNT_LOOKUP_VALUES
   (LOOKUP_VALUE_ID, LOOKUP_CODE, LOOKUP_VALUE, LOOKUP_TYPE_ID)
 Values
   (8, 'LATE_FEE', 'Late Fee', 3);
COMMIT;
