--
-- Create Schema Script 
--   Database Version   : 10.2.0.1.0 
--   TOAD Version       : 9.0.0.160 
--   DB Connect String  : XE 
--   Schema             : RNTMGR 
--   Script Created by  : RNTMGR 
--   Script Created at  : 24.04.2007 20:35:11 
--   Physical Location  :  
--   Notes              :  
--

-- Object Counts: 
--   Views: 8           Columns: 86         


--
-- RNT_USERS_V  (View) 
--
CREATE OR REPLACE FORCE VIEW RNT_USERS_V
(USER_ID, USER_LOGIN, USER_NAME, USER_PASSWORD, IS_ACTIVE_YN, 
 CHECKSUM)
AS 
select 
   USER_ID, USER_LOGIN, USER_NAME, 
   USER_PASSWORD, IS_ACTIVE_YN,
   RNT_USERS_PKG.GET_CHECKSUM(USER_ID) as CHECKSUM
from RNT_USERS;


--
-- RNT_USER_ASSIGNMENTS_V  (View) 
--
CREATE OR REPLACE FORCE VIEW RNT_USER_ASSIGNMENTS_V
(USER_ID, USER_LOGIN, USER_NAME, IS_ACTIVE_YN, ROLE_CODE, 
 ROLE_NAME, ROLE_ID, USER_ASSIGN_ID, BUSINESS_ID, BUSINESS_NAME, 
 PARENT_BUSINESS_ID, CHECKSUM)
AS 
select u.USER_ID, u.USER_LOGIN, u.USER_NAME, u.IS_ACTIVE_YN,
       r.ROLE_CODE, r.ROLE_NAME, r.ROLE_ID,
       a.USER_ASSIGN_ID, b.BUSINESS_ID, b.BUSINESS_NAME,
       b.PARENT_BUSINESS_ID,
       RNT_USER_ASSIGNMENTS_PKG.GET_CHECKSUM(a.USER_ASSIGN_ID) as CHECKSUM
from RNT_USERS u,
     RNT_USER_ROLES r,
     RNT_USER_ASSIGNMENTS a,
     RNT_BUSINESS_UNITS b
where a.ROLE_ID = r.ROLE_ID
  and a.USER_ID= u.USER_ID
  and a.BUSINESS_ID = b.BUSINESS_ID;


--
-- RNT_BUSINESS_UNITS_V  (View) 
--
CREATE OR REPLACE FORCE VIEW RNT_BUSINESS_UNITS_V
(BUSINESS_ID, BUSINESS_NAME, PARENT_BUSINESS_ID, CHECKSUM)
AS 
select BUSINESS_ID, BUSINESS_NAME, PARENT_BUSINESS_ID, RNT_BUSINESS_UNITS_PKG.GET_CHECKSUM(BUSINESS_ID) as CHECKSUM
from RNT_BUSINESS_UNITS          
start with (PARENT_BUSINESS_ID = 0 
            and BUSINESS_ID in (select BUSINESS_ID 
                                from RNT_USER_ASSIGNMENTS_V
                                where USER_ID = RNT_USERS_PKG.GET_USER()
                                  and ROLE_CODE = RNT_USERS_PKG.GET_ROLE()
                                )
           )                    
         or (BUSINESS_ID in (select BUSINESS_ID 
                             from RNT_USER_ASSIGNMENTS_V
                             where USER_ID = RNT_USERS_PKG.GET_USER()
                             and ROLE_CODE = RNT_USERS_PKG.GET_ROLE()
                            )
             )                 
connect by prior BUSINESS_ID = PARENT_BUSINESS_ID;


--
-- RNT_LOANS_V  (View) 
--
CREATE OR REPLACE FORCE VIEW RNT_LOANS_V
(LOAN_ID, PROPERTY_ID, POSITION, LOAN_DATE, LOAN_AMOUNT, 
 TERM, INTEREST_RATE, CREDIT_LINE_YN, ARM_YN, BALLOON_DATE, 
 AMORTIZATION_START, SETTLEMENT_DATE, CHECKSUM)
AS 
select 
   LOAN_ID, PROPERTY_ID, POSITION, 
   LOAN_DATE, LOAN_AMOUNT, 
   TERM, INTEREST_RATE, CREDIT_LINE_YN, 
   ARM_YN, BALLOON_DATE, AMORTIZATION_START, 
   SETTLEMENT_DATE, RNT_LOANS_PKG.GET_CHECKSUM(LOAN_ID) as CHECKSUM
from RNT_LOANS;


--
-- RNT_LOOKUP_VALUES_V  (View) 
--
CREATE OR REPLACE FORCE VIEW RNT_LOOKUP_VALUES_V
(LOOKUP_TYPE_ID, LOOKUP_TYPE_CODE, LOOKUP_VALUE_ID, LOOKUP_CODE, LOOKUP_VALUE)
AS 
select t.LOOKUP_TYPE_ID, 
       t.LOOKUP_TYPE_CODE,
       v.LOOKUP_VALUE_ID, 
       v.LOOKUP_CODE, 
       v.LOOKUP_VALUE 
from RNT_LOOKUP_TYPES t,
     RNT_LOOKUP_VALUES v
where t.LOOKUP_TYPE_ID = v.LOOKUP_TYPE_ID;


--
-- RNT_PROPERTIES_V  (View) 
--
CREATE OR REPLACE FORCE VIEW RNT_PROPERTIES_V
(PROPERTY_ID, BUSINESS_ID, BUSINESS_NAME, UNITS, ADDRESS1, 
 ADDRESS2, CITY, STATE, STATE_NAME, ZIPCODE, 
 DATE_PURCHASED, PURCHASE_PRICE, LAND_VALUE, DEPRECIATION_TERM, YEAR_BUILT, 
 BUILDING_SIZE, LOT_SIZE, DATE_SOLD, SALE_AMOUNT, NOTE_YN, 
 COUNT_UNITS, CHECKSUM)
AS 
select 
   p.PROPERTY_ID, 
   p.BUSINESS_ID,
   u.BUSINESS_NAME,
   p.UNITS,
   p.ADDRESS1, 
   p.ADDRESS2, 
   p.CITY, 
   p.STATE,
   v.LOOKUP_VALUE as STATE_NAME, 
   p.ZIPCODE, 
   p.DATE_PURCHASED, 
   p.PURCHASE_PRICE, 
   p.LAND_VALUE, 
   p.DEPRECIATION_TERM, 
   p.YEAR_BUILT, 
   p.BUILDING_SIZE, 
   p.LOT_SIZE, 
   p.DATE_SOLD, 
   p.SALE_AMOUNT, 
   p.NOTE_YN,
   (select count(*)  
    from RNT_PROPERTY_UNITS 
    where PROPERTY_ID = p.PROPERTY_ID
   ) as COUNT_UNITS,
   RNT_PROPERTIES_PKG.GET_CKECKSUM(p.PROPERTY_ID) as CHECKSUM 
from RNT_PROPERTIES p,
     RNT_BUSINESS_UNITS_V u,
     RNT_LOOKUP_VALUES_V v
where p.BUSINESS_ID = u.BUSINESS_ID
  and v.LOOKUP_TYPE_CODE = 'STATES'
  and v.LOOKUP_CODE = p.STATE;


--
-- RNT_PROPERTY_UNITS_V  (View) 
--
CREATE OR REPLACE FORCE VIEW RNT_PROPERTY_UNITS_V
(UNIT_ID, PROPERTY_ID, UNIT_NAME, UNIT_SIZE, BEDROOMS, 
 BATHROOMS, CHECKSUM)
AS 
select UNIT_ID, 
       PROPERTY_ID, 
       UNIT_NAME, UNIT_SIZE, BEDROOMS, 
       BATHROOMS,
       RNT_PROPERTY_UNITS_PKG.GET_CHECKSUM(UNIT_ID) as CHECKSUM
from RNT_PROPERTY_UNITS
order by UNIT_NAME;


--
-- RNT_TENANCY_AGREEMENT_V  (View) 
--
CREATE OR REPLACE FORCE VIEW RNT_TENANCY_AGREEMENT_V
(AGREEMENT_ID, UNIT_ID, AGREEMENT_DATE, TERM, AMOUNT, 
 AMOUNT_PERIOD, DATE_AVAILABLE, DEPOSIT, LAST_MONTH, DISCOUNT_AMOUNT, 
 DISCOUNT_TYPE, DISCOUNT_PERIOD, PROPERTY_ID, UNIT_NAME, AMOUNTH_PERIOD_NAME, 
 DISCOUNT_TYPE_NAME, CHECKSUM)
AS 
select 
   a.AGREEMENT_ID, 
   a.UNIT_ID, 
   a.AGREEMENT_DATE, 
   a.TERM, 
   a.AMOUNT, 
   a.AMOUNT_PERIOD, 
   a.DATE_AVAILABLE, 
   a.DEPOSIT, 
   a.LAST_MONTH, 
   a.DISCOUNT_AMOUNT, 
   a.DISCOUNT_TYPE, 
   a.DISCOUNT_PERIOD,
   u.PROPERTY_ID,
   u.UNIT_NAME,
   lv.LOOKUP_VALUE as AMOUNTH_PERIOD_NAME,
   dt.LOOKUP_VALUE as DISCOUNT_TYPE_NAME,
   RNT_TENANCY_AGREEMENT_PKG.GET_CHECKSUM(a.AGREEMENT_ID) as CHECKSUM
from RNT_TENANCY_AGREEMENT a,
     RNT_PROPERTY_UNITS u,
     RNT_LOOKUP_VALUES_V lv,
     (select LOOKUP_CODE, LOOKUP_VALUE from RNT_LOOKUP_VALUES_V where LOOKUP_TYPE_CODE = 'FEE_TYPE') dt
where u.UNIT_ID = a.UNIT_ID
  and lv.LOOKUP_TYPE_CODE = 'RENT_PERIOD'
  and lv.LOOKUP_CODE = a.AMOUNT_PERIOD     
  and dt.LOOKUP_CODE(+) = a.DISCOUNT_TYPE;


