Insert into RNT_USER_ROLES
   (ROLE_ID, ROLE_CODE, ROLE_NAME)
 Values
   (5, 'BUSINESS_OWNER', 'Business owner');
COMMIT;

ALTER VIEW RNT_ACCOUNTS_PAYABLE_V COMPILE;

ALTER VIEW RNT_ACCNTS_PAYABLE_EXPENSES_V COMPILE;

ALTER PACKAGE RNT_ACCOUNTS_PAYABLE_PKG COMPILE;

ALTER PACKAGE RNT_ACCOUNTS_PAYABLE_PKG COMPILE BODY;