ALTER TABLE RNT_USERS
 ADD (USER_LASTNAME  VARCHAR2(50 BYTE));

ALTER TABLE RNT_USERS
 ADD (PRIMARY_PHONE  VARCHAR2(20 BYTE));

ALTER TABLE RNT_USERS
 ADD (SECONDARY_PHONE  VARCHAR2(20 BYTE));

ALTER TABLE RNT_USERS
 ADD (IS_SUBSCRIBED_YN  VARCHAR2(1 BYTE));


COMMENT ON COLUMN RNT_USERS.USER_LASTNAME IS 'User last name';

COMMENT ON COLUMN RNT_USERS.PRIMARY_PHONE IS 'Primary phone';

COMMENT ON COLUMN RNT_USERS.SECONDARY_PHONE IS 'Secondary phone';

COMMENT ON COLUMN RNT_USERS.IS_SUBSCRIBED_YN IS 'Is subscribed user?';
