CREATE OR REPLACE FORCE VIEW RNT_USER_ASSIGNMENTS_V
(USER_ID, USER_LOGIN, USER_LASTNAME, USER_NAME, IS_ACTIVE_YN, 
 IS_SUBSCRIBED_YN, ROLE_CODE, ROLE_NAME, ROLE_ID, USER_ASSIGN_ID, 
 BUSINESS_ID, BUSINESS_NAME, PARENT_BUSINESS_ID, CHECKSUM)
AS 
select u.USER_ID, u.USER_LOGIN, u.USER_LASTNAME, u.USER_NAME, u.IS_ACTIVE_YN,
       u.IS_SUBSCRIBED_YN, 
       r.ROLE_CODE, r.ROLE_NAME, r.ROLE_ID,
       a.USER_ASSIGN_ID, b.BUSINESS_ID, b.BUSINESS_NAME,
       b.PARENT_BUSINESS_ID,
       RNT_USER_ASSIGNMENTS_PKG.GET_CHECKSUM(a.USER_ASSIGN_ID) as CHECKSUM
from RNT_USERS u,
     RNT_USER_ROLES r,
     RNT_USER_ASSIGNMENTS a,
     RNT_BUSINESS_UNITS b
where a.ROLE_ID = r.ROLE_ID
  and a.USER_ID= u.USER_ID
  and a.BUSINESS_ID = b.BUSINESS_ID;

CREATE OR REPLACE FORCE VIEW RNT_USERS_V
(USER_ID, USER_LOGIN, USER_NAME, USER_PASSWORD, IS_ACTIVE_YN, 
 USER_LASTNAME, PRIMARY_PHONE, SECONDARY_PHONE, IS_SUBSCRIBED_YN, CHECKSUM)
AS 
select 
   USER_ID, USER_LOGIN, USER_NAME, 
   USER_PASSWORD, IS_ACTIVE_YN,
   USER_LASTNAME, PRIMARY_PHONE, 
   SECONDARY_PHONE, IS_SUBSCRIBED_YN,
   RNT_USERS_PKG.GET_CHECKSUM(USER_ID) as CHECKSUM
from RNT_USERS;