CREATE OR REPLACE FORCE VIEW RNT_EXPENSE_ITEMS_V
(EXPENSE_ID, SUPPLIER_ID, ITEM_NAME, ITEM_COST, ESTIMATE, 
 ACTUAL, EXPENSE_ITEM_ID, CHECKSUM)
AS 
select EXPENSE_ID
,      SUPPLIER_ID
,      ITEM_NAME
,      ITEM_COST
,      ESTIMATE
,      ACTUAL
,      EXPENSE_ITEM_ID
,      rnt_sys_checksum_rec_pkg.get_checksum('EXPENSE_ID='||EXPENSE_ID||'SUPPLIER_ID='||SUPPLIER_ID||'ITEM_NAME='||ITEM_NAME||'ITEM_COST='||ITEM_COST||'ESTIMATE='||ESTIMATE||'ACTUAL='||ACTUAL||'EXPENSE_ITEM_ID='||EXPENSE_ITEM_ID) as CHECKSUM
from RNT_EXPENSE_ITEMS;
