CREATE TABLE RNT_EXPENSE_ITEMS
( EXPENSE_ITEM_ID  NUMBER                       NOT NULL,
  EXPENSE_ID       NUMBER                       NOT NULL,
  SUPPLIER_ID      NUMBER                       NOT NULL,
  ITEM_NAME        VARCHAR2(60)                 NOT NULL,
  ITEM_COST        NUMBER                       NOT NULL,
  ESTIMATE         NUMBER,
  ACTUAL           NUMBER )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN RNT_EXPENSE_ITEMS.EXPENSE_ITEM_ID IS 'Primary Key';

ALTER TABLE RNT_EXPENSE_ITEMS
 ADD CONSTRAINT RNT_EXPENSE_ITEMS_PK
 PRIMARY KEY
 (EXPENSE_ITEM_ID);


CREATE UNIQUE INDEX RNT_EXPENSE_ITEMS_U1 ON RNT_EXPENSE_ITEMS
(EXPENSE_ID, SUPPLIER_ID, ITEM_NAME)
LOGGING
NOPARALLEL;

CREATE INDEX RNT_EXPENSE_ITEMS_I1 ON RNT_EXPENSE_ITEMS
(SUPPLIER_ID)
LOGGING
NOPARALLEL;



ALTER TABLE RNT_EXPENSE_ITEMS
 ADD CONSTRAINT RNT_EXPENSE_ITEMS_F1 
 FOREIGN KEY (EXPENSE_ID) 
 REFERENCES RNT_PROPERTY_EXPENSES (EXPENSE_ID);

ALTER TABLE RNT_EXPENSE_ITEMS
 ADD CONSTRAINT RNT_EXPENSE_ITEMS_F2 
 FOREIGN KEY (SUPPLIER_ID) 
 REFERENCES RNT_SUPPLIERS_ALL (SUPPLIER_ID);