--
-- Create Schema Script 
--   Database Version   : 10.2.0.1.0 
--   TOAD Version       : 9.0.0.160 
--   DB Connect String  : XE 
--   Schema             : RNTMGR 
--   Script Created by  : RNTMGR 
--   Script Created at  : 09.04.2007 22:59:31 
--   Physical Location  :  
--   Notes              :  
--

-- Object Counts: 
--   Views: 5           


--
-- RNT_LOOKUP_VALUES_V  (View) 
--
CREATE OR REPLACE FORCE VIEW RNT_LOOKUP_VALUES_V
AS 
select t.LOOKUP_TYPE_ID, 
       t.LOOKUP_TYPE_CODE,
       v.LOOKUP_VALUE_ID, 
       v.LOOKUP_CODE, 
       v.LOOKUP_VALUE 
from RNT_LOOKUP_TYPES t,
     RNT_LOOKUP_VALUES v
where t.LOOKUP_TYPE_ID = v.LOOKUP_TYPE_ID;


--
-- RNT_PROPERTY_UNITS_V  (View) 
--
CREATE OR REPLACE FORCE VIEW RNT_PROPERTY_UNITS_V
AS 
select UNIT_ID, 
       PROPERTY_ID, 
       UNIT_NAME, UNIT_SIZE, BEDROOMS, 
       BATHROOMS,
       RNT_PROPERTY_UNITS_PKG.GET_CHECKSUM(UNIT_ID) as CHECKSUM
from RNT_PROPERTY_UNITS
order by UNIT_NAME;


--
-- RNT_LOANS_V  (View) 
--
CREATE OR REPLACE FORCE VIEW RNT_LOANS_V
AS 
select 
   LOAN_ID, PROPERTY_ID, POSITION, 
   LOAN_DATE, LOAN_AMOUNT, 
   TERM, INTEREST_RATE, CREDIT_LINE_YN, 
   ARM_YN, BALLOON_DATE, AMORTIZATION_START, 
   SETTLEMENT_DATE, RNT_LOANS_PKG.GET_CHECKSUM(LOAN_ID) as CHECKSUM
from RNT_LOANS;


--
-- RNT_PROPERTIES_V  (View) 
--
CREATE OR REPLACE FORCE VIEW RNT_PROPERTIES_V
AS 
select 
   p.PROPERTY_ID, 
   p.BUSINESS_ID,
   u.BUSINESS_NAME,
   p.UNITS,
   p.ADDRESS1, 
   p.ADDRESS2, 
   p.CITY, 
   p.STATE,
   v.LOOKUP_VALUE as STATE_NAME, 
   p.ZIPCODE, 
   p.DATE_PURCHASED, 
   p.PURCHASE_PRICE, 
   p.LAND_VALUE, 
   p.DEPRECIATION_TERM, 
   p.YEAR_BUILT, 
   p.BUILDING_SIZE, 
   p.LOT_SIZE, 
   p.DATE_SOLD, 
   p.SALE_AMOUNT, 
   p.NOTE_YN,
   (select count(*)  
    from RNT_PROPERTY_UNITS 
    where PROPERTY_ID = p.PROPERTY_ID
   ) as COUNT_UNITS,
   RNT_PROPERTIES_PKG.GET_CKECKSUM(p.PROPERTY_ID) as CHECKSUM 
from RNT_PROPERTIES p,
     RNT_BUSINESS_UNITS u,
     RNT_LOOKUP_VALUES_V v
where p.BUSINESS_ID = u.BUSINESS_ID
  and v.LOOKUP_TYPE_CODE = 'STATES'
  and v.LOOKUP_CODE = p.STATE;


--
-- RNT_TENANCY_AGREEMENT_V  (View) 
--
CREATE OR REPLACE FORCE VIEW RNT_TENANCY_AGREEMENT_V
AS 
select 
   a.AGREEMENT_ID, 
   a.UNIT_ID, 
   a.AGREEMENT_DATE, 
   a.TERM, 
   a.AMOUNT, 
   a.AMOUNT_PERIOD, 
   a.EFFECTIVE_DATE, 
   a.DEPOSIT, 
   a.LAST_MONTH, 
   a.DISCOUNT_AMOUNT, 
   a.DISCOUNT_TYPE, 
   a.DISCOUNT_PERIOD,
   u.PROPERTY_ID,
   u.UNIT_NAME,
   lv.LOOKUP_VALUE as AMOUNTH_PERIOD_NAME,
   dt.LOOKUP_VALUE as DISCOUNT_TYPE_NAME,
   RNT_TENANCY_AGREEMENT_PKG.GET_CHECKSUM(a.AGREEMENT_ID) as CHECKSUM
from RNT_TENANCY_AGREEMENT a,
     RNT_PROPERTY_UNITS u,
     RNT_LOOKUP_VALUES_V lv,
     (select LOOKUP_CODE, LOOKUP_VALUE from RNT_LOOKUP_VALUES_V where LOOKUP_TYPE_CODE = 'FEE_TYPE') dt
where u.UNIT_ID = a.UNIT_ID
  and lv.LOOKUP_TYPE_CODE = 'RENT_PERIOD'
  and lv.LOOKUP_CODE = a.AMOUNT_PERIOD     
  and dt.LOOKUP_CODE(+) = a.DISCOUNT_TYPE;


