ALTER PACKAGE RNT_PAYMENT_ALLOCATIONS_PKG COMPILE BODY;

ALTER PACKAGE RNT_GEN_PERIODS_PKG COMPILE BODY;

ALTER PACKAGE RNT_SECTION8_OFFICES_PKG COMPILE;

ALTER PACKAGE RNT_PEOPLE_PKG COMPILE;

ALTER PACKAGE RNT_SECTION8_OFFICES_PKG COMPILE BODY;

ALTER PACKAGE RNT_PAYMENTS_PKG COMPILE BODY;

ALTER PACKAGE RNT_PEOPLE_PKG COMPILE BODY;

 