CREATE OR REPLACE TYPE        T_SUMMARY_REC2 AS 
OBJECT(
        PROPERTY_ID NUMBER,
        ADDRESS1    VARCHAR (60), 
        NOI_VALUE NUMBER,
        CAP_RATE_VALUE NUMBER
      )
/

CREATE OR REPLACE type        T_SUMMARY_TABLE_2 as table of T_SUMMARY_REC2
/

SHOW ERRORS;

CREATE OR REPLACE TYPE T_SUMMARY_REC1 AS 
OBJECT(
        MONTH_DATE         DATE, 
        BUSINESS_ID        NUMBER,
        INCOME_AMOUNT      NUMBER,
        EXPENSE_AMOUNT     NUMBER,
        CASH_FLOW          NUMBER,
        OWED_AMOUNT        NUMBER,
        UNCOLLECTED_INCOME NUMBER,
        INVOICED_AMOUNT    NUMBER,
        UNPAID_INVOICES    NUMBER
      )
/

SHOW ERRORS;

CREATE OR REPLACE type T_SUMMARY_TABLE_1 as table of T_SUMMARY_REC1
/

SHOW ERRORS;


CREATE OR REPLACE TYPE               T_SUMMARY_ALERT_REC AS 
OBJECT(
        PROPERTY_ID NUMBER,
        UNIT_ID NUMBER,
        AGREEMENT_ID NUMBER, 
        TENANT_ID NUMBER, 
        BUSINESS_ID NUMBER,
        RECORD_TYPE varchar2(3), 
        DESCRIPTION varchar2(1200),
        PAYMENT_DUE_MONTH varchar2(6)     
       )
/

SHOW ERRORS;


CREATE OR REPLACE type               T_SUMMARY_ALERT_TABLE  as table of T_SUMMARY_ALERT_REC
/

SHOW ERRORS;

