CREATE INDEX RNT_PROPERTIES_I1 ON RNT_PROPERTIES
(BUSINESS_ID)
LOGGING
NOPARALLEL;

CREATE INDEX RNT_PAYMENT_ALLOCATIONS_I1 ON RNT_PAYMENT_ALLOCATIONS
(PAY_ALLOC_ID, PAYMENT_ID, AR_ID, AP_ID)
LOGGING
NOPARALLEL;

CREATE INDEX RNT_ACCOUNTS_RECEIVABLE_I1 ON RNT_ACCOUNTS_RECEIVABLE
(AR_ID, PAYMENT_TYPE, TENANT_ID, AGREEMENT_ID, LOAN_ID, 
BUSINESS_ID, IS_GENERATED_YN, AGREEMENT_ACTION_ID, PAYMENT_PROPERTY_ID, SOURCE_PAYMENT_ID, 
RECORD_TYPE)
LOGGING
NOPARALLEL;

CREATE INDEX RNT_ACCOUNTS_PAYABLE_I1 ON RNT_ACCOUNTS_PAYABLE
(PAYMENT_TYPE_ID, SUPPLIER_ID, PAYMENT_PROPERTY_ID, BUSINESS_ID, RECORD_TYPE, 
AP_ID)
LOGGING
NOPARALLEL;

ALTER PACKAGE RNT_AGREEMENT_ACTIONS_PKG COMPILE BODY;