declare

procedure insert_zip(x_zip in xmltype) is

  v_zipcode       number(5);
  v_city          varchar2(35);
  v_state         varchar2(2);
  v_county        varchar2(25);
  v_city_id       number;
  v_count         number;


begin

  v_zipcode := x_zip.extract('/ZIP/ZIP_CODE/text()').getStringVal();
  v_city := x_zip.extract('/ZIP/CITY/text()').getStringVal();
  v_state := x_zip.extract('/ZIP/STATE/text()').getStringVal();
  v_county := x_zip.extract('/ZIP/COUNTY_NAME/text()').getStringVal();

dbms_output.put_line(v_zipcode||', '||v_city||', '||v_county||', '||v_state);

  select count(*)
  into v_count
  from rnt_cities
  where name = v_city
  and county = v_county
  and state  = v_state;

  if v_count = 0 then
    insert into rnt_cities (city_id, name, county, state)
    values (rnt_cities_seq.nextval, v_city, v_county, v_state)
    returning city_id into v_city_id;
  else
    select city_id
    into v_city_id
    from rnt_cities
    where name = v_city
    and county = v_county
    and state  = v_state;
  end if;

dbms_output.put_line('city_id='||v_city_id);

  select count(*)
  into v_count
  from rnt_zipcodes
  where zipcode = v_zipcode;

  if v_count = 0 then
    insert into rnt_zipcodes(zipcode)
    values (v_zipcode);
  end if;

  select count(*)
  into v_count
  from rnt_city_zipcodes
  where city_id = v_city_id
  and zipcode = v_zipcode;

  if v_count = 0 then
    insert into rnt_city_zipcodes (city_id, zipcode)
    values (v_city_id, v_zipcode);
  end if;

end insert_zip;


begin 

	insert_zip(xmltype('<ZIP>
		<ZIP_CODE>501</ZIP_CODE>
		<CITY>HOLTSVILLE</CITY>
		<STATE>NY</STATE>
		<AREA_CODE>631</AREA_CODE>
		<CITY_ALIAS_NAME>HOLTSVILLE</CITY_ALIAS_NAME>
		<CITY_ALIAS_ABBR/>
		<CITY_TYPE>P</CITY_TYPE>
		<COUNTY_NAME>SUFFOLK</COUNTY_NAME>
		<STATE_FIPS>36</STATE_FIPS>
		<COUNTY_FIPS>103</COUNTY_FIPS>
		<TIME_ZONE>5</TIME_ZONE>
		<DAY_LIGHT_SAVING>Y</DAY_LIGHT_SAVING>
		<LATITUDE>40.81518</LATITUDE>
		<LONGITUDE>-73.0455</LONGITUDE>
		<ELEVATION>104</ELEVATION>
	</ZIP>'));
	insert_zip(xmltype('<ZIP>
		<ZIP_CODE>15617</ZIP_CODE>
		<CITY>ARONA</CITY>
		<STATE>PA</STATE>
		<AREA_CODE>724</AREA_CODE>
		<CITY_ALIAS_NAME>ARONA</CITY_ALIAS_NAME>
		<CITY_ALIAS_ABBR/>
		<CITY_TYPE>P</CITY_TYPE>
		<COUNTY_NAME>WESTMORELAND</COUNTY_NAME>
		<STATE_FIPS>42</STATE_FIPS>
		<COUNTY_FIPS>129</COUNTY_FIPS>
		<TIME_ZONE>5</TIME_ZONE>
		<DAY_LIGHT_SAVING>Y</DAY_LIGHT_SAVING>
		<LATITUDE>40.26822</LATITUDE>
		<LONGITUDE>-79.66008</LONGITUDE>
		<ELEVATION>985</ELEVATION>
	</ZIP>'));
	insert_zip(xmltype('<ZIP>
		<ZIP_CODE>15618</ZIP_CODE>
		<CITY>AVONMORE</CITY>
		<STATE>PA</STATE>
		<AREA_CODE>724</AREA_CODE>
		<CITY_ALIAS_NAME>AVONMORE</CITY_ALIAS_NAME>
		<CITY_ALIAS_ABBR/>
		<CITY_TYPE>P</CITY_TYPE>
		<COUNTY_NAME>WESTMORELAND</COUNTY_NAME>
		<STATE_FIPS>42</STATE_FIPS>
		<COUNTY_FIPS>129</COUNTY_FIPS>
		<TIME_ZONE>5</TIME_ZONE>
		<DAY_LIGHT_SAVING>Y</DAY_LIGHT_SAVING>
		<LATITUDE>40.52826</LATITUDE>
		<LONGITUDE>-79.466872</LONGITUDE>
		<ELEVATION>858</ELEVATION>
	</ZIP>'));
	insert_zip(xmltype('<ZIP>
		<ZIP_CODE>15618</ZIP_CODE>
		<CITY>AVONMORE</CITY>
		<STATE>PA</STATE>
		<AREA_CODE>724</AREA_CODE>
		<CITY_ALIAS_NAME>EDMON</CITY_ALIAS_NAME>
		<CITY_ALIAS_ABBR/>
		<CITY_TYPE>N</CITY_TYPE>
		<COUNTY_NAME>WESTMORELAND</COUNTY_NAME>
		<STATE_FIPS>42</STATE_FIPS>
		<COUNTY_FIPS>129</COUNTY_FIPS>
		<TIME_ZONE>5</TIME_ZONE>
		<DAY_LIGHT_SAVING>Y</DAY_LIGHT_SAVING>
		<LATITUDE>40.52826</LATITUDE>
		<LONGITUDE>-79.466872</LONGITUDE>
		<ELEVATION>858</ELEVATION>
	</ZIP>'));
	insert_zip(xmltype('<ZIP>
		<ZIP_CODE>15619</ZIP_CODE>
		<CITY>BOVARD</CITY>
		<STATE>PA</STATE>
		<AREA_CODE>724</AREA_CODE>
		<CITY_ALIAS_NAME>BOVARD</CITY_ALIAS_NAME>
		<CITY_ALIAS_ABBR/>
		<CITY_TYPE>P</CITY_TYPE>
		<COUNTY_NAME>WESTMORELAND</COUNTY_NAME>
		<STATE_FIPS>42</STATE_FIPS>
		<COUNTY_FIPS>129</COUNTY_FIPS>
		<TIME_ZONE>5</TIME_ZONE>
		<DAY_LIGHT_SAVING>Y</DAY_LIGHT_SAVING>
		<LATITUDE>40.315872</LATITUDE>
		<LONGITUDE>-79.503724</LONGITUDE>
		<ELEVATION>1079</ELEVATION>
	</ZIP>'));
	insert_zip(xmltype('<ZIP>
		<ZIP_CODE>15620</ZIP_CODE>
		<CITY>BRADENVILLE</CITY>
		<STATE>PA</STATE>
		<AREA_CODE>724</AREA_CODE>
		<CITY_ALIAS_NAME>BRADENVILLE</CITY_ALIAS_NAME>
		<CITY_ALIAS_ABBR/>
		<CITY_TYPE>P</CITY_TYPE>
		<COUNTY_NAME>WESTMORELAND</COUNTY_NAME>
		<STATE_FIPS>42</STATE_FIPS>
		<COUNTY_FIPS>129</COUNTY_FIPS>
		<TIME_ZONE>5</TIME_ZONE>
		<DAY_LIGHT_SAVING>Y</DAY_LIGHT_SAVING>
		<LATITUDE>40.3051</LATITUDE>
		<LONGITUDE>-79.2631</LONGITUDE>
		<ELEVATION>1916</ELEVATION>
	</ZIP>'));
	insert_zip(xmltype('<ZIP>
		<ZIP_CODE>15621</ZIP_CODE>
		<CITY>CALUMET</CITY>
		<STATE>PA</STATE>
		<AREA_CODE>724</AREA_CODE>
		<CITY_ALIAS_NAME>CALUMET</CITY_ALIAS_NAME>
		<CITY_ALIAS_ABBR/>
		<CITY_TYPE>P</CITY_TYPE>
		<COUNTY_NAME>WESTMORELAND</COUNTY_NAME>
		<STATE_FIPS>42</STATE_FIPS>
		<COUNTY_FIPS>129</COUNTY_FIPS>
		<TIME_ZONE>5</TIME_ZONE>
		<DAY_LIGHT_SAVING>Y</DAY_LIGHT_SAVING>
		<LATITUDE>40.210833</LATITUDE>
		<LONGITUDE>-79.485556</LONGITUDE>
		<ELEVATION>998</ELEVATION>
	</ZIP>'));
	insert_zip(xmltype('<ZIP>
		<ZIP_CODE>15622</ZIP_CODE>
		<CITY>CHAMPION</CITY>
		<STATE>PA</STATE>
		<AREA_CODE>814</AREA_CODE>
		<CITY_ALIAS_NAME>CHAMPION</CITY_ALIAS_NAME>
		<CITY_ALIAS_ABBR/>
		<CITY_TYPE>P</CITY_TYPE>
		<COUNTY_NAME>WESTMORELAND</COUNTY_NAME>
		<STATE_FIPS>42</STATE_FIPS>
		<COUNTY_FIPS>129</COUNTY_FIPS>
		<TIME_ZONE>5</TIME_ZONE>
		<DAY_LIGHT_SAVING>Y</DAY_LIGHT_SAVING>
		<LATITUDE>40.0425</LATITUDE>
		<LONGITUDE>-79.3231</LONGITUDE>
		<ELEVATION>2696</ELEVATION>
	</ZIP>'));
	insert_zip(xmltype('<ZIP>
		<ZIP_CODE>15623</ZIP_CODE>
		<CITY>CLARIDGE</CITY>
		<STATE>PA</STATE>
		<AREA_CODE>724</AREA_CODE>
		<CITY_ALIAS_NAME>CLARIDGE</CITY_ALIAS_NAME>
		<CITY_ALIAS_ABBR/>
		<CITY_TYPE>P</CITY_TYPE>
		<COUNTY_NAME>WESTMORELAND</COUNTY_NAME>
		<STATE_FIPS>42</STATE_FIPS>
		<COUNTY_FIPS>129</COUNTY_FIPS>
		<TIME_ZONE>5</TIME_ZONE>
		<DAY_LIGHT_SAVING>Y</DAY_LIGHT_SAVING>
		<LATITUDE>40.365556</LATITUDE>
		<LONGITUDE>-79.6225</LONGITUDE>
		<ELEVATION>1047</ELEVATION>
	</ZIP>'));
	insert_zip(xmltype('<ZIP>
		<ZIP_CODE>15624</ZIP_CODE>
		<CITY>CRABTREE</CITY>
		<STATE>PA</STATE>
		<AREA_CODE>724</AREA_CODE>
		<CITY_ALIAS_NAME>CRABTREE</CITY_ALIAS_NAME>
		<CITY_ALIAS_ABBR/>
		<CITY_TYPE>P</CITY_TYPE>
		<COUNTY_NAME>WESTMORELAND</COUNTY_NAME>
		<STATE_FIPS>42</STATE_FIPS>
		<COUNTY_FIPS>129</COUNTY_FIPS>
		<TIME_ZONE>5</TIME_ZONE>
		<DAY_LIGHT_SAVING>Y</DAY_LIGHT_SAVING>
		<LATITUDE>40.364046</LATITUDE>
		<LONGITUDE>-79.469652</LONGITUDE>
		<ELEVATION>1015</ELEVATION>
	</ZIP>'));
	insert_zip(xmltype('<ZIP>
		<ZIP_CODE>15625</ZIP_CODE>
		<CITY>DARRAGH</CITY>
		<STATE>PA</STATE>
		<AREA_CODE>724</AREA_CODE>
		<CITY_ALIAS_NAME>DARRAGH</CITY_ALIAS_NAME>
		<CITY_ALIAS_ABBR/>
		<CITY_TYPE>P</CITY_TYPE>
		<COUNTY_NAME>WESTMORELAND</COUNTY_NAME>
		<STATE_FIPS>42</STATE_FIPS>
		<COUNTY_FIPS>129</COUNTY_FIPS>
		<TIME_ZONE>5</TIME_ZONE>
		<DAY_LIGHT_SAVING>Y</DAY_LIGHT_SAVING>
		<LATITUDE>40.258527</LATITUDE>
		<LONGITUDE>-79.676214</LONGITUDE>
		<ELEVATION>1041</ELEVATION>
	</ZIP>'));
	insert_zip(xmltype('<ZIP>
		<ZIP_CODE>15626</ZIP_CODE>
		<CITY>DELMONT</CITY>
		<STATE>PA</STATE>
		<AREA_CODE>724</AREA_CODE>
		<CITY_ALIAS_NAME>DELMONT</CITY_ALIAS_NAME>
		<CITY_ALIAS_ABBR/>
		<CITY_TYPE>P</CITY_TYPE>
		<COUNTY_NAME>WESTMORELAND</COUNTY_NAME>
		<STATE_FIPS>42</STATE_FIPS>
		<COUNTY_FIPS>129</COUNTY_FIPS>
		<TIME_ZONE>5</TIME_ZONE>
		<DAY_LIGHT_SAVING>Y</DAY_LIGHT_SAVING>
		<LATITUDE>40.4073</LATITUDE>
		<LONGITUDE>-79.5743</LONGITUDE>
		<ELEVATION>1267</ELEVATION>
	</ZIP>'));
	insert_zip(xmltype('<ZIP>
		<ZIP_CODE>15627</ZIP_CODE>
		<CITY>DERRY</CITY>
		<STATE>PA</STATE>
		<AREA_CODE>724</AREA_CODE>
		<CITY_ALIAS_NAME>DERRY</CITY_ALIAS_NAME>
		<CITY_ALIAS_ABBR/>
		<CITY_TYPE>P</CITY_TYPE>
		<COUNTY_NAME>WESTMORELAND</COUNTY_NAME>
		<STATE_FIPS>42</STATE_FIPS>
		<COUNTY_FIPS>129</COUNTY_FIPS>
		<TIME_ZONE>5</TIME_ZONE>
		<DAY_LIGHT_SAVING>Y</DAY_LIGHT_SAVING>
		<LATITUDE>40.3493</LATITUDE>
		<LONGITUDE>-79.2885</LONGITUDE>
		<ELEVATION>1104</ELEVATION>
	</ZIP>'));
	insert_zip(xmltype('<ZIP>
		<ZIP_CODE>15628</ZIP_CODE>
		<CITY>DONEGAL</CITY>
		<STATE>PA</STATE>
		<AREA_CODE>724</AREA_CODE>
		<CITY_ALIAS_NAME>DONEGAL</CITY_ALIAS_NAME>
		<CITY_ALIAS_ABBR/>
		<CITY_TYPE>P</CITY_TYPE>
		<COUNTY_NAME>WESTMORELAND</COUNTY_NAME>
		<STATE_FIPS>42</STATE_FIPS>
		<COUNTY_FIPS>129</COUNTY_FIPS>
		<TIME_ZONE>5</TIME_ZONE>
		<DAY_LIGHT_SAVING>Y</DAY_LIGHT_SAVING>
		<LATITUDE>40.097934</LATITUDE>
		<LONGITUDE>-79.381906</LONGITUDE>
		<ELEVATION>1842</ELEVATION>
	</ZIP>'));
	insert_zip(xmltype('<ZIP>
		<ZIP_CODE>15629</ZIP_CODE>
		<CITY>EAST VANDERGRIFT</CITY>
		<STATE>PA</STATE>
		<AREA_CODE>724</AREA_CODE>
		<CITY_ALIAS_NAME>E VANDERGRIFT</CITY_ALIAS_NAME>
		<CITY_ALIAS_ABBR/>
		<CITY_TYPE>N</CITY_TYPE>
		<COUNTY_NAME>WESTMORELAND</COUNTY_NAME>
		<STATE_FIPS>42</STATE_FIPS>
		<COUNTY_FIPS>129</COUNTY_FIPS>
		<TIME_ZONE>5</TIME_ZONE>
		<DAY_LIGHT_SAVING>Y</DAY_LIGHT_SAVING>
		<LATITUDE>40.599534</LATITUDE>
		<LONGITUDE>-79.561819</LONGITUDE>
		<ELEVATION>798</ELEVATION>
	</ZIP>'));
	insert_zip(xmltype('<ZIP>
		<ZIP_CODE>15629</ZIP_CODE>
		<CITY>EAST VANDERGRIFT</CITY>
		<STATE>PA</STATE>
		<AREA_CODE>724</AREA_CODE>
		<CITY_ALIAS_NAME>EAST VANDERGRIFT</CITY_ALIAS_NAME>
		<CITY_ALIAS_ABBR>E VANDERGRIFT</CITY_ALIAS_ABBR>
		<CITY_TYPE>P</CITY_TYPE>
		<COUNTY_NAME>WESTMORELAND</COUNTY_NAME>
		<STATE_FIPS>42</STATE_FIPS>
		<COUNTY_FIPS>129</COUNTY_FIPS>
		<TIME_ZONE>5</TIME_ZONE>
		<DAY_LIGHT_SAVING>Y</DAY_LIGHT_SAVING>
		<LATITUDE>40.599534</LATITUDE>
		<LONGITUDE>-79.561819</LONGITUDE>
		<ELEVATION>798</ELEVATION>
	</ZIP>'));
	insert_zip(xmltype('<ZIP>
		<ZIP_CODE>15631</ZIP_CODE>
		<CITY>EVERSON</CITY>
		<STATE>PA</STATE>
		<AREA_CODE>724</AREA_CODE>
		<CITY_ALIAS_NAME>EVERSON</CITY_ALIAS_NAME>
		<CITY_ALIAS_ABBR/>
		<CITY_TYPE>P</CITY_TYPE>
		<COUNTY_NAME>FAYETTE</COUNTY_NAME>
		<STATE_FIPS>42</STATE_FIPS>
		<COUNTY_FIPS>51</COUNTY_FIPS>
		<TIME_ZONE>5</TIME_ZONE>
		<DAY_LIGHT_SAVING>Y</DAY_LIGHT_SAVING>
		<LATITUDE>40.091916</LATITUDE>
		<LONGITUDE>-79.586276</LONGITUDE>
		<ELEVATION>1089</ELEVATION>
	</ZIP>'));
	insert_zip(xmltype('<ZIP>
		<ZIP_CODE>15632</ZIP_CODE>
		<CITY>EXPORT</CITY>
		<STATE>PA</STATE>
		<AREA_CODE>724</AREA_CODE>
		<CITY_ALIAS_NAME>EXPORT</CITY_ALIAS_NAME>
		<CITY_ALIAS_ABBR/>
		<CITY_TYPE>P</CITY_TYPE>
		<COUNTY_NAME>WESTMORELAND</COUNTY_NAME>
		<STATE_FIPS>42</STATE_FIPS>
		<COUNTY_FIPS>129</COUNTY_FIPS>
		<TIME_ZONE>5</TIME_ZONE>
		<DAY_LIGHT_SAVING>Y</DAY_LIGHT_SAVING>
		<LATITUDE>40.4297</LATITUDE>
		<LONGITUDE>-79.6108</LONGITUDE>
		<ELEVATION>1257</ELEVATION>
	</ZIP>'));
	insert_zip(xmltype('<ZIP>
		<ZIP_CODE>15633</ZIP_CODE>
		<CITY>FORBES ROAD</CITY>
		<STATE>PA</STATE>
		<AREA_CODE>724</AREA_CODE>
		<CITY_ALIAS_NAME>FORBES RD</CITY_ALIAS_NAME>
		<CITY_ALIAS_ABBR/>
		<CITY_TYPE>O</CITY_TYPE>
		<COUNTY_NAME>WESTMORELAND</COUNTY_NAME>
		<STATE_FIPS>42</STATE_FIPS>
		<COUNTY_FIPS>129</COUNTY_FIPS>
		<TIME_ZONE>5</TIME_ZONE>
		<DAY_LIGHT_SAVING>Y</DAY_LIGHT_SAVING>
		<LATITUDE>40.357116</LATITUDE>
		<LONGITUDE>-79.522934</LONGITUDE>
		<ELEVATION>1091</ELEVATION>
	</ZIP>'));
	insert_zip(xmltype('<ZIP>
		<ZIP_CODE>15633</ZIP_CODE>
		<CITY>FORBES ROAD</CITY>
		<STATE>PA</STATE>
		<AREA_CODE>724</AREA_CODE>
		<CITY_ALIAS_NAME>FORBES ROAD</CITY_ALIAS_NAME>
		<CITY_ALIAS_ABBR/>
		<CITY_TYPE>P</CITY_TYPE>
		<COUNTY_NAME>WESTMORELAND</COUNTY_NAME>
		<STATE_FIPS>42</STATE_FIPS>
		<COUNTY_FIPS>129</COUNTY_FIPS>
		<TIME_ZONE>5</TIME_ZONE>
		<DAY_LIGHT_SAVING>Y</DAY_LIGHT_SAVING>
		<LATITUDE>40.357116</LATITUDE>
		<LONGITUDE>-79.522934</LONGITUDE>
		<ELEVATION>1091</ELEVATION>
	</ZIP>'));
	insert_zip(xmltype('<ZIP>
		<ZIP_CODE>15634</ZIP_CODE>
		<CITY>GRAPEVILLE</CITY>
		<STATE>PA</STATE>
		<AREA_CODE>724</AREA_CODE>
		<CITY_ALIAS_NAME>GRAPEVILLE</CITY_ALIAS_NAME>
		<CITY_ALIAS_ABBR/>
		<CITY_TYPE>P</CITY_TYPE>
		<COUNTY_NAME>WESTMORELAND</COUNTY_NAME>
		<STATE_FIPS>42</STATE_FIPS>
		<COUNTY_FIPS>129</COUNTY_FIPS>
		<TIME_ZONE>5</TIME_ZONE>
		<DAY_LIGHT_SAVING>Y</DAY_LIGHT_SAVING>
		<LATITUDE>40.324335</LATITUDE>
		<LONGITUDE>-79.605003</LONGITUDE>
		<ELEVATION>1177</ELEVATION>
	</ZIP>'));
	insert_zip(xmltype('<ZIP>
		<ZIP_CODE>15635</ZIP_CODE>
		<CITY>HANNASTOWN</CITY>
		<STATE>PA</STATE>
		<AREA_CODE>724</AREA_CODE>
		<CITY_ALIAS_NAME>HANNASTOWN</CITY_ALIAS_NAME>
		<CITY_ALIAS_ABBR/>
		<CITY_TYPE>P</CITY_TYPE>
		<COUNTY_NAME>WESTMORELAND</COUNTY_NAME>
		<STATE_FIPS>42</STATE_FIPS>
		<COUNTY_FIPS>129</COUNTY_FIPS>
		<TIME_ZONE>5</TIME_ZONE>
		<DAY_LIGHT_SAVING>Y</DAY_LIGHT_SAVING>
		<LATITUDE>40.351383</LATITUDE>
		<LONGITUDE>-79.496926</LONGITUDE>
		<ELEVATION>1047</ELEVATION>
	</ZIP>'));
	insert_zip(xmltype('<ZIP>
		<ZIP_CODE>15636</ZIP_CODE>
		<CITY>HARRISON CITY</CITY>
		<STATE>PA</STATE>
		<AREA_CODE>724</AREA_CODE>
		<CITY_ALIAS_NAME>HARRISON CITY</CITY_ALIAS_NAME>
		<CITY_ALIAS_ABBR/>
		<CITY_TYPE>P</CITY_TYPE>
		<COUNTY_NAME>WESTMORELAND</COUNTY_NAME>
		<STATE_FIPS>42</STATE_FIPS>
		<COUNTY_FIPS>129</COUNTY_FIPS>
		<TIME_ZONE>5</TIME_ZONE>
		<DAY_LIGHT_SAVING>Y</DAY_LIGHT_SAVING>
		<LATITUDE>40.3815</LATITUDE>
		<LONGITUDE>-79.6497</LONGITUDE>
		<ELEVATION>1131</ELEVATION>
	</ZIP>'));
	insert_zip(xmltype('<ZIP>
		<ZIP_CODE>15637</ZIP_CODE>
		<CITY>HERMINIE</CITY>
		<STATE>PA</STATE>
		<AREA_CODE>724</AREA_CODE>
		<CITY_ALIAS_NAME>HERMINIE</CITY_ALIAS_NAME>
		<CITY_ALIAS_ABBR/>
		<CITY_TYPE>P</CITY_TYPE>
		<COUNTY_NAME>WESTMORELAND</COUNTY_NAME>
		<STATE_FIPS>42</STATE_FIPS>
		<COUNTY_FIPS>129</COUNTY_FIPS>
		<TIME_ZONE>5</TIME_ZONE>
		<DAY_LIGHT_SAVING>Y</DAY_LIGHT_SAVING>
		<LATITUDE>40.262921</LATITUDE>
		<LONGITUDE>-79.714173</LONGITUDE>
		<ELEVATION>985</ELEVATION>
	</ZIP>'));
	insert_zip(xmltype('<ZIP>
		<ZIP_CODE>15638</ZIP_CODE>
		<CITY>HOSTETTER</CITY>
		<STATE>PA</STATE>
		<AREA_CODE>724</AREA_CODE>
		<CITY_ALIAS_NAME>HOSTETTER</CITY_ALIAS_NAME>
		<CITY_ALIAS_ABBR/>
		<CITY_TYPE>P</CITY_TYPE>
		<COUNTY_NAME>WESTMORELAND</COUNTY_NAME>
		<STATE_FIPS>42</STATE_FIPS>
		<COUNTY_FIPS>129</COUNTY_FIPS>
		<TIME_ZONE>5</TIME_ZONE>
		<DAY_LIGHT_SAVING>Y</DAY_LIGHT_SAVING>
		<LATITUDE>40.266111</LATITUDE>
		<LONGITUDE>-79.398611</LONGITUDE>
		<ELEVATION>1170</ELEVATION>
	</ZIP>'));
	insert_zip(xmltype('<ZIP>
		<ZIP_CODE>15639</ZIP_CODE>
		<CITY>HUNKER</CITY>
		<STATE>PA</STATE>
		<AREA_CODE>724</AREA_CODE>
		<CITY_ALIAS_NAME>HUNKER</CITY_ALIAS_NAME>
		<CITY_ALIAS_ABBR/>
		<CITY_TYPE>P</CITY_TYPE>
		<COUNTY_NAME>WESTMORELAND</COUNTY_NAME>
		<STATE_FIPS>42</STATE_FIPS>
		<COUNTY_FIPS>129</COUNTY_FIPS>
		<TIME_ZONE>5</TIME_ZONE>
		<DAY_LIGHT_SAVING>Y</DAY_LIGHT_SAVING>
		<LATITUDE>40.20251</LATITUDE>
		<LONGITUDE>-79.586821</LONGITUDE>
		<ELEVATION>1206</ELEVATION>
	</ZIP>'));
	insert_zip(xmltype('<ZIP>
		<ZIP_CODE>15640</ZIP_CODE>
		<CITY>HUTCHINSON</CITY>
		<STATE>PA</STATE>
		<AREA_CODE>724</AREA_CODE>
		<CITY_ALIAS_NAME>HUTCHINSON</CITY_ALIAS_NAME>
		<CITY_ALIAS_ABBR/>
		<CITY_TYPE>P</CITY_TYPE>
		<COUNTY_NAME>WESTMORELAND</COUNTY_NAME>
		<STATE_FIPS>42</STATE_FIPS>
		<COUNTY_FIPS>129</COUNTY_FIPS>
		<TIME_ZONE>5</TIME_ZONE>
		<DAY_LIGHT_SAVING>Y</DAY_LIGHT_SAVING>
		<LATITUDE>40.225968</LATITUDE>
		<LONGITUDE>-79.73336</LONGITUDE>
		<ELEVATION>977</ELEVATION>
	</ZIP>'));
	insert_zip(xmltype('<ZIP>
		<ZIP_CODE>15641</ZIP_CODE>
		<CITY>HYDE PARK</CITY>
		<STATE>PA</STATE>
		<AREA_CODE>724</AREA_CODE>
		<CITY_ALIAS_NAME>HYDE PARK</CITY_ALIAS_NAME>
		<CITY_ALIAS_ABBR/>
		<CITY_TYPE>P</CITY_TYPE>
		<COUNTY_NAME>WESTMORELAND</COUNTY_NAME>
		<STATE_FIPS>42</STATE_FIPS>
		<COUNTY_FIPS>129</COUNTY_FIPS>
		<TIME_ZONE>5</TIME_ZONE>
		<DAY_LIGHT_SAVING>Y</DAY_LIGHT_SAVING>
		<LATITUDE>40.630928</LATITUDE>
		<LONGITUDE>-79.590277</LONGITUDE>
		<ELEVATION>833</ELEVATION>
	</ZIP>'));
	insert_zip(xmltype('<ZIP>
		<ZIP_CODE>15642</ZIP_CODE>
		<CITY>IRWIN</CITY>
		<STATE>PA</STATE>
		<AREA_CODE>724</AREA_CODE>
		<CITY_ALIAS_NAME>N HUNTINGDON</CITY_ALIAS_NAME>
		<CITY_ALIAS_ABBR/>
		<CITY_TYPE>N</CITY_TYPE>
		<COUNTY_NAME>WESTMORELAND</COUNTY_NAME>
		<STATE_FIPS>42</STATE_FIPS>
		<COUNTY_FIPS>129</COUNTY_FIPS>
		<TIME_ZONE>5</TIME_ZONE>
		<DAY_LIGHT_SAVING>Y</DAY_LIGHT_SAVING>
		<LATITUDE>40.329557</LATITUDE>
		<LONGITUDE>-79.718024</LONGITUDE>
		<ELEVATION>1085</ELEVATION>
	</ZIP>'));
	insert_zip(xmltype('<ZIP>
		<ZIP_CODE>15642</ZIP_CODE>
		<CITY>IRWIN</CITY>
		<STATE>PA</STATE>
		<AREA_CODE>724</AREA_CODE>
		<CITY_ALIAS_NAME>NO HUNTINGDON</CITY_ALIAS_NAME>
		<CITY_ALIAS_ABBR/>
		<CITY_TYPE>N</CITY_TYPE>
		<COUNTY_NAME>WESTMORELAND</COUNTY_NAME>
		<STATE_FIPS>42</STATE_FIPS>
		<COUNTY_FIPS>129</COUNTY_FIPS>
		<TIME_ZONE>5</TIME_ZONE>
		<DAY_LIGHT_SAVING>Y</DAY_LIGHT_SAVING>
		<LATITUDE>40.329557</LATITUDE>
		<LONGITUDE>-79.718024</LONGITUDE>
		<ELEVATION>1085</ELEVATION>
	</ZIP>'));
	insert_zip(xmltype('<ZIP>
		<ZIP_CODE>15642</ZIP_CODE>
		<CITY>IRWIN</CITY>
		<STATE>PA</STATE>
		<AREA_CODE>724</AREA_CODE>
		<CITY_ALIAS_NAME>NORTH IRWIN</CITY_ALIAS_NAME>
		<CITY_ALIAS_ABBR/>
		<CITY_TYPE>N</CITY_TYPE>
		<COUNTY_NAME>WESTMORELAND</COUNTY_NAME>
		<STATE_FIPS>42</STATE_FIPS>
		<COUNTY_FIPS>129</COUNTY_FIPS>
		<TIME_ZONE>5</TIME_ZONE>
		<DAY_LIGHT_SAVING>Y</DAY_LIGHT_SAVING>
		<LATITUDE>40.329557</LATITUDE>
		<LONGITUDE>-79.718024</LONGITUDE>
		<ELEVATION>1085</ELEVATION>
	</ZIP>'));
	insert_zip(xmltype('<ZIP>
		<ZIP_CODE>15642</ZIP_CODE>
		<CITY>IRWIN</CITY>
		<STATE>PA</STATE>
		<AREA_CODE>724</AREA_CODE>
		<CITY_ALIAS_NAME>IRWIN</CITY_ALIAS_NAME>
		<CITY_ALIAS_ABBR/>
		<CITY_TYPE>P</CITY_TYPE>
		<COUNTY_NAME>WESTMORELAND</COUNTY_NAME>
		<STATE_FIPS>42</STATE_FIPS>
		<COUNTY_FIPS>129</COUNTY_FIPS>
		<TIME_ZONE>5</TIME_ZONE>
		<DAY_LIGHT_SAVING>Y</DAY_LIGHT_SAVING>
		<LATITUDE>40.329557</LATITUDE>
		<LONGITUDE>-79.718024</LONGITUDE>
		<ELEVATION>1085</ELEVATION>
	</ZIP>'));
	insert_zip(xmltype('<ZIP>
		<ZIP_CODE>15642</ZIP_CODE>
		<CITY>IRWIN</CITY>
		<STATE>PA</STATE>
		<AREA_CODE>724</AREA_CODE>
		<CITY_ALIAS_NAME>NORTH HUNTINGDON</CITY_ALIAS_NAME>
		<CITY_ALIAS_ABBR>N HUNTINGDON</CITY_ALIAS_ABBR>
		<CITY_TYPE>N</CITY_TYPE>
		<COUNTY_NAME>WESTMORELAND</COUNTY_NAME>
		<STATE_FIPS>42</STATE_FIPS>
		<COUNTY_FIPS>129</COUNTY_FIPS>
		<TIME_ZONE>5</TIME_ZONE>
		<DAY_LIGHT_SAVING>Y</DAY_LIGHT_SAVING>
		<LATITUDE>40.329557</LATITUDE>
		<LONGITUDE>-79.718024</LONGITUDE>
		<ELEVATION>1085</ELEVATION>
	</ZIP>'));
	insert_zip(xmltype('<ZIP>
		<ZIP_CODE>15644</ZIP_CODE>
		<CITY>JEANNETTE</CITY>
		<STATE>PA</STATE>
		<AREA_CODE>724</AREA_CODE>
		<CITY_ALIAS_NAME>JEANNETTE</CITY_ALIAS_NAME>
		<CITY_ALIAS_ABBR/>
		<CITY_TYPE>P</CITY_TYPE>
		<COUNTY_NAME>WESTMORELAND</COUNTY_NAME>
		<STATE_FIPS>42</STATE_FIPS>
		<COUNTY_FIPS>129</COUNTY_FIPS>
		<TIME_ZONE>5</TIME_ZONE>
		<DAY_LIGHT_SAVING>Y</DAY_LIGHT_SAVING>
		<LATITUDE>40.330297</LATITUDE>
		<LONGITUDE>-79.613372</LONGITUDE>
		<ELEVATION>1046</ELEVATION>
	</ZIP>'));
	insert_zip(xmltype('<ZIP>
		<ZIP_CODE>15646</ZIP_CODE>
		<CITY>JONES MILLS</CITY>
		<STATE>PA</STATE>
		<AREA_CODE>724</AREA_CODE>
		<CITY_ALIAS_NAME>JONES MILLS</CITY_ALIAS_NAME>
		<CITY_ALIAS_ABBR/>
		<CITY_TYPE>P</CITY_TYPE>
		<COUNTY_NAME>WESTMORELAND</COUNTY_NAME>
		<STATE_FIPS>42</STATE_FIPS>
		<COUNTY_FIPS>129</COUNTY_FIPS>
		<TIME_ZONE>5</TIME_ZONE>
		<DAY_LIGHT_SAVING>Y</DAY_LIGHT_SAVING>
		<LATITUDE>40.065316</LATITUDE>
		<LONGITUDE>-79.31582</LONGITUDE>
		<ELEVATION>2606</ELEVATION>
	</ZIP>'));
	insert_zip(xmltype('<ZIP>
		<ZIP_CODE>15647</ZIP_CODE>
		<CITY>LARIMER</CITY>
		<STATE>PA</STATE>
		<AREA_CODE>724</AREA_CODE>
		<CITY_ALIAS_NAME>LARIMER</CITY_ALIAS_NAME>
		<CITY_ALIAS_ABBR/>
		<CITY_TYPE>P</CITY_TYPE>
		<COUNTY_NAME>WESTMORELAND</COUNTY_NAME>
		<STATE_FIPS>42</STATE_FIPS>
		<COUNTY_FIPS>129</COUNTY_FIPS>
		<TIME_ZONE>5</TIME_ZONE>
		<DAY_LIGHT_SAVING>Y</DAY_LIGHT_SAVING>
		<LATITUDE>40.3418</LATITUDE>
		<LONGITUDE>-79.7231</LONGITUDE>
		<ELEVATION>916</ELEVATION>
	</ZIP>'));

end;
/
